# fly.toml app configuration file generated for ssh-machine on 2025-03-28T18:56:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = 'suspend'
  auto_start_machines = true

[checks]
  [checks.sshCheck]
      grace_period = "60s"
      interval = "15s"
      port = 2222
      timeout = "10s"
      type = "tcp"
