name: lazycloud-web
description: Helm chart for LazyCloud Web (Next.js Frontend)
version: 0.1.0
apiVersion: v2
keywords:
  - lazycloud
  - web
  - nextjs
  - frontend
sources:
home:

# This is the chart version. It will be updated with each release of the chart.
appVersion: 0.1.0
