# Staging environment values for Web

replicaCount: 1

image:
  repository: 534742592531.dkr.ecr.us-east-1.amazonaws.com/web
  pullPolicy: Always
  tag: "staging-latest"

ingress:
  hostname: staging.lazycloud.dev

# Lower resources for staging
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

secrets:
  name: "app-secrets-staging"