apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lazycloud-aws-load-balancer-controller
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{ .name }}-aws-load-balancer-controller'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: git@github.com:AmbientWare/lazycloud.git
        targetRevision: main
        path: deploy/platform/aws-load-balancer-controller
        helm:
          valueFiles:
            - values.yaml
            - 'values-{{ index .metadata.labels "region" }}.yaml'
      destination:
        server: '{{ .server }}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
