apiVersion: v1
kind: Secret
metadata:
  name: cluster-ash-1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    provider: hetzner
    cluster_id: ash-1
    region: us-east-1
    is-hub: "true"
    supports-staging: "false" # NOTE: enable later for staging
type: Opaque
stringData:
  name: ash-1
  server: https://kubernetes.default.svc
