apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lazycloud-services-staging
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  supports-staging: "true"
          - list:
              elements:
                - service: api-platform
                - service: web
  template:
    metadata:
      name: '{{ .name }}-{{ .service }}-staging'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: git@github.com:AmbientWare/lazycloud.git
        targetRevision: staging
        path: 'deploy/services/{{ .service }}'
        helm:
          valueFiles:
            - values.yaml
            - values-staging.yaml
            - 'values-{{ .name }}.yaml'
      destination:
        server: '{{ .server }}'
        namespace: lazycloud-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
