apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.orgName }}-{{ .Values.environment }}-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
