apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.orgName }}-{{ .Values.environment }}-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-credentials
            namespace: {{ .Values.aws.credentialsSecretNamespace }}
            key: access-key
          secretAccessKeySecretRef:
            name: aws-sm-credentials
            namespace: {{ .Values.aws.credentialsSecretNamespace }}
            key: secret-key
