{{- if .Values.cloudflare.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-external
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.orgName }}-{{ .Values.environment }}-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: apiToken
      remoteRef:
        key: {{ .Values.cloudflare.awsSecretName }}
        property: CLOUDFLARE_API_TOKEN
{{- end }}
