{{- if .Values.appSecrets.prod.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-external
  namespace: {{ .Values.appSecrets.prod.namespace }}
  annotations:
    # Deploy after ESO webhook is ready
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.orgName }}-{{ .Values.environment }}-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appSecrets.prod.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.appSecrets.prod.awsSecretName }}
{{- end }}
