{{- if .Values.appSecrets.staging.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-external
  namespace: {{ .Values.appSecrets.staging.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.orgName }}-{{ .Values.environment }}-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appSecrets.staging.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.appSecrets.staging.awsSecretName }}
{{- end }}
