{{- if .Values.appSecrets.prod.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appSecrets.prod.namespace }}
  labels:
    app.kubernetes.io/managed-by: external-secrets
{{- end }}
