# Shared across all regions
nodeRoleName: lazycloud-karpenter-node

karpenter:
  serviceAccount:
    name: karpenter

  controller:
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
