// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: host/v1/container.proto

package hostproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerLink_Connect_FullMethodName = "/lazycloud.host.v1.ContainerLink/Connect"
	ContainerLink_API_FullMethodName     = "/lazycloud.host.v1.ContainerLink/API"
)

// ContainerLinkClient is the client API for ContainerLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContainerLink connects the supervisor (PID 1 in a container) to the agent.
// The agent serves it on a Unix socket it creates for that container alone, so
// the socket identifies the container. Agent and supervisor ship together.
type ContainerLinkClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SupervisorMessage, SupervisorCommand], error)
	// API forwards one request to the container API, which the agent relays
	// to HostService.ContainerAPI. The agent sets head.container_id and
	// bounds body size and concurrent calls per container.
	API(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[APIRequest, APIResponse], error)
}

type containerLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerLinkClient(cc grpc.ClientConnInterface) ContainerLinkClient {
	return &containerLinkClient{cc}
}

func (c *containerLinkClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SupervisorMessage, SupervisorCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerLink_ServiceDesc.Streams[0], ContainerLink_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SupervisorMessage, SupervisorCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerLink_ConnectClient = grpc.BidiStreamingClient[SupervisorMessage, SupervisorCommand]

func (c *containerLinkClient) API(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[APIRequest, APIResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerLink_ServiceDesc.Streams[1], ContainerLink_API_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[APIRequest, APIResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerLink_APIClient = grpc.BidiStreamingClient[APIRequest, APIResponse]

// ContainerLinkServer is the server API for ContainerLink service.
// All implementations must embed UnimplementedContainerLinkServer
// for forward compatibility.
//
// ContainerLink connects the supervisor (PID 1 in a container) to the agent.
// The agent serves it on a Unix socket it creates for that container alone, so
// the socket identifies the container. Agent and supervisor ship together.
type ContainerLinkServer interface {
	Connect(grpc.BidiStreamingServer[SupervisorMessage, SupervisorCommand]) error
	// API forwards one request to the container API, which the agent relays
	// to HostService.ContainerAPI. The agent sets head.container_id and
	// bounds body size and concurrent calls per container.
	API(grpc.BidiStreamingServer[APIRequest, APIResponse]) error
	mustEmbedUnimplementedContainerLinkServer()
}

// UnimplementedContainerLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerLinkServer struct{}

func (UnimplementedContainerLinkServer) Connect(grpc.BidiStreamingServer[SupervisorMessage, SupervisorCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedContainerLinkServer) API(grpc.BidiStreamingServer[APIRequest, APIResponse]) error {
	return status.Error(codes.Unimplemented, "method API not implemented")
}
func (UnimplementedContainerLinkServer) mustEmbedUnimplementedContainerLinkServer() {}
func (UnimplementedContainerLinkServer) testEmbeddedByValue()                       {}

// UnsafeContainerLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerLinkServer will
// result in compilation errors.
type UnsafeContainerLinkServer interface {
	mustEmbedUnimplementedContainerLinkServer()
}

func RegisterContainerLinkServer(s grpc.ServiceRegistrar, srv ContainerLinkServer) {
	// If the following call panics, it indicates UnimplementedContainerLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerLink_ServiceDesc, srv)
}

func _ContainerLink_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerLinkServer).Connect(&grpc.GenericServerStream[SupervisorMessage, SupervisorCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerLink_ConnectServer = grpc.BidiStreamingServer[SupervisorMessage, SupervisorCommand]

func _ContainerLink_API_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerLinkServer).API(&grpc.GenericServerStream[APIRequest, APIResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerLink_APIServer = grpc.BidiStreamingServer[APIRequest, APIResponse]

// ContainerLink_ServiceDesc is the grpc.ServiceDesc for ContainerLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lazycloud.host.v1.ContainerLink",
	HandlerType: (*ContainerLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ContainerLink_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "API",
			Handler:       _ContainerLink_API_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "host/v1/container.proto",
}
