// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: host/v1/host.proto

package hostproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerPhase int32

const (
	ContainerPhase_CONTAINER_PHASE_UNSPECIFIED ContainerPhase = 0
	// Fetching the image, source and runtime.
	ContainerPhase_CONTAINER_PHASE_PREPARING ContainerPhase = 1
	// The container process runs; runner slots are loading.
	ContainerPhase_CONTAINER_PHASE_STARTING ContainerPhase = 2
	// Every slot loaded its handler; the container can claim tasks.
	ContainerPhase_CONTAINER_PHASE_READY ContainerPhase = 3
	// The container is gone. exit carries the reason.
	ContainerPhase_CONTAINER_PHASE_EXITED ContainerPhase = 4
)

// Enum value maps for ContainerPhase.
var (
	ContainerPhase_name = map[int32]string{
		0: "CONTAINER_PHASE_UNSPECIFIED",
		1: "CONTAINER_PHASE_PREPARING",
		2: "CONTAINER_PHASE_STARTING",
		3: "CONTAINER_PHASE_READY",
		4: "CONTAINER_PHASE_EXITED",
	}
	ContainerPhase_value = map[string]int32{
		"CONTAINER_PHASE_UNSPECIFIED": 0,
		"CONTAINER_PHASE_PREPARING":   1,
		"CONTAINER_PHASE_STARTING":    2,
		"CONTAINER_PHASE_READY":       3,
		"CONTAINER_PHASE_EXITED":      4,
	}
)

func (x ContainerPhase) Enum() *ContainerPhase {
	p := new(ContainerPhase)
	*p = x
	return p
}

func (x ContainerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[0].Descriptor()
}

func (ContainerPhase) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[0]
}

func (x ContainerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerPhase.Descriptor instead.
func (ContainerPhase) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{0}
}

type ExitReason int32

const (
	ExitReason_EXIT_REASON_UNSPECIFIED ExitReason = 0
	// A StopContainer command finished.
	ExitReason_EXIT_REASON_STOPPED ExitReason = 1
	// The handler failed to import or initialize.
	ExitReason_EXIT_REASON_LOAD_ERROR ExitReason = 2
	// Image, source or runtime preparation failed.
	ExitReason_EXIT_REASON_START_FAILED ExitReason = 3
	// The container or supervisor died unexpectedly.
	ExitReason_EXIT_REASON_CRASHED       ExitReason = 4
	ExitReason_EXIT_REASON_OUT_OF_MEMORY ExitReason = 5
)

// Enum value maps for ExitReason.
var (
	ExitReason_name = map[int32]string{
		0: "EXIT_REASON_UNSPECIFIED",
		1: "EXIT_REASON_STOPPED",
		2: "EXIT_REASON_LOAD_ERROR",
		3: "EXIT_REASON_START_FAILED",
		4: "EXIT_REASON_CRASHED",
		5: "EXIT_REASON_OUT_OF_MEMORY",
	}
	ExitReason_value = map[string]int32{
		"EXIT_REASON_UNSPECIFIED":   0,
		"EXIT_REASON_STOPPED":       1,
		"EXIT_REASON_LOAD_ERROR":    2,
		"EXIT_REASON_START_FAILED":  3,
		"EXIT_REASON_CRASHED":       4,
		"EXIT_REASON_OUT_OF_MEMORY": 5,
	}
)

func (x ExitReason) Enum() *ExitReason {
	p := new(ExitReason)
	*p = x
	return p
}

func (x ExitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[1].Descriptor()
}

func (ExitReason) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[1]
}

func (x ExitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExitReason.Descriptor instead.
func (ExitReason) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{1}
}

type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED CancelReason = 0
	CancelReason_CANCEL_REASON_CANCELLED   CancelReason = 1
	CancelReason_CANCEL_REASON_TIMED_OUT   CancelReason = 2
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_CANCELLED",
		2: "CANCEL_REASON_TIMED_OUT",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED": 0,
		"CANCEL_REASON_CANCELLED":   1,
		"CANCEL_REASON_TIMED_OUT":   2,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[2].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[2]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{2}
}

type PayloadEncoding int32

const (
	PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED PayloadEncoding = 0
	PayloadEncoding_PAYLOAD_ENCODING_JSON        PayloadEncoding = 1
	PayloadEncoding_PAYLOAD_ENCODING_CLOUDPICKLE PayloadEncoding = 2
)

// Enum value maps for PayloadEncoding.
var (
	PayloadEncoding_name = map[int32]string{
		0: "PAYLOAD_ENCODING_UNSPECIFIED",
		1: "PAYLOAD_ENCODING_JSON",
		2: "PAYLOAD_ENCODING_CLOUDPICKLE",
	}
	PayloadEncoding_value = map[string]int32{
		"PAYLOAD_ENCODING_UNSPECIFIED": 0,
		"PAYLOAD_ENCODING_JSON":        1,
		"PAYLOAD_ENCODING_CLOUDPICKLE": 2,
	}
)

func (x PayloadEncoding) Enum() *PayloadEncoding {
	p := new(PayloadEncoding)
	*p = x
	return p
}

func (x PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[3].Descriptor()
}

func (PayloadEncoding) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[3]
}

func (x PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEncoding.Descriptor instead.
func (PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{3}
}

type AttemptFailureKind int32

const (
	AttemptFailureKind_ATTEMPT_FAILURE_KIND_UNSPECIFIED AttemptFailureKind = 0
	// The handler raised.
	AttemptFailureKind_ATTEMPT_FAILURE_KIND_USER_ERROR AttemptFailureKind = 1
	// The slot process died while running the attempt.
	AttemptFailureKind_ATTEMPT_FAILURE_KIND_CRASHED AttemptFailureKind = 2
)

// Enum value maps for AttemptFailureKind.
var (
	AttemptFailureKind_name = map[int32]string{
		0: "ATTEMPT_FAILURE_KIND_UNSPECIFIED",
		1: "ATTEMPT_FAILURE_KIND_USER_ERROR",
		2: "ATTEMPT_FAILURE_KIND_CRASHED",
	}
	AttemptFailureKind_value = map[string]int32{
		"ATTEMPT_FAILURE_KIND_UNSPECIFIED": 0,
		"ATTEMPT_FAILURE_KIND_USER_ERROR":  1,
		"ATTEMPT_FAILURE_KIND_CRASHED":     2,
	}
)

func (x AttemptFailureKind) Enum() *AttemptFailureKind {
	p := new(AttemptFailureKind)
	*p = x
	return p
}

func (x AttemptFailureKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttemptFailureKind) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[4].Descriptor()
}

func (AttemptFailureKind) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[4]
}

func (x AttemptFailureKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttemptFailureKind.Descriptor instead.
func (AttemptFailureKind) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{4}
}

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
	LogStream_LOG_STREAM_SYSTEM      LogStream = 3
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
		3: "LOG_STREAM_SYSTEM",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
		"LOG_STREAM_SYSTEM":      3,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_host_v1_host_proto_enumTypes[5].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_host_v1_host_proto_enumTypes[5]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{5}
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Capacity      *Capacity              `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_host_v1_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostToken     string                 `protobuf:"bytes,2,opt,name=host_token,json=hostToken,proto3" json:"host_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_host_v1_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetHostToken() string {
	if x != nil {
		return x.HostToken
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis     int64                  `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_host_v1_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{2}
}

func (x *Capacity) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *Capacity) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*HostMessage_Hello
	//	*HostMessage_Container
	//	*HostMessage_Ack
	Body          isHostMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_host_v1_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{3}
}

func (x *HostMessage) GetBody() isHostMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HostMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*HostMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *HostMessage) GetContainer() *ContainerReport {
	if x != nil {
		if x, ok := x.Body.(*HostMessage_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *HostMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*HostMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isHostMessage_Body interface {
	isHostMessage_Body()
}

type HostMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HostMessage_Container struct {
	Container *ContainerReport `protobuf:"bytes,2,opt,name=container,proto3,oneof"`
}

type HostMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*HostMessage_Hello) isHostMessage_Body() {}

func (*HostMessage_Container) isHostMessage_Body() {}

func (*HostMessage_Ack) isHostMessage_Body() {}

// Hello opens a session. It lists every container the host runs so the server
// can stop containers it no longer assigns and resend missing starts.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BootId        string                 `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Capacity      *Capacity              `protobuf:"bytes,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Containers    []*ContainerReport     `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_host_v1_host_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *Hello) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Hello) GetContainers() []*ContainerReport {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type ContainerReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Phase         ContainerPhase         `protobuf:"varint,2,opt,name=phase,proto3,enum=lazycloud.host.v1.ContainerPhase" json:"phase,omitempty"`
	Exit          *ContainerExit         `protobuf:"bytes,3,opt,name=exit,proto3" json:"exit,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerReport) Reset() {
	*x = ContainerReport{}
	mi := &file_host_v1_host_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerReport) ProtoMessage() {}

func (x *ContainerReport) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerReport.ProtoReflect.Descriptor instead.
func (*ContainerReport) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerReport) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerReport) GetPhase() ContainerPhase {
	if x != nil {
		return x.Phase
	}
	return ContainerPhase_CONTAINER_PHASE_UNSPECIFIED
}

func (x *ContainerReport) GetExit() *ContainerExit {
	if x != nil {
		return x.Exit
	}
	return nil
}

func (x *ContainerReport) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type ContainerExit struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Reason   ExitReason             `protobuf:"varint,1,opt,name=reason,proto3,enum=lazycloud.host.v1.ExitReason" json:"reason,omitempty"`
	ExitCode int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// For EXIT_REASON_LOAD_ERROR: the exception the runner reported.
	Error         *RunnerError `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExit) Reset() {
	*x = ContainerExit{}
	mi := &file_host_v1_host_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExit) ProtoMessage() {}

func (x *ContainerExit) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExit.ProtoReflect.Descriptor instead.
func (*ContainerExit) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerExit) GetReason() ExitReason {
	if x != nil {
		return x.Reason
	}
	return ExitReason_EXIT_REASON_UNSPECIFIED
}

func (x *ContainerExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContainerExit) GetError() *RunnerError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RunnerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Traceback     string                 `protobuf:"bytes,3,opt,name=traceback,proto3" json:"traceback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerError) Reset() {
	*x = RunnerError{}
	mi := &file_host_v1_host_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerError) ProtoMessage() {}

func (x *RunnerError) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerError.ProtoReflect.Descriptor instead.
func (*RunnerError) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{7}
}

func (x *RunnerError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RunnerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunnerError) GetTraceback() string {
	if x != nil {
		return x.Traceback
	}
	return ""
}

// Ack confirms receipt of a command. It is not completion; completion is the
// container report that follows.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_host_v1_host_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Start
	//	*ServerMessage_Stop
	//	*ServerMessage_Cancel
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_host_v1_host_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{9}
}

func (x *ServerMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetStart() *StartContainer {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ServerMessage) GetStop() *StopContainer {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *CancelAttempt {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Start struct {
	Start *StartContainer `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type ServerMessage_Stop struct {
	Stop *StopContainer `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *CancelAttempt `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*ServerMessage_Start) isServerMessage_Body() {}

func (*ServerMessage_Stop) isServerMessage_Body() {}

func (*ServerMessage_Cancel) isServerMessage_Body() {}

type StartContainer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// An OCI image reference the host can pull.
	Image         string            `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	PythonVersion string            `protobuf:"bytes,3,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	Source        *Source           `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Resources     *Resources        `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Function      *FunctionWorkload `protobuf:"bytes,6,opt,name=function,proto3" json:"function,omitempty"`
	Environment   map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainer) Reset() {
	*x = StartContainer{}
	mi := &file_host_v1_host_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainer) ProtoMessage() {}

func (x *StartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainer.ProtoReflect.Descriptor instead.
func (*StartContainer) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{10}
}

func (x *StartContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartContainer) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *StartContainer) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StartContainer) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *StartContainer) GetFunction() *FunctionWorkload {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *StartContainer) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type Source struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Sha256 string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// A presigned GET URL for the source zip.
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=url_expires_at,json=urlExpiresAt,proto3" json:"url_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_host_v1_host_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{11}
}

func (x *Source) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetUrlExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UrlExpiresAt
	}
	return nil
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis     int64                  `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_host_v1_host_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{12}
}

func (x *Resources) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *Resources) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type FunctionWorkload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       string                 `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	Slots         int32                  `protobuf:"varint,2,opt,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionWorkload) Reset() {
	*x = FunctionWorkload{}
	mi := &file_host_v1_host_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionWorkload) ProtoMessage() {}

func (x *FunctionWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionWorkload.ProtoReflect.Descriptor instead.
func (*FunctionWorkload) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{13}
}

func (x *FunctionWorkload) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *FunctionWorkload) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

type StopContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	GraceSeconds  int32                  `protobuf:"varint,2,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainer) Reset() {
	*x = StopContainer{}
	mi := &file_host_v1_host_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainer) ProtoMessage() {}

func (x *StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainer.ProtoReflect.Descriptor instead.
func (*StopContainer) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{14}
}

func (x *StopContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopContainer) GetGraceSeconds() int32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

// CancelAttempt kills the slot running the attempt. The server has already
// recorded the outcome.
type CancelAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Reason        CancelReason           `protobuf:"varint,3,opt,name=reason,proto3,enum=lazycloud.host.v1.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAttempt) Reset() {
	*x = CancelAttempt{}
	mi := &file_host_v1_host_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAttempt) ProtoMessage() {}

func (x *CancelAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAttempt.ProtoReflect.Descriptor instead.
func (*CancelAttempt) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{15}
}

func (x *CancelAttempt) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CancelAttempt) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CancelAttempt) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

type ClaimTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MaxTasks      int32                  `protobuf:"varint,2,opt,name=max_tasks,json=maxTasks,proto3" json:"max_tasks,omitempty"`
	WaitSeconds   int32                  `protobuf:"varint,3,opt,name=wait_seconds,json=waitSeconds,proto3" json:"wait_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTasksRequest) Reset() {
	*x = ClaimTasksRequest{}
	mi := &file_host_v1_host_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTasksRequest) ProtoMessage() {}

func (x *ClaimTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTasksRequest.ProtoReflect.Descriptor instead.
func (*ClaimTasksRequest) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{16}
}

func (x *ClaimTasksRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ClaimTasksRequest) GetMaxTasks() int32 {
	if x != nil {
		return x.MaxTasks
	}
	return 0
}

func (x *ClaimTasksRequest) GetWaitSeconds() int32 {
	if x != nil {
		return x.WaitSeconds
	}
	return 0
}

type ClaimTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ClaimedTask         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTasksResponse) Reset() {
	*x = ClaimTasksResponse{}
	mi := &file_host_v1_host_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTasksResponse) ProtoMessage() {}

func (x *ClaimTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTasksResponse.ProtoReflect.Descriptor instead.
func (*ClaimTasksResponse) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimTasksResponse) GetTasks() []*ClaimedTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ClaimedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AttemptNumber int32                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	InputEncoding PayloadEncoding        `protobuf:"varint,4,opt,name=input_encoding,json=inputEncoding,proto3,enum=lazycloud.host.v1.PayloadEncoding" json:"input_encoding,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimedTask) Reset() {
	*x = ClaimedTask{}
	mi := &file_host_v1_host_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedTask) ProtoMessage() {}

func (x *ClaimedTask) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimedTask.ProtoReflect.Descriptor instead.
func (*ClaimedTask) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{18}
}

func (x *ClaimedTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ClaimedTask) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ClaimedTask) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *ClaimedTask) GetInputEncoding() PayloadEncoding {
	if x != nil {
		return x.InputEncoding
	}
	return PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED
}

func (x *ClaimedTask) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ClaimedTask) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type CompleteTaskRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AttemptId   string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*CompleteTaskRequest_Success
	//	*CompleteTaskRequest_Failure
	Outcome       isCompleteTaskRequest_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_host_v1_host_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteTaskRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CompleteTaskRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CompleteTaskRequest) GetOutcome() isCompleteTaskRequest_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *CompleteTaskRequest) GetSuccess() *TaskSuccess {
	if x != nil {
		if x, ok := x.Outcome.(*CompleteTaskRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *CompleteTaskRequest) GetFailure() *TaskFailure {
	if x != nil {
		if x, ok := x.Outcome.(*CompleteTaskRequest_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isCompleteTaskRequest_Outcome interface {
	isCompleteTaskRequest_Outcome()
}

type CompleteTaskRequest_Success struct {
	Success *TaskSuccess `protobuf:"bytes,3,opt,name=success,proto3,oneof"`
}

type CompleteTaskRequest_Failure struct {
	Failure *TaskFailure `protobuf:"bytes,4,opt,name=failure,proto3,oneof"`
}

func (*CompleteTaskRequest_Success) isCompleteTaskRequest_Outcome() {}

func (*CompleteTaskRequest_Failure) isCompleteTaskRequest_Outcome() {}

type TaskSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      PayloadEncoding        `protobuf:"varint,1,opt,name=encoding,proto3,enum=lazycloud.host.v1.PayloadEncoding" json:"encoding,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSuccess) Reset() {
	*x = TaskSuccess{}
	mi := &file_host_v1_host_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSuccess) ProtoMessage() {}

func (x *TaskSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSuccess.ProtoReflect.Descriptor instead.
func (*TaskSuccess) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{20}
}

func (x *TaskSuccess) GetEncoding() PayloadEncoding {
	if x != nil {
		return x.Encoding
	}
	return PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED
}

func (x *TaskSuccess) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskFailure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  AttemptFailureKind     `protobuf:"varint,1,opt,name=kind,proto3,enum=lazycloud.host.v1.AttemptFailureKind" json:"kind,omitempty"`
	Error *RunnerError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The cloudpickled exception, when the runner could serialize it.
	Exception     []byte `protobuf:"bytes,3,opt,name=exception,proto3" json:"exception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailure) Reset() {
	*x = TaskFailure{}
	mi := &file_host_v1_host_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailure) ProtoMessage() {}

func (x *TaskFailure) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailure.ProtoReflect.Descriptor instead.
func (*TaskFailure) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{21}
}

func (x *TaskFailure) GetKind() AttemptFailureKind {
	if x != nil {
		return x.Kind
	}
	return AttemptFailureKind_ATTEMPT_FAILURE_KIND_UNSPECIFIED
}

func (x *TaskFailure) GetError() *RunnerError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TaskFailure) GetException() []byte {
	if x != nil {
		return x.Exception
	}
	return nil
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_host_v1_host_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{22}
}

type AppendLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Lines         []*LogLine             `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLogsRequest) Reset() {
	*x = AppendLogsRequest{}
	mi := &file_host_v1_host_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogsRequest) ProtoMessage() {}

func (x *AppendLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogsRequest.ProtoReflect.Descriptor instead.
func (*AppendLogsRequest) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{23}
}

func (x *AppendLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AppendLogsRequest) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=lazycloud.host.v1.LogStream" json:"stream,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_host_v1_host_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{24}
}

func (x *LogLine) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LogLine) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *LogLine) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogLine) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type AppendLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLogsResponse) Reset() {
	*x = AppendLogsResponse{}
	mi := &file_host_v1_host_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogsResponse) ProtoMessage() {}

func (x *AppendLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_v1_host_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogsResponse.ProtoReflect.Descriptor instead.
func (*AppendLogsResponse) Descriptor() ([]byte, []int) {
	return file_host_v1_host_proto_rawDescGZIP(), []int{25}
}

var File_host_v1_host_proto protoreflect.FileDescriptor

const file_host_v1_host_proto_rawDesc = "" +
	"\n" +
	"\x12host/v1/host.proto\x12\x11lazycloud.host.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x127\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1b.lazycloud.host.v1.CapacityR\bcapacity\"H\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"host_token\x18\x02 \x01(\tR\thostToken\"L\n" +
	"\bCapacity\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x03R\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"\xb7\x01\n" +
	"\vHostMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.lazycloud.host.v1.HelloH\x00R\x05hello\x12B\n" +
	"\tcontainer\x18\x02 \x01(\v2\".lazycloud.host.v1.ContainerReportH\x00R\tcontainer\x12*\n" +
	"\x03ack\x18\x03 \x01(\v2\x16.lazycloud.host.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xc2\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x127\n" +
	"\bcapacity\x18\x02 \x01(\v2\x1b.lazycloud.host.v1.CapacityR\bcapacity\x12B\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\".lazycloud.host.v1.ContainerReportR\n" +
	"containers\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\xe0\x01\n" +
	"\x0fContainerReport\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x127\n" +
	"\x05phase\x18\x02 \x01(\x0e2!.lazycloud.host.v1.ContainerPhaseR\x05phase\x124\n" +
	"\x04exit\x18\x03 \x01(\v2 .lazycloud.host.v1.ContainerExitR\x04exit\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xb3\x01\n" +
	"\rContainerExit\x125\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1d.lazycloud.host.v1.ExitReasonR\x06reason\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x05error\x18\x04 \x01(\v2\x1e.lazycloud.host.v1.RunnerErrorR\x05error\"Y\n" +
	"\vRunnerError\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttraceback\x18\x03 \x01(\tR\ttraceback\"$\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"\xe5\x01\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x129\n" +
	"\x05start\x18\x02 \x01(\v2!.lazycloud.host.v1.StartContainerH\x00R\x05start\x126\n" +
	"\x04stop\x18\x03 \x01(\v2 .lazycloud.host.v1.StopContainerH\x00R\x04stop\x12:\n" +
	"\x06cancel\x18\x04 \x01(\v2 .lazycloud.host.v1.CancelAttemptH\x00R\x06cancelB\x06\n" +
	"\x04body\"\xb6\x03\n" +
	"\x0eStartContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12%\n" +
	"\x0epython_version\x18\x03 \x01(\tR\rpythonVersion\x121\n" +
	"\x06source\x18\x04 \x01(\v2\x19.lazycloud.host.v1.SourceR\x06source\x12:\n" +
	"\tresources\x18\x05 \x01(\v2\x1c.lazycloud.host.v1.ResourcesR\tresources\x12?\n" +
	"\bfunction\x18\x06 \x01(\v2#.lazycloud.host.v1.FunctionWorkloadR\bfunction\x12T\n" +
	"\venvironment\x18\a \x03(\v22.lazycloud.host.v1.StartContainer.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x06Source\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12@\n" +
	"\x0eurl_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\furlExpiresAt\"M\n" +
	"\tResources\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x03R\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"B\n" +
	"\x10FunctionWorkload\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\tR\ahandler\x12\x14\n" +
	"\x05slots\x18\x02 \x01(\x05R\x05slots\"W\n" +
	"\rStopContainer\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12#\n" +
	"\rgrace_seconds\x18\x02 \x01(\x05R\fgraceSeconds\"\x8a\x01\n" +
	"\rCancelAttempt\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x127\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x1f.lazycloud.host.v1.CancelReasonR\x06reason\"v\n" +
	"\x11ClaimTasksRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\tmax_tasks\x18\x02 \x01(\x05R\bmaxTasks\x12!\n" +
	"\fwait_seconds\x18\x03 \x01(\x05R\vwaitSeconds\"J\n" +
	"\x12ClaimTasksResponse\x124\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1e.lazycloud.host.v1.ClaimedTaskR\x05tasks\"\x85\x02\n" +
	"\vClaimedTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x05R\rattemptNumber\x12I\n" +
	"\x0einput_encoding\x18\x04 \x01(\x0e2\".lazycloud.host.v1.PayloadEncodingR\rinputEncoding\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xda\x01\n" +
	"\x13CompleteTaskRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12:\n" +
	"\asuccess\x18\x03 \x01(\v2\x1e.lazycloud.host.v1.TaskSuccessH\x00R\asuccess\x12:\n" +
	"\afailure\x18\x04 \x01(\v2\x1e.lazycloud.host.v1.TaskFailureH\x00R\afailureB\t\n" +
	"\aoutcome\"e\n" +
	"\vTaskSuccess\x12>\n" +
	"\bencoding\x18\x01 \x01(\x0e2\".lazycloud.host.v1.PayloadEncodingR\bencoding\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\"\x9c\x01\n" +
	"\vTaskFailure\x129\n" +
	"\x04kind\x18\x01 \x01(\x0e2%.lazycloud.host.v1.AttemptFailureKindR\x04kind\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.lazycloud.host.v1.RunnerErrorR\x05error\x12\x1c\n" +
	"\texception\x18\x03 \x01(\fR\texception\"\x16\n" +
	"\x14CompleteTaskResponse\"h\n" +
	"\x11AppendLogsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x120\n" +
	"\x05lines\x18\x02 \x03(\v2\x1a.lazycloud.host.v1.LogLineR\x05lines\"\xa2\x01\n" +
	"\aLogLine\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x124\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x1c.lazycloud.host.v1.LogStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x14\n" +
	"\x12AppendLogsResponse*\xa5\x01\n" +
	"\x0eContainerPhase\x12\x1f\n" +
	"\x1bCONTAINER_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONTAINER_PHASE_PREPARING\x10\x01\x12\x1c\n" +
	"\x18CONTAINER_PHASE_STARTING\x10\x02\x12\x19\n" +
	"\x15CONTAINER_PHASE_READY\x10\x03\x12\x1a\n" +
	"\x16CONTAINER_PHASE_EXITED\x10\x04*\xb4\x01\n" +
	"\n" +
	"ExitReason\x12\x1b\n" +
	"\x17EXIT_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXIT_REASON_STOPPED\x10\x01\x12\x1a\n" +
	"\x16EXIT_REASON_LOAD_ERROR\x10\x02\x12\x1c\n" +
	"\x18EXIT_REASON_START_FAILED\x10\x03\x12\x17\n" +
	"\x13EXIT_REASON_CRASHED\x10\x04\x12\x1d\n" +
	"\x19EXIT_REASON_OUT_OF_MEMORY\x10\x05*g\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CANCEL_REASON_CANCELLED\x10\x01\x12\x1b\n" +
	"\x17CANCEL_REASON_TIMED_OUT\x10\x02*p\n" +
	"\x0fPayloadEncoding\x12 \n" +
	"\x1cPAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYLOAD_ENCODING_JSON\x10\x01\x12 \n" +
	"\x1cPAYLOAD_ENCODING_CLOUDPICKLE\x10\x02*\x81\x01\n" +
	"\x12AttemptFailureKind\x12$\n" +
	" ATTEMPT_FAILURE_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fATTEMPT_FAILURE_KIND_USER_ERROR\x10\x01\x12 \n" +
	"\x1cATTEMPT_FAILURE_KIND_CRASHED\x10\x02*l\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02\x12\x15\n" +
	"\x11LOG_STREAM_SYSTEM\x10\x032\xc4\x03\n" +
	"\vHostService\x12M\n" +
	"\x06Enroll\x12 .lazycloud.host.v1.EnrollRequest\x1a!.lazycloud.host.v1.EnrollResponse\x12O\n" +
	"\aSession\x12\x1e.lazycloud.host.v1.HostMessage\x1a .lazycloud.host.v1.ServerMessage(\x010\x01\x12Y\n" +
	"\n" +
	"ClaimTasks\x12$.lazycloud.host.v1.ClaimTasksRequest\x1a%.lazycloud.host.v1.ClaimTasksResponse\x12_\n" +
	"\fCompleteTask\x12&.lazycloud.host.v1.CompleteTaskRequest\x1a'.lazycloud.host.v1.CompleteTaskResponse\x12Y\n" +
	"\n" +
	"AppendLogs\x12$.lazycloud.host.v1.AppendLogsRequest\x1a%.lazycloud.host.v1.AppendLogsResponseB5Z3github.com/AmbientWare/lazycloud/internal/hostprotob\x06proto3"

var (
	file_host_v1_host_proto_rawDescOnce sync.Once
	file_host_v1_host_proto_rawDescData []byte
)

func file_host_v1_host_proto_rawDescGZIP() []byte {
	file_host_v1_host_proto_rawDescOnce.Do(func() {
		file_host_v1_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_v1_host_proto_rawDesc), len(file_host_v1_host_proto_rawDesc)))
	})
	return file_host_v1_host_proto_rawDescData
}

var file_host_v1_host_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_host_v1_host_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_host_v1_host_proto_goTypes = []any{
	(ContainerPhase)(0),           // 0: lazycloud.host.v1.ContainerPhase
	(ExitReason)(0),               // 1: lazycloud.host.v1.ExitReason
	(CancelReason)(0),             // 2: lazycloud.host.v1.CancelReason
	(PayloadEncoding)(0),          // 3: lazycloud.host.v1.PayloadEncoding
	(AttemptFailureKind)(0),       // 4: lazycloud.host.v1.AttemptFailureKind
	(LogStream)(0),                // 5: lazycloud.host.v1.LogStream
	(*EnrollRequest)(nil),         // 6: lazycloud.host.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 7: lazycloud.host.v1.EnrollResponse
	(*Capacity)(nil),              // 8: lazycloud.host.v1.Capacity
	(*HostMessage)(nil),           // 9: lazycloud.host.v1.HostMessage
	(*Hello)(nil),                 // 10: lazycloud.host.v1.Hello
	(*ContainerReport)(nil),       // 11: lazycloud.host.v1.ContainerReport
	(*ContainerExit)(nil),         // 12: lazycloud.host.v1.ContainerExit
	(*RunnerError)(nil),           // 13: lazycloud.host.v1.RunnerError
	(*Ack)(nil),                   // 14: lazycloud.host.v1.Ack
	(*ServerMessage)(nil),         // 15: lazycloud.host.v1.ServerMessage
	(*StartContainer)(nil),        // 16: lazycloud.host.v1.StartContainer
	(*Source)(nil),                // 17: lazycloud.host.v1.Source
	(*Resources)(nil),             // 18: lazycloud.host.v1.Resources
	(*FunctionWorkload)(nil),      // 19: lazycloud.host.v1.FunctionWorkload
	(*StopContainer)(nil),         // 20: lazycloud.host.v1.StopContainer
	(*CancelAttempt)(nil),         // 21: lazycloud.host.v1.CancelAttempt
	(*ClaimTasksRequest)(nil),     // 22: lazycloud.host.v1.ClaimTasksRequest
	(*ClaimTasksResponse)(nil),    // 23: lazycloud.host.v1.ClaimTasksResponse
	(*ClaimedTask)(nil),           // 24: lazycloud.host.v1.ClaimedTask
	(*CompleteTaskRequest)(nil),   // 25: lazycloud.host.v1.CompleteTaskRequest
	(*TaskSuccess)(nil),           // 26: lazycloud.host.v1.TaskSuccess
	(*TaskFailure)(nil),           // 27: lazycloud.host.v1.TaskFailure
	(*CompleteTaskResponse)(nil),  // 28: lazycloud.host.v1.CompleteTaskResponse
	(*AppendLogsRequest)(nil),     // 29: lazycloud.host.v1.AppendLogsRequest
	(*LogLine)(nil),               // 30: lazycloud.host.v1.LogLine
	(*AppendLogsResponse)(nil),    // 31: lazycloud.host.v1.AppendLogsResponse
	nil,                           // 32: lazycloud.host.v1.StartContainer.EnvironmentEntry
	(*timestamppb.Timestamp)(nil), // 33: google.protobuf.Timestamp
}
var file_host_v1_host_proto_depIdxs = []int32{
	8,  // 0: lazycloud.host.v1.EnrollRequest.capacity:type_name -> lazycloud.host.v1.Capacity
	10, // 1: lazycloud.host.v1.HostMessage.hello:type_name -> lazycloud.host.v1.Hello
	11, // 2: lazycloud.host.v1.HostMessage.container:type_name -> lazycloud.host.v1.ContainerReport
	14, // 3: lazycloud.host.v1.HostMessage.ack:type_name -> lazycloud.host.v1.Ack
	8,  // 4: lazycloud.host.v1.Hello.capacity:type_name -> lazycloud.host.v1.Capacity
	11, // 5: lazycloud.host.v1.Hello.containers:type_name -> lazycloud.host.v1.ContainerReport
	0,  // 6: lazycloud.host.v1.ContainerReport.phase:type_name -> lazycloud.host.v1.ContainerPhase
	12, // 7: lazycloud.host.v1.ContainerReport.exit:type_name -> lazycloud.host.v1.ContainerExit
	33, // 8: lazycloud.host.v1.ContainerReport.observed_at:type_name -> google.protobuf.Timestamp
	1,  // 9: lazycloud.host.v1.ContainerExit.reason:type_name -> lazycloud.host.v1.ExitReason
	13, // 10: lazycloud.host.v1.ContainerExit.error:type_name -> lazycloud.host.v1.RunnerError
	16, // 11: lazycloud.host.v1.ServerMessage.start:type_name -> lazycloud.host.v1.StartContainer
	20, // 12: lazycloud.host.v1.ServerMessage.stop:type_name -> lazycloud.host.v1.StopContainer
	21, // 13: lazycloud.host.v1.ServerMessage.cancel:type_name -> lazycloud.host.v1.CancelAttempt
	17, // 14: lazycloud.host.v1.StartContainer.source:type_name -> lazycloud.host.v1.Source
	18, // 15: lazycloud.host.v1.StartContainer.resources:type_name -> lazycloud.host.v1.Resources
	19, // 16: lazycloud.host.v1.StartContainer.function:type_name -> lazycloud.host.v1.FunctionWorkload
	32, // 17: lazycloud.host.v1.StartContainer.environment:type_name -> lazycloud.host.v1.StartContainer.EnvironmentEntry
	33, // 18: lazycloud.host.v1.Source.url_expires_at:type_name -> google.protobuf.Timestamp
	2,  // 19: lazycloud.host.v1.CancelAttempt.reason:type_name -> lazycloud.host.v1.CancelReason
	24, // 20: lazycloud.host.v1.ClaimTasksResponse.tasks:type_name -> lazycloud.host.v1.ClaimedTask
	3,  // 21: lazycloud.host.v1.ClaimedTask.input_encoding:type_name -> lazycloud.host.v1.PayloadEncoding
	33, // 22: lazycloud.host.v1.ClaimedTask.deadline:type_name -> google.protobuf.Timestamp
	26, // 23: lazycloud.host.v1.CompleteTaskRequest.success:type_name -> lazycloud.host.v1.TaskSuccess
	27, // 24: lazycloud.host.v1.CompleteTaskRequest.failure:type_name -> lazycloud.host.v1.TaskFailure
	3,  // 25: lazycloud.host.v1.TaskSuccess.encoding:type_name -> lazycloud.host.v1.PayloadEncoding
	4,  // 26: lazycloud.host.v1.TaskFailure.kind:type_name -> lazycloud.host.v1.AttemptFailureKind
	13, // 27: lazycloud.host.v1.TaskFailure.error:type_name -> lazycloud.host.v1.RunnerError
	30, // 28: lazycloud.host.v1.AppendLogsRequest.lines:type_name -> lazycloud.host.v1.LogLine
	5,  // 29: lazycloud.host.v1.LogLine.stream:type_name -> lazycloud.host.v1.LogStream
	33, // 30: lazycloud.host.v1.LogLine.time:type_name -> google.protobuf.Timestamp
	6,  // 31: lazycloud.host.v1.HostService.Enroll:input_type -> lazycloud.host.v1.EnrollRequest
	9,  // 32: lazycloud.host.v1.HostService.Session:input_type -> lazycloud.host.v1.HostMessage
	22, // 33: lazycloud.host.v1.HostService.ClaimTasks:input_type -> lazycloud.host.v1.ClaimTasksRequest
	25, // 34: lazycloud.host.v1.HostService.CompleteTask:input_type -> lazycloud.host.v1.CompleteTaskRequest
	29, // 35: lazycloud.host.v1.HostService.AppendLogs:input_type -> lazycloud.host.v1.AppendLogsRequest
	7,  // 36: lazycloud.host.v1.HostService.Enroll:output_type -> lazycloud.host.v1.EnrollResponse
	15, // 37: lazycloud.host.v1.HostService.Session:output_type -> lazycloud.host.v1.ServerMessage
	23, // 38: lazycloud.host.v1.HostService.ClaimTasks:output_type -> lazycloud.host.v1.ClaimTasksResponse
	28, // 39: lazycloud.host.v1.HostService.CompleteTask:output_type -> lazycloud.host.v1.CompleteTaskResponse
	31, // 40: lazycloud.host.v1.HostService.AppendLogs:output_type -> lazycloud.host.v1.AppendLogsResponse
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_host_v1_host_proto_init() }
func file_host_v1_host_proto_init() {
	if File_host_v1_host_proto != nil {
		return
	}
	file_host_v1_host_proto_msgTypes[3].OneofWrappers = []any{
		(*HostMessage_Hello)(nil),
		(*HostMessage_Container)(nil),
		(*HostMessage_Ack)(nil),
	}
	file_host_v1_host_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerMessage_Start)(nil),
		(*ServerMessage_Stop)(nil),
		(*ServerMessage_Cancel)(nil),
	}
	file_host_v1_host_proto_msgTypes[19].OneofWrappers = []any{
		(*CompleteTaskRequest_Success)(nil),
		(*CompleteTaskRequest_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_v1_host_proto_rawDesc), len(file_host_v1_host_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_v1_host_proto_goTypes,
		DependencyIndexes: file_host_v1_host_proto_depIdxs,
		EnumInfos:         file_host_v1_host_proto_enumTypes,
		MessageInfos:      file_host_v1_host_proto_msgTypes,
	}.Build()
	File_host_v1_host_proto = out.File
	file_host_v1_host_proto_goTypes = nil
	file_host_v1_host_proto_depIdxs = nil
}
