[project]
name = "lazycloud"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
lazycloud = "cli.commands:main_cli"
update-billing = "backend.billing.update_billing:main"
cli-console = "scripts.dev_tools:textual_console"
cli-dashboard = "scripts.dev_tools:cli_dashboard"
mk-help = "scripts.minikube_dev:help"
mk-up = "scripts.minikube_dev:main"
mk-down = "scripts.minikube_dev:main_down"
mk-dash = "scripts.minikube_dev:main_dashboard"
mk-status = "scripts.minikube_dev:main_status"

[tool.uv.workspace]
members = [
    "apps/backend",
    "apps/cli",
    "packages/models",
    "packages/api_requests",
    "packages/responses",
]

[tool.hatch.build.targets.wheel]
packages = ["scripts", "minikube"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
