// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package control

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensureWorkload = `-- name: EnsureWorkload :one
insert into workloads (app_id, kind, name, desired_state)
values ($1, 'function', $2, 'active')
on conflict (app_id, kind, name) where desired_state <> 'deleted' do update set name = excluded.name
returning id, active_release_id, desired_state
`

type EnsureWorkloadParams struct {
	AppID uuid.UUID
	Name  string
}

type EnsureWorkloadRow struct {
	ID              uuid.UUID
	ActiveReleaseID *uuid.UUID
	DesiredState    string
}

// The live workload, created without a release when missing. Unlike a
// deploy it never reactivates a stopped workload. The no-op update locks the
// row, so concurrent prepares of one definition insert one release.
func (q *Queries) EnsureWorkload(ctx context.Context, arg EnsureWorkloadParams) (EnsureWorkloadRow, error) {
	row := q.db.QueryRow(ctx, ensureWorkload, arg.AppID, arg.Name)
	var i EnsureWorkloadRow
	err := row.Scan(&i.ID, &i.ActiveReleaseID, &i.DesiredState)
	return i, err
}

const releaseByDigest = `-- name: ReleaseByDigest :one
select r.id, r.version, r.created_at
from releases r
where r.workload_id = $1 and r.spec_digest = $2
  and (not $3::bool or r.version is null)
order by (r.id = $4::uuid) desc nulls last, r.id desc
limit 1
`

type ReleaseByDigestParams struct {
	WorkloadID      uuid.UUID
	SpecDigest      []byte
	UnversionedOnly bool
	ActiveReleaseID *uuid.UUID
}

type ReleaseByDigestRow struct {
	ID        uuid.UUID
	Version   *int32
	CreatedAt time.Time
}

// The active release when it matches, else the newest matching one. With
// unversioned_only it matches working-tree releases alone.
func (q *Queries) ReleaseByDigest(ctx context.Context, arg ReleaseByDigestParams) (ReleaseByDigestRow, error) {
	row := q.db.QueryRow(ctx, releaseByDigest,
		arg.WorkloadID,
		arg.SpecDigest,
		arg.UnversionedOnly,
		arg.ActiveReleaseID,
	)
	var i ReleaseByDigestRow
	err := row.Scan(&i.ID, &i.Version, &i.CreatedAt)
	return i, err
}
