{{- if gt (int .Values.backgroundWorkers.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-background-workers
  labels:
    app: {{ .Chart.Name }}-background-workers
    component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-background-workers
{{- end }}
