{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
    component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
{{- end }}
