# Default values for LazyCloud Web

replicaCount: 1

image:
  repository: 534742592531.dkr.ecr.us-east-1.amazonaws.com/web
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hostname: lazycloud.dev
  healthCheckPath: /api/health
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:211125306000:certificate/YOUR-WILDCARD-CERT-ARN"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi


# Environment variables pulled from External Secrets
secrets:
  name: "app-secrets"
  env:
    - "NODE_ENV"
    - "DATABASE_URL"
    - "CLERK_SECRET_KEY"
    - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
    - "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL"
    - "NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL"
