apiVersion: v2
name: external-dns
description: ExternalDNS wrapper chart for Cloudflare
type: application
version: 1.0.0
appVersion: "0.14.0"

dependencies:
  - name: external-dns
    version: "1.14.3"
    repository: https://kubernetes-sigs.github.io/external-dns/
