external-dns:
  provider:
    name: cloudflare

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: apiToken

  sources:
    - ingress

  policy: sync

  txtOwnerId: lazycloud

  domainFilters:
    - lazycloud.dev

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
