// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AppState.
const (
	AppStateActive  AppState = "active"
	AppStateDeleted AppState = "deleted"
	AppStatePaused  AppState = "paused"
)

// Valid indicates whether the value is a known member of the AppState enum.
func (e AppState) Valid() bool {
	switch e {
	case AppStateActive:
		return true
	case AppStateDeleted:
		return true
	case AppStatePaused:
		return true
	default:
		return false
	}
}

// Defines values for ContainerState.
const (
	ContainerStateDraining ContainerState = "draining"
	ContainerStatePending  ContainerState = "pending"
	ContainerStateReady    ContainerState = "ready"
	ContainerStateStarting ContainerState = "starting"
	ContainerStateStopped  ContainerState = "stopped"
)

// Valid indicates whether the value is a known member of the ContainerState enum.
func (e ContainerState) Valid() bool {
	switch e {
	case ContainerStateDraining:
		return true
	case ContainerStatePending:
		return true
	case ContainerStateReady:
		return true
	case ContainerStateStarting:
		return true
	case ContainerStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for DeliveryState.
const (
	DeliveryStateBounced    DeliveryState = "bounced"
	DeliveryStateComplained DeliveryState = "complained"
	DeliveryStateDelivered  DeliveryState = "delivered"
	DeliveryStateDiscarded  DeliveryState = "discarded"
	DeliveryStateFailed     DeliveryState = "failed"
	DeliveryStateQueued     DeliveryState = "queued"
	DeliveryStateSent       DeliveryState = "sent"
)

// Valid indicates whether the value is a known member of the DeliveryState enum.
func (e DeliveryState) Valid() bool {
	switch e {
	case DeliveryStateBounced:
		return true
	case DeliveryStateComplained:
		return true
	case DeliveryStateDelivered:
		return true
	case DeliveryStateDiscarded:
		return true
	case DeliveryStateFailed:
		return true
	case DeliveryStateQueued:
		return true
	case DeliveryStateSent:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentPlanAction.
const (
	Add      DeploymentPlanAction = "add"
	Redeploy DeploymentPlanAction = "redeploy"
	Remove   DeploymentPlanAction = "remove"
	Retain   DeploymentPlanAction = "retain"
)

// Valid indicates whether the value is a known member of the DeploymentPlanAction enum.
func (e DeploymentPlanAction) Valid() bool {
	switch e {
	case Add:
		return true
	case Redeploy:
		return true
	case Remove:
		return true
	case Retain:
		return true
	default:
		return false
	}
}

// Defines values for DeviceCodeStatus.
const (
	DeviceCodeStatusApproved DeviceCodeStatus = "approved"
	DeviceCodeStatusDenied   DeviceCodeStatus = "denied"
	DeviceCodeStatusExpired  DeviceCodeStatus = "expired"
	DeviceCodeStatusPending  DeviceCodeStatus = "pending"
)

// Valid indicates whether the value is a known member of the DeviceCodeStatus enum.
func (e DeviceCodeStatus) Valid() bool {
	switch e {
	case DeviceCodeStatusApproved:
		return true
	case DeviceCodeStatusDenied:
		return true
	case DeviceCodeStatusExpired:
		return true
	case DeviceCodeStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenStatus.
const (
	DeviceTokenStatusApproved DeviceTokenStatus = "approved"
	DeviceTokenStatusDenied   DeviceTokenStatus = "denied"
	DeviceTokenStatusExpired  DeviceTokenStatus = "expired"
	DeviceTokenStatusPending  DeviceTokenStatus = "pending"
	DeviceTokenStatusSlowDown DeviceTokenStatus = "slow_down"
)

// Valid indicates whether the value is a known member of the DeviceTokenStatus enum.
func (e DeviceTokenStatus) Valid() bool {
	switch e {
	case DeviceTokenStatusApproved:
		return true
	case DeviceTokenStatusDenied:
		return true
	case DeviceTokenStatusExpired:
		return true
	case DeviceTokenStatusPending:
		return true
	case DeviceTokenStatusSlowDown:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	Conflict            ErrorCode = "conflict"
	Forbidden           ErrorCode = "forbidden"
	Internal            ErrorCode = "internal"
	InvalidRequest      ErrorCode = "invalid_request"
	NotFound            ErrorCode = "not_found"
	PayloadTooLarge     ErrorCode = "payload_too_large"
	TaskNotFinished     ErrorCode = "task_not_finished"
	TooManyPendingTasks ErrorCode = "too_many_pending_tasks"
	Unauthenticated     ErrorCode = "unauthenticated"
	Unavailable         ErrorCode = "unavailable"
	Unsupported         ErrorCode = "unsupported"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case Conflict:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case InvalidRequest:
		return true
	case NotFound:
		return true
	case PayloadTooLarge:
		return true
	case TaskNotFinished:
		return true
	case TooManyPendingTasks:
		return true
	case Unauthenticated:
		return true
	case Unavailable:
		return true
	case Unsupported:
		return true
	default:
		return false
	}
}

// Defines values for FailureKind.
const (
	FailureKindDependencyFailed FailureKind = "dependency_failed"
	FailureKindLoadError        FailureKind = "load_error"
	FailureKindLost             FailureKind = "lost"
	FailureKindStartFailed      FailureKind = "start_failed"
	FailureKindSystem           FailureKind = "system"
	FailureKindTimeout          FailureKind = "timeout"
	FailureKindUserError        FailureKind = "user_error"
)

// Valid indicates whether the value is a known member of the FailureKind enum.
func (e FailureKind) Valid() bool {
	switch e {
	case FailureKindDependencyFailed:
		return true
	case FailureKindLoadError:
		return true
	case FailureKindLost:
		return true
	case FailureKindStartFailed:
		return true
	case FailureKindSystem:
		return true
	case FailureKindTimeout:
		return true
	case FailureKindUserError:
		return true
	default:
		return false
	}
}

// Defines values for FunctionState.
const (
	FunctionStateActive  FunctionState = "active"
	FunctionStateStopped FunctionState = "stopped"
)

// Valid indicates whether the value is a known member of the FunctionState enum.
func (e FunctionState) Valid() bool {
	switch e {
	case FunctionStateActive:
		return true
	case FunctionStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for ImageArchitecture.
const (
	ImageArchitectureAmd64 ImageArchitecture = "amd64"
	ImageArchitectureArm64 ImageArchitecture = "arm64"
)

// Valid indicates whether the value is a known member of the ImageArchitecture enum.
func (e ImageArchitecture) Valid() bool {
	switch e {
	case ImageArchitectureAmd64:
		return true
	case ImageArchitectureArm64:
		return true
	default:
		return false
	}
}

// Defines values for ImageBuildPhase.
const (
	ImageBuildPhaseBuilding ImageBuildPhase = "building"
	ImageBuildPhaseFinished ImageBuildPhase = "finished"
	ImageBuildPhaseQueued   ImageBuildPhase = "queued"
	ImageBuildPhaseStarting ImageBuildPhase = "starting"
)

// Valid indicates whether the value is a known member of the ImageBuildPhase enum.
func (e ImageBuildPhase) Valid() bool {
	switch e {
	case ImageBuildPhaseBuilding:
		return true
	case ImageBuildPhaseFinished:
		return true
	case ImageBuildPhaseQueued:
		return true
	case ImageBuildPhaseStarting:
		return true
	default:
		return false
	}
}

// Defines values for ImageBuildStatus.
const (
	ImageBuildStatusBuilding  ImageBuildStatus = "building"
	ImageBuildStatusFailed    ImageBuildStatus = "failed"
	ImageBuildStatusSucceeded ImageBuildStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ImageBuildStatus enum.
func (e ImageBuildStatus) Valid() bool {
	switch e {
	case ImageBuildStatusBuilding:
		return true
	case ImageBuildStatusFailed:
		return true
	case ImageBuildStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ImageDefinitionArchitecture.
const (
	ImageDefinitionArchitectureAmd64 ImageDefinitionArchitecture = "amd64"
	ImageDefinitionArchitectureArm64 ImageDefinitionArchitecture = "arm64"
)

// Valid indicates whether the value is a known member of the ImageDefinitionArchitecture enum.
func (e ImageDefinitionArchitecture) Valid() bool {
	switch e {
	case ImageDefinitionArchitectureAmd64:
		return true
	case ImageDefinitionArchitectureArm64:
		return true
	default:
		return false
	}
}

// Defines values for ImageSpecPythonVersion.
const (
	N310 ImageSpecPythonVersion = "3.10"
	N311 ImageSpecPythonVersion = "3.11"
	N312 ImageSpecPythonVersion = "3.12"
	N313 ImageSpecPythonVersion = "3.13"
	N314 ImageSpecPythonVersion = "3.14"
)

// Valid indicates whether the value is a known member of the ImageSpecPythonVersion enum.
func (e ImageSpecPythonVersion) Valid() bool {
	switch e {
	case N310:
		return true
	case N311:
		return true
	case N312:
		return true
	case N313:
		return true
	case N314:
		return true
	default:
		return false
	}
}

// Defines values for ImageStepKind.
const (
	Micromamba            ImageStepKind = "micromamba"
	MicromambaEnvironment ImageStepKind = "micromamba_environment"
	Pip                   ImageStepKind = "pip"
	PoetryProject         ImageStepKind = "poetry_project"
	Pyproject             ImageStepKind = "pyproject"
	Shell                 ImageStepKind = "shell"
	UvProject             ImageStepKind = "uv_project"
)

// Valid indicates whether the value is a known member of the ImageStepKind enum.
func (e ImageStepKind) Valid() bool {
	switch e {
	case Micromamba:
		return true
	case MicromambaEnvironment:
		return true
	case Pip:
		return true
	case PoetryProject:
		return true
	case Pyproject:
		return true
	case Shell:
		return true
	case UvProject:
		return true
	default:
		return false
	}
}

// Defines values for InvitationRole.
const (
	InvitationRoleAdministrator InvitationRole = "administrator"
	InvitationRoleMember        InvitationRole = "member"
)

// Valid indicates whether the value is a known member of the InvitationRole enum.
func (e InvitationRole) Valid() bool {
	switch e {
	case InvitationRoleAdministrator:
		return true
	case InvitationRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for LiveAppState.
const (
	LiveAppStateActive LiveAppState = "active"
	LiveAppStatePaused LiveAppState = "paused"
)

// Valid indicates whether the value is a known member of the LiveAppState enum.
func (e LiveAppState) Valid() bool {
	switch e {
	case LiveAppStateActive:
		return true
	case LiveAppStatePaused:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryStream.
const (
	LogEntryStreamStderr LogEntryStream = "stderr"
	LogEntryStreamStdout LogEntryStream = "stdout"
	LogEntryStreamSystem LogEntryStream = "system"
)

// Valid indicates whether the value is a known member of the LogEntryStream enum.
func (e LogEntryStream) Valid() bool {
	switch e {
	case LogEntryStreamStderr:
		return true
	case LogEntryStreamStdout:
		return true
	case LogEntryStreamSystem:
		return true
	default:
		return false
	}
}

// Defines values for PayloadEncoding.
const (
	PayloadEncodingCloudpickle PayloadEncoding = "cloudpickle"
	PayloadEncodingJson        PayloadEncoding = "json"
)

// Valid indicates whether the value is a known member of the PayloadEncoding enum.
func (e PayloadEncoding) Valid() bool {
	switch e {
	case PayloadEncodingCloudpickle:
		return true
	case PayloadEncodingJson:
		return true
	default:
		return false
	}
}

// Defines values for RetryPolicyBackoff.
const (
	Exponential RetryPolicyBackoff = "exponential"
	Fixed       RetryPolicyBackoff = "fixed"
)

// Valid indicates whether the value is a known member of the RetryPolicyBackoff enum.
func (e RetryPolicyBackoff) Valid() bool {
	switch e {
	case Exponential:
		return true
	case Fixed:
		return true
	default:
		return false
	}
}

// Defines values for StopReason.
const (
	StopReasonCrashed     StopReason = "crashed"
	StopReasonHostLost    StopReason = "host_lost"
	StopReasonLoadError   StopReason = "load_error"
	StopReasonOutOfMemory StopReason = "out_of_memory"
	StopReasonStartFailed StopReason = "start_failed"
	StopReasonStopped     StopReason = "stopped"
)

// Valid indicates whether the value is a known member of the StopReason enum.
func (e StopReason) Valid() bool {
	switch e {
	case StopReasonCrashed:
		return true
	case StopReasonHostLost:
		return true
	case StopReasonLoadError:
		return true
	case StopReasonOutOfMemory:
		return true
	case StopReasonStartFailed:
		return true
	case StopReasonStopped:
		return true
	default:
		return false
	}
}

// Defines values for TaskInputEncoding.
const (
	TaskInputEncodingCloudpickle TaskInputEncoding = "cloudpickle"
	TaskInputEncodingJson        TaskInputEncoding = "json"
)

// Valid indicates whether the value is a known member of the TaskInputEncoding enum.
func (e TaskInputEncoding) Valid() bool {
	switch e {
	case TaskInputEncodingCloudpickle:
		return true
	case TaskInputEncodingJson:
		return true
	default:
		return false
	}
}

// Defines values for TaskPendingReason.
const (
	TaskPendingReasonCapacityBusy        TaskPendingReason = "capacity_busy"
	TaskPendingReasonCapacityLimit       TaskPendingReason = "capacity_limit"
	TaskPendingReasonCapacityUnavailable TaskPendingReason = "capacity_unavailable"
	TaskPendingReasonDependencies        TaskPendingReason = "dependencies"
	TaskPendingReasonProvisioningCompute TaskPendingReason = "provisioning_compute"
	TaskPendingReasonQueued              TaskPendingReason = "queued"
	TaskPendingReasonRetry               TaskPendingReason = "retry"
	TaskPendingReasonStartingContainer   TaskPendingReason = "starting_container"
)

// Valid indicates whether the value is a known member of the TaskPendingReason enum.
func (e TaskPendingReason) Valid() bool {
	switch e {
	case TaskPendingReasonCapacityBusy:
		return true
	case TaskPendingReasonCapacityLimit:
		return true
	case TaskPendingReasonCapacityUnavailable:
		return true
	case TaskPendingReasonDependencies:
		return true
	case TaskPendingReasonProvisioningCompute:
		return true
	case TaskPendingReasonQueued:
		return true
	case TaskPendingReasonRetry:
		return true
	case TaskPendingReasonStartingContainer:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCancelled TaskStatus = "cancelled"
	TaskStatusFailed    TaskStatus = "failed"
	TaskStatusQueued    TaskStatus = "queued"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusSucceeded TaskStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCancelled:
		return true
	case TaskStatusFailed:
		return true
	case TaskStatusQueued:
		return true
	case TaskStatusRunning:
		return true
	case TaskStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for TokenStatus.
const (
	TokenStatusActive  TokenStatus = "active"
	TokenStatusExpired TokenStatus = "expired"
)

// Valid indicates whether the value is a known member of the TokenStatus enum.
func (e TokenStatus) Valid() bool {
	switch e {
	case TokenStatusActive:
		return true
	case TokenStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for UploadTargetMethod.
const (
	PUT UploadTargetMethod = "PUT"
)

// Valid indicates whether the value is a known member of the UploadTargetMethod enum.
func (e UploadTargetMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadKind.
const (
	WorkloadKindFunction WorkloadKind = "function"
)

// Valid indicates whether the value is a known member of the WorkloadKind enum.
func (e WorkloadKind) Valid() bool {
	switch e {
	case WorkloadKindFunction:
		return true
	default:
		return false
	}
}

// Defines values for WorkloadState.
const (
	WorkloadStateActive  WorkloadState = "active"
	WorkloadStateDeleted WorkloadState = "deleted"
	WorkloadStateStopped WorkloadState = "stopped"
)

// Valid indicates whether the value is a known member of the WorkloadState enum.
func (e WorkloadState) Valid() bool {
	switch e {
	case WorkloadStateActive:
		return true
	case WorkloadStateDeleted:
		return true
	case WorkloadStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceRole.
const (
	WorkspaceRoleAdministrator WorkspaceRole = "administrator"
	WorkspaceRoleMember        WorkspaceRole = "member"
	WorkspaceRoleOwner         WorkspaceRole = "owner"
)

// Valid indicates whether the value is a known member of the WorkspaceRole enum.
func (e WorkspaceRole) Valid() bool {
	switch e {
	case WorkspaceRoleAdministrator:
		return true
	case WorkspaceRoleMember:
		return true
	case WorkspaceRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceState.
const (
	WorkspaceStateActive   WorkspaceState = "active"
	WorkspaceStateDeleting WorkspaceState = "deleting"
)

// Valid indicates whether the value is a known member of the WorkspaceState enum.
func (e WorkspaceState) Valid() bool {
	switch e {
	case WorkspaceStateActive:
		return true
	case WorkspaceStateDeleting:
		return true
	default:
		return false
	}
}

// AcceptedInvitation defines model for AcceptedInvitation.
type AcceptedInvitation struct {
	Member    Member    `json:"member"`
	Workspace Workspace `json:"workspace"`
}

// App defines model for App.
type App struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      AppName            `json:"name"`
	State     AppState           `json:"state"`

	// Workloads Deployed workloads that are not deleted.
	Workloads int `json:"workloads"`
}

// AppName defines model for AppName.
type AppName = string

// AppPage defines model for AppPage.
type AppPage struct {
	Apps []App `json:"apps"`

	// NextCursor Present when another page follows.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// AppRef An app name or id.
type AppRef = string

// AppState defines model for AppState.
type AppState string

// Autoscaler defines model for Autoscaler.
type Autoscaler struct {
	MaxContainers     *int `json:"max_containers,omitempty"`
	MinContainers     *int `json:"min_containers,omitempty"`
	TasksPerContainer *int `json:"tasks_per_container,omitempty"`
}

// Container defines model for Container.
type Container struct {
	App         AppName            `json:"app"`
	CpuMillis   int64              `json:"cpu_millis"`
	CreatedAt   time.Time          `json:"created_at"`
	ExitMessage *string            `json:"exit_message,omitempty"`
	Function    WorkloadName       `json:"function"`
	Id          openapi_types.UUID `json:"id"`
	MemoryMib   int64              `json:"memory_mib"`
	ReadyAt     *time.Time         `json:"ready_at,omitempty"`
	ReleaseId   openapi_types.UUID `json:"release_id"`

	// RunningTasks Attempts running now.
	RunningTasks int            `json:"running_tasks"`
	Slots        int            `json:"slots"`
	State        ContainerState `json:"state"`
	StopReason   *StopReason    `json:"stop_reason,omitempty"`
	StoppedAt    *time.Time     `json:"stopped_at,omitempty"`

	// Version The deployed version of the release; absent for a working-tree release.
	Version *int `json:"version,omitempty"`
}

// ContainerPage defines model for ContainerPage.
type ContainerPage struct {
	Containers []Container `json:"containers"`
	NextCursor *string     `json:"next_cursor,omitempty"`
}

// ContainerState defines model for ContainerState.
type ContainerState string

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	Record Token `json:"record"`

	// Token The secret; it is not shown again.
	Token string `json:"token"`
}

// DeliveryState What became of an email: `queued` until the provider accepts it, then `sent`, and `delivered`, `bounced` or `complained` as the provider reports; `failed` when delivery gave up; `discarded` when it was withdrawn before sending.
type DeliveryState string

// DeployedWorkload defines model for DeployedWorkload.
type DeployedWorkload struct {
	App       AppName   `json:"app"`
	AppState  *AppState `json:"app_state,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// DeployedAt When the active version was deployed.
	DeployedAt *time.Time         `json:"deployed_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	Kind       WorkloadKind       `json:"kind"`
	Name       WorkloadName       `json:"name"`

	// ReleaseId The active release.
	ReleaseId *openapi_types.UUID `json:"release_id,omitempty"`

	// State Desired state. A paused app stops its active workloads too.
	State WorkloadState `json:"state"`

	// Version The active version.
	Version *int `json:"version,omitempty"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	App App `json:"app"`

	// Pruned Functions the prune deleted.
	Pruned   []WorkloadName `json:"pruned"`
	Releases []Release      `json:"releases"`

	// RemovedVersions Versions of the pruned functions.
	RemovedVersions int `json:"removed_versions"`
}

// DeploymentPage defines model for DeploymentPage.
type DeploymentPage struct {
	Deployments []DeployedWorkload `json:"deployments"`
	NextCursor  *string            `json:"next_cursor,omitempty"`
}

// DeploymentPlan defines model for DeploymentPlan.
type DeploymentPlan struct {
	App AppName `json:"app"`

	// Items Listed workloads by kind and name, then omitted deployed ones.
	Items []DeploymentPlanItem `json:"items"`
	Prune bool                 `json:"prune"`
}

// DeploymentPlanAction `add` deploys a new workload, `redeploy` deploys one that exists, `retain` leaves an omitted one deployed and `remove` deletes an omitted one with prune.
type DeploymentPlanAction string

// DeploymentPlanItem defines model for DeploymentPlanItem.
type DeploymentPlanItem struct {
	// Action `add` deploys a new workload, `redeploy` deploys one that exists, `retain` leaves an omitted one deployed and `remove` deletes an omitted one with prune.
	Action DeploymentPlanAction `json:"action"`
	Kind   WorkloadKind         `json:"kind"`
	Name   WorkloadName         `json:"name"`

	// Versions Versions the workload has now.
	Versions int `json:"versions"`
}

// DeploymentPlanRequest defines model for DeploymentPlanRequest.
type DeploymentPlanRequest struct {
	Prune     *bool              `json:"prune,omitempty"`
	Workloads []WorkloadIdentity `json:"workloads"`
}

// DeploymentRequest defines model for DeploymentRequest.
type DeploymentRequest struct {
	// Functions At least one, unless prune deletes every deployed function.
	Functions []FunctionSpec `json:"functions"`

	// Prune Delete every function of the app that is not listed.
	Prune *bool `json:"prune,omitempty"`
}

// DeviceCode defines model for DeviceCode.
type DeviceCode struct {
	ClientName string           `json:"client_name"`
	CreatedAt  time.Time        `json:"created_at"`
	ExpiresAt  time.Time        `json:"expires_at"`
	Status     DeviceCodeStatus `json:"status"`
	UserCode   string           `json:"user_code"`
}

// DeviceCodeStatus defines model for DeviceCodeStatus.
type DeviceCodeStatus string

// DeviceLogin defines model for DeviceLogin.
type DeviceLogin struct {
	// DeviceCode The CLI's secret for polling.
	DeviceCode          string `json:"device_code"`
	ExpiresInSeconds    int    `json:"expires_in_seconds"`
	PollIntervalSeconds int    `json:"poll_interval_seconds"`

	// UserCode What the person confirms at the verification page.
	UserCode        string `json:"user_code"`
	VerificationUri string `json:"verification_uri"`

	// VerificationUriComplete The verification page with the code filled in.
	VerificationUriComplete string `json:"verification_uri_complete"`
}

// DeviceLoginRequest defines model for DeviceLoginRequest.
type DeviceLoginRequest struct {
	// ClientName Names the device token, such as cli@laptop.
	ClientName *string `json:"client_name,omitempty"`
}

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	DeviceCode string `json:"device_code"`
}

// DeviceTokenResponse defines model for DeviceTokenResponse.
type DeviceTokenResponse struct {
	// PollIntervalSeconds Wait at least this long before the next poll.
	PollIntervalSeconds int               `json:"poll_interval_seconds"`
	Status              DeviceTokenStatus `json:"status"`

	// Token The device token, on the poll that finds the login approved.
	Token *string `json:"token,omitempty"`
}

// DeviceTokenStatus defines model for DeviceTokenStatus.
type DeviceTokenStatus string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// FailureKind defines model for FailureKind.
type FailureKind string

// Function defines model for Function.
type Function struct {
	ActiveRelease Release       `json:"active_release"`
	App           AppName       `json:"app"`
	Name          WorkloadName  `json:"name"`
	State         FunctionState `json:"state"`
}

// FunctionState defines model for Function.State.
type FunctionState string

// FunctionSpec defines model for FunctionSpec.
type FunctionSpec struct {
	Autoscaler *Autoscaler `json:"autoscaler,omitempty"`

	// ClientContract The signature `lazycloud app export` types clients from.
	ClientContract *json.RawMessage `json:"client_contract,omitempty"`

	// Concurrency Tasks one container runs at once, one process per slot.
	Concurrency *int               `json:"concurrency,omitempty"`
	Environment *map[string]string `json:"environment,omitempty"`

	// Handler module:qualname within the source archive
	Handler string    `json:"handler"`
	Image   ImageSpec `json:"image"`

	// KeepWarmSeconds Idle time before a container above the minimum stops.
	KeepWarmSeconds *int         `json:"keep_warm_seconds,omitempty"`
	MaxPendingTasks *int         `json:"max_pending_tasks,omitempty"`
	Name            WorkloadName `json:"name"`

	// Resources Reservations the container always keeps. CPU above the reservation is shared up to `cpu_limit_millis`, by default the reservation plus 16 cores. Memory above the reservation is allowed up to `memory_limit_mib`, by default four times the reservation, at least 1 GiB and at most 8 GiB above it; the container is killed beyond it.
	Resources      Resources    `json:"resources"`
	RetryPolicy    *RetryPolicy `json:"retry_policy,omitempty"`
	Source         SourceRef    `json:"source"`
	TimeoutSeconds *int         `json:"timeout_seconds,omitempty"`
}

// Image defines model for Image.
type Image struct {
	Architecture  ImageArchitecture `json:"architecture"`
	CreatedAt     time.Time         `json:"created_at"`
	Id            ImageId           `json:"id"`
	PythonVersion string            `json:"python_version"`

	// Ready The image is published and can be deployed.
	Ready   bool       `json:"ready"`
	ReadyAt *time.Time `json:"ready_at,omitempty"`
}

// ImageArchitecture defines model for ImageArchitecture.
type ImageArchitecture string

// ImageBuild defines model for ImageBuild.
type ImageBuild struct {
	// Attempt Build containers started so far, at most 2.
	Attempt    int                `json:"attempt"`
	CreatedAt  time.Time          `json:"created_at"`
	Failure    *string            `json:"failure,omitempty"`
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	ImageId    ImageId            `json:"image_id"`

	// Phase queued waits for a host with room, starting prepares the build container, building runs the build and finished means the status is final.
	Phase  ImageBuildPhase  `json:"phase"`
	Status ImageBuildStatus `json:"status"`
}

// ImageBuildLogEntry defines model for ImageBuildLogEntry.
type ImageBuildLogEntry struct {
	Attempt int `json:"attempt"`

	// Data One line of build output without its trailing newline.
	Data string    `json:"data"`
	Id   int64     `json:"id"`
	Time time.Time `json:"time"`
}

// ImageBuildPhase queued waits for a host with room, starting prepares the build container, building runs the build and finished means the status is final.
type ImageBuildPhase string

// ImageBuildStatus defines model for ImageBuildStatus.
type ImageBuildStatus string

// ImageDefinition What an image contains. Steps run in order after python_packages and before commands.
type ImageDefinition struct {
	Architecture *ImageDefinitionArchitecture `json:"architecture,omitempty"`

	// BaseImage A registry image to start from.
	BaseImage *string `json:"base_image,omitempty"`

	// BaseImageCredentials Registry credentials by environment variable name.
	BaseImageCredentials *map[string]string `json:"base_image_credentials,omitempty"`
	Commands             *[]string          `json:"commands,omitempty"`
	Context              *SourceRef         `json:"context,omitempty"`

	// Dockerfile A Dockerfile that replaces the base image and Python setup.
	Dockerfile *string            `json:"dockerfile,omitempty"`
	Env        *map[string]string `json:"env,omitempty"`

	// Gpu The GPU model the build runs on.
	Gpu *string `json:"gpu,omitempty"`

	// Micromamba Micromamba provides Python and the base environment.
	Micromamba     *bool     `json:"micromamba,omitempty"`
	PythonPackages *[]string `json:"python_packages,omitempty"`

	// PythonVersion A supported minor release or an exact patch release.
	PythonVersion string `json:"python_version"`

	// Secrets Workspace secrets the build reads as build arguments.
	Secrets *[]string    `json:"secrets,omitempty"`
	Steps   *[]ImageStep `json:"steps,omitempty"`
}

// ImageDefinitionArchitecture defines model for ImageDefinition.Architecture.
type ImageDefinitionArchitecture string

// ImageId defines model for ImageId.
type ImageId = string

// ImageResolution defines model for ImageResolution.
type ImageResolution struct {
	Build *ImageBuild `json:"build,omitempty"`
	Image Image       `json:"image"`
}

// ImageSpec defines model for ImageSpec.
type ImageSpec struct {
	ImageId *ImageId `json:"image_id,omitempty"`

	// PythonVersion The Python minor version the runtime is mounted for.
	PythonVersion ImageSpecPythonVersion `json:"python_version"`

	// Reference The image by digest the release runs, set by the server.
	Reference *string `json:"reference,omitempty"`
}

// ImageSpecPythonVersion The Python minor version the runtime is mounted for.
type ImageSpecPythonVersion string

// ImageStep shell runs command. pip and micromamba install args. Project kinds install the project at args[0] with extras args[1:] and groups. micromamba_environment creates the environment from the file at args[0].
type ImageStep struct {
	Args    *[]string     `json:"args,omitempty"`
	Command *string       `json:"command,omitempty"`
	Groups  *[]string     `json:"groups,omitempty"`
	Kind    ImageStepKind `json:"kind"`
}

// ImageStepKind defines model for ImageStepKind.
type ImageStepKind string

// Invitation defines model for Invitation.
type Invitation struct {
	CreatedAt time.Time `json:"created_at"`

	// Delivery What became of an email: `queued` until the provider accepts it, then `sent`, and `delivered`, `bounced` or `complained` as the provider reports; `failed` when delivery gave up; `discarded` when it was withdrawn before sending.
	Delivery DeliveryState `json:"delivery"`
	Email    string        `json:"email"`

	// Expired Decided by the server's clock.
	Expired         bool                `json:"expired"`
	ExpiresAt       time.Time           `json:"expires_at"`
	Id              openapi_types.UUID  `json:"id"`
	InvitedByName   string              `json:"invited_by_name"`
	InvitedByUserId *openapi_types.UUID `json:"invited_by_user_id,omitempty"`

	// Role The roles an invitation or role change grants; ownership is never offered.
	Role        InvitationRole     `json:"role"`
	UpdatedAt   time.Time          `json:"updated_at"`
	WorkspaceId openapi_types.UUID `json:"workspace_id"`
}

// InvitationList defines model for InvitationList.
type InvitationList struct {
	Invitations []Invitation `json:"invitations"`
}

// InvitationPreview defines model for InvitationPreview.
type InvitationPreview struct {
	Email         string    `json:"email"`
	Expired       bool      `json:"expired"`
	ExpiresAt     time.Time `json:"expires_at"`
	InvitedByName string    `json:"invited_by_name"`

	// Role The roles an invitation or role change grants; ownership is never offered.
	Role          InvitationRole     `json:"role"`
	WorkspaceId   openapi_types.UUID `json:"workspace_id"`
	WorkspaceName Name               `json:"workspace_name"`
}

// InvitationRequest defines model for InvitationRequest.
type InvitationRequest struct {
	Email string          `json:"email"`
	Role  *InvitationRole `json:"role,omitempty"`
}

// InvitationRole The roles an invitation or role change grants; ownership is never offered.
type InvitationRole string

// LiveAppState defines model for LiveAppState.
type LiveAppState string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	Attempt int `json:"attempt"`

	// Data One line of output without its trailing newline.
	Data   string             `json:"data"`
	Id     int64              `json:"id"`
	Stream LogEntryStream     `json:"stream"`
	TaskId openapi_types.UUID `json:"task_id"`
	Time   time.Time          `json:"time"`
}

// LogEntryStream defines model for LogEntry.Stream.
type LogEntryStream string

// Me defines model for Me.
type Me struct {
	User       User        `json:"user"`
	Workspaces []Workspace `json:"workspaces"`
}

// Member defines model for Member.
type Member struct {
	// CreatedAt When the user joined.
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Role        WorkspaceRole      `json:"role"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// MemberList defines model for MemberList.
type MemberList struct {
	Members []Member `json:"members"`
}

// MemberRoleRequest defines model for MemberRoleRequest.
type MemberRoleRequest struct {
	// Role The roles an invitation or role change grants; ownership is never offered.
	Role InvitationRole `json:"role"`
}

// Name defines model for Name.
type Name = string

// Payload A task argument or return value. `json` carries `value`; `cloudpickle` carries base64 `data`. Arguments encode `{"args": [...], "kwargs": {...}}`.
type Payload struct {
	Data     *[]byte          `json:"data,omitempty"`
	Encoding PayloadEncoding  `json:"encoding"`
	Value    *json.RawMessage `json:"value,omitempty"`
}

// PayloadEncoding defines model for Payload.Encoding.
type PayloadEncoding string

// Release defines model for Release.
type Release struct {
	CreatedAt time.Time          `json:"created_at"`
	Function  WorkloadName       `json:"function"`
	Id        openapi_types.UUID `json:"id"`
	Spec      FunctionSpec       `json:"spec"`

	// Version The deployed version; absent for a release only working-tree calls use.
	Version *int `json:"version,omitempty"`
}

// Resources Reservations the container always keeps. CPU above the reservation is shared up to `cpu_limit_millis`, by default the reservation plus 16 cores. Memory above the reservation is allowed up to `memory_limit_mib`, by default four times the reservation, at least 1 GiB and at most 8 GiB above it; the container is killed beyond it.
type Resources struct {
	CpuLimitMillis *int `json:"cpu_limit_millis,omitempty"`
	CpuMillis      int  `json:"cpu_millis"`
	MemoryLimitMib *int `json:"memory_limit_mib,omitempty"`
	MemoryMib      int  `json:"memory_mib"`
}

// RetryPolicy defines model for RetryPolicy.
type RetryPolicy struct {
	Backoff      *RetryPolicyBackoff `json:"backoff,omitempty"`
	DelaySeconds *float32            `json:"delay_seconds,omitempty"`

	// MaxAttempts Attempts including the first.
	MaxAttempts     int      `json:"max_attempts"`
	MaxDelaySeconds *float32 `json:"max_delay_seconds,omitempty"`
}

// RetryPolicyBackoff defines model for RetryPolicy.Backoff.
type RetryPolicyBackoff string

// Sha256 Lowercase hex SHA-256 digest
type Sha256 = string

// SourceRef defines model for SourceRef.
type SourceRef struct {
	// Sha256 Lowercase hex SHA-256 digest
	Sha256 Sha256 `json:"sha256"`
}

// SourceUpload defines model for SourceUpload.
type SourceUpload struct {
	// Present The archive is stored and can be deployed.
	Present bool `json:"present"`

	// Sha256 Lowercase hex SHA-256 digest
	Sha256 Sha256 `json:"sha256"`

	// Upload Send the archive bytes with this request, then register the digest again.
	Upload *UploadTarget `json:"upload,omitempty"`
}

// SourceUploadRequest defines model for SourceUploadRequest.
type SourceUploadRequest struct {
	// Sha256 Lowercase hex SHA-256 digest
	Sha256    Sha256 `json:"sha256"`
	SizeBytes int64  `json:"size_bytes"`
}

// StartDeploymentRequest defines model for StartDeploymentRequest.
type StartDeploymentRequest struct {
	// Version Make this deployed version active before starting.
	Version *int `json:"version,omitempty"`
}

// StopReason defines model for StopReason.
type StopReason string

// StopTasksRequest defines model for StopTasksRequest.
type StopTasksRequest struct {
	TaskIds []openapi_types.UUID `json:"task_ids"`
}

// StopTasksResponse defines model for StopTasksResponse.
type StopTasksResponse struct {
	// Skipped Tasks that were already finished or are not in the workspace.
	Skipped []openapi_types.UUID `json:"skipped"`

	// Stopped Tasks this request cancelled.
	Stopped []openapi_types.UUID `json:"stopped"`
}

// SubmitTasksRequest defines model for SubmitTasksRequest.
type SubmitTasksRequest struct {
	Inputs []TaskInput `json:"inputs"`

	// ParentTaskId The task that submits these, which becomes their parent.
	ParentTaskId *openapi_types.UUID `json:"parent_task_id,omitempty"`

	// ReleaseId Run on this release, such as a prepared one, instead of the active one.
	ReleaseId *openapi_types.UUID `json:"release_id,omitempty"`
}

// SubmitTasksResponse defines model for SubmitTasksResponse.
type SubmitTasksResponse struct {
	Tasks []Task `json:"tasks"`
}

// Task defines model for Task.
type Task struct {
	App AppName `json:"app"`

	// Attempts Attempts started so far.
	Attempts int `json:"attempts"`

	// ContainerId The container of the latest attempt.
	ContainerId *openapi_types.UUID `json:"container_id,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	Failure     *TaskFailure        `json:"failure,omitempty"`
	FinishedAt  *time.Time          `json:"finished_at,omitempty"`
	Function    WorkloadName        `json:"function"`
	Id          openapi_types.UUID  `json:"id"`
	MaxAttempts int                 `json:"max_attempts"`

	// NextAttemptAt When a queued task that already ran becomes due again.
	NextAttemptAt *time.Time          `json:"next_attempt_at,omitempty"`
	ParentTaskId  *openapi_types.UUID `json:"parent_task_id,omitempty"`

	// Pending Why a queued task has not started, derived from current state on every read.
	Pending   *TaskPendingProgress `json:"pending,omitempty"`
	ReleaseId openapi_types.UUID   `json:"release_id"`

	// RootTaskId The first task of the call graph; the task itself when it has no parent.
	RootTaskId *openapi_types.UUID `json:"root_task_id,omitempty"`
	StartedAt  *time.Time          `json:"started_at,omitempty"`
	Status     TaskStatus          `json:"status"`

	// Version The deployed version of the release; absent for a working-tree release.
	Version *int `json:"version,omitempty"`
}

// TaskFailure defines model for TaskFailure.
type TaskFailure struct {
	// Exception The cloudpickled exception, when the runner could serialize it.
	Exception *[]byte     `json:"exception,omitempty"`
	Kind      FailureKind `json:"kind"`
	Message   string      `json:"message"`
	Traceback *string     `json:"traceback,omitempty"`

	// Type The exception type the handler raised.
	Type *string `json:"type,omitempty"`
}

// TaskInput A task's arguments. A cloudpickle input refers to each pending FunctionCall it contains by the persistent id `("function_call", task_id)` and lists those ids in `depends_on`; the task waits until they succeed and the runner resolves each id to that task's result.
type TaskInput struct {
	Data      *[]byte               `json:"data,omitempty"`
	DependsOn *[]openapi_types.UUID `json:"depends_on,omitempty"`
	Encoding  TaskInputEncoding     `json:"encoding"`
	Value     *json.RawMessage      `json:"value,omitempty"`
}

// TaskInputEncoding defines model for TaskInput.Encoding.
type TaskInputEncoding string

// TaskPage defines model for TaskPage.
type TaskPage struct {
	NextCursor *string `json:"next_cursor,omitempty"`
	Tasks      []Task  `json:"tasks"`
}

// TaskPendingProgress Why a queued task has not started, derived from current state on every read.
type TaskPendingProgress struct {
	Message    string    `json:"message"`
	ObservedAt time.Time `json:"observed_at"`

	// PendingSince When the task last became due or was submitted.
	PendingSince time.Time         `json:"pending_since"`
	Reason       TaskPendingReason `json:"reason"`

	// Since When the current reason began.
	Since time.Time `json:"since"`
}

// TaskPendingReason defines model for TaskPendingReason.
type TaskPendingReason string

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// Token defines model for Token.
type Token struct {
	CreatedAt time.Time `json:"created_at"`

	// Device Minted by `lazycloud login`.
	Device bool `json:"device"`

	// ExpiresAt Absent when the token never expires.
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`

	// LastUsedAt Recorded within 30 seconds of use; absent if never used.
	LastUsedAt *time.Time  `json:"last_used_at,omitempty"`
	Name       string      `json:"name"`
	Status     TokenStatus `json:"status"`

	// WorkspaceId Set when the token reaches only this workspace.
	WorkspaceId *openapi_types.UUID `json:"workspace_id,omitempty"`
}

// TokenCreateRequest defines model for TokenCreateRequest.
type TokenCreateRequest struct {
	// ExpiresInSeconds One to 90 days; omit for a token that never expires.
	ExpiresInSeconds *int   `json:"expires_in_seconds,omitempty"`
	Name             string `json:"name"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	// NextCursor Pass as `cursor` for the next page; absent after the last.
	NextCursor *openapi_types.UUID `json:"next_cursor,omitempty"`
	Tokens     []Token             `json:"tokens"`
}

// TokenStatus defines model for TokenStatus.
type TokenStatus string

// UploadTarget Send the archive bytes with this request, then register the digest again.
type UploadTarget struct {
	ExpiresAt time.Time          `json:"expires_at"`
	Headers   map[string]string  `json:"headers"`
	Method    UploadTargetMethod `json:"method"`

	// Url Absolute URL; the request carries no bearer token.
	Url string `json:"url"`
}

// UploadTargetMethod defines model for UploadTarget.Method.
type UploadTargetMethod string

// User defines model for User.
type User struct {
	AvatarUrl   string    `json:"avatar_url"`
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`

	// Email Empty when GitHub reported no verified primary address.
	Email string `json:"email"`

	// GithubLogin Empty for accounts that have not signed in with GitHub.
	GithubLogin string             `json:"github_login"`
	Id          openapi_types.UUID `json:"id"`

	// IsAdmin Platform administrators reach every workspace.
	IsAdmin bool `json:"is_admin"`
}

// Version defines model for Version.
type Version struct {
	Active    bool               `json:"active"`
	CreatedAt time.Time          `json:"created_at"`
	ReleaseId openapi_types.UUID `json:"release_id"`
	Version   int                `json:"version"`
}

// VersionPage defines model for VersionPage.
type VersionPage struct {
	NextCursor *string   `json:"next_cursor,omitempty"`
	Versions   []Version `json:"versions"`
}

// WorkloadIdentity defines model for WorkloadIdentity.
type WorkloadIdentity struct {
	Kind WorkloadKind `json:"kind"`
	Name WorkloadName `json:"name"`
}

// WorkloadKind defines model for WorkloadKind.
type WorkloadKind string

// WorkloadName defines model for WorkloadName.
type WorkloadName = string

// WorkloadState Desired state. A paused app stops its active workloads too.
type WorkloadState string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      Name               `json:"name"`

	// Role The caller's role; absent for an administrator who is not a member.
	Role  *WorkspaceRole `json:"role,omitempty"`
	State WorkspaceState `json:"state"`
}

// WorkspaceList defines model for WorkspaceList.
type WorkspaceList struct {
	// NextCursor Pass as `cursor` for the next page; absent after the last.
	NextCursor *Name       `json:"next_cursor,omitempty"`
	Workspaces []Workspace `json:"workspaces"`
}

// WorkspaceRequest defines model for WorkspaceRequest.
type WorkspaceRequest struct {
	Name Name `json:"name"`
}

// WorkspaceRole defines model for WorkspaceRole.
type WorkspaceRole string

// WorkspaceState defines model for WorkspaceState.
type WorkspaceState string

// AppPath defines model for AppPath.
type AppPath = AppName

// AppRefPath An app name or id.
type AppRefPath = AppRef

// ContainerPath defines model for ContainerPath.
type ContainerPath = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// DeploymentPath defines model for DeploymentPath.
type DeploymentPath = openapi_types.UUID

// FunctionPath defines model for FunctionPath.
type FunctionPath = WorkloadName

// ImageBuildPath defines model for ImageBuildPath.
type ImageBuildPath = openapi_types.UUID

// ImagePath defines model for ImagePath.
type ImagePath = ImageId

// InvitationPath defines model for InvitationPath.
type InvitationPath = openapi_types.UUID

// InvitationTokenPath defines model for InvitationTokenPath.
type InvitationTokenPath = string

// Limit defines model for Limit.
type Limit = int

// LogAfter defines model for LogAfter.
type LogAfter = int64

// LogTail defines model for LogTail.
type LogTail = int

// PageLimit defines model for PageLimit.
type PageLimit = int

// TaskPath defines model for TaskPath.
type TaskPath = openapi_types.UUID

// UserCodePath defines model for UserCodePath.
type UserCodePath = string

// WorkspacePath defines model for WorkspacePath.
type WorkspacePath = Name

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// IncludeDevice Include tokens minted by `lazycloud login`.
	IncludeDevice *bool  `form:"include_device,omitempty" json:"include_device,omitempty"`
	Limit         *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *openapi_types.UUID `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListWorkspacesParams defines parameters for ListWorkspaces.
type ListWorkspacesParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Name `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListAppsParams defines parameters for ListApps.
type ListAppsParams struct {
	// State Only apps in this state. Omitted lists active and paused apps.
	State *LiveAppState `form:"state,omitempty" json:"state,omitempty"`
	Limit *PageLimit    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListContainersParams defines parameters for ListContainers.
type ListContainersParams struct {
	// Live Only containers that have not stopped.
	Live  *bool      `form:"live,omitempty" json:"live,omitempty"`
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StreamContainerLogsParams defines parameters for StreamContainerLogs.
type StreamContainerLogsParams struct {
	// After Return entries with an id greater than this.
	After *LogAfter `form:"after,omitempty" json:"after,omitempty"`

	// Tail Start with only the last this many stored entries.
	Tail   *LogTail `form:"tail,omitempty" json:"tail,omitempty"`
	Follow *bool    `form:"follow,omitempty" json:"follow,omitempty"`
}

// ListDeploymentsParams defines parameters for ListDeployments.
type ListDeploymentsParams struct {
	App   *AppName      `form:"app,omitempty" json:"app,omitempty"`
	Name  *WorkloadName `form:"name,omitempty" json:"name,omitempty"`
	Limit *PageLimit    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StreamDeploymentLogsParams defines parameters for StreamDeploymentLogs.
type StreamDeploymentLogsParams struct {
	// After Return entries with an id greater than this.
	After *LogAfter `form:"after,omitempty" json:"after,omitempty"`

	// Tail Start with only the last this many stored entries.
	Tail   *LogTail `form:"tail,omitempty" json:"tail,omitempty"`
	Follow *bool    `form:"follow,omitempty" json:"follow,omitempty"`
}

// ListDeploymentVersionsParams defines parameters for ListDeploymentVersions.
type ListDeploymentVersionsParams struct {
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetImageBuildParams defines parameters for GetImageBuild.
type GetImageBuildParams struct {
	// WaitSeconds Hold the request until the build finishes or this many seconds pass.
	WaitSeconds *int `form:"wait_seconds,omitempty" json:"wait_seconds,omitempty"`
}

// StreamImageBuildLogsParams defines parameters for StreamImageBuildLogs.
type StreamImageBuildLogsParams struct {
	// After Return entries with an id greater than this.
	After *int64 `form:"after,omitempty" json:"after,omitempty"`

	// Follow Keep the stream open until the build finishes.
	Follow *bool `form:"follow,omitempty" json:"follow,omitempty"`
}

// BuildImageParams defines parameters for BuildImage.
type BuildImageParams struct {
	// Force Build again even when the image is ready.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	App *AppName `form:"app,omitempty" json:"app,omitempty"`

	// Function Requires `app`.
	Function *WorkloadName `form:"function,omitempty" json:"function,omitempty"`
	Status   *TaskStatus   `form:"status,omitempty" json:"status,omitempty"`
	Limit    *PageLimit    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor The `next_cursor` of the previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetTaskParams defines parameters for GetTask.
type GetTaskParams struct {
	// WaitSeconds Hold the request until the task finishes or this many seconds pass.
	WaitSeconds *int `form:"wait_seconds,omitempty" json:"wait_seconds,omitempty"`
}

// StreamTaskLogsParams defines parameters for StreamTaskLogs.
type StreamTaskLogsParams struct {
	// After Return entries with an id greater than this.
	After *LogAfter `form:"after,omitempty" json:"after,omitempty"`

	// Tail Start with only the last this many stored entries.
	Tail *LogTail `form:"tail,omitempty" json:"tail,omitempty"`

	// Follow Keep the stream open until the task finishes.
	Follow *bool `form:"follow,omitempty" json:"follow,omitempty"`
}

// StartDeviceLoginJSONRequestBody defines body for StartDeviceLogin for application/json ContentType.
type StartDeviceLoginJSONRequestBody = DeviceLoginRequest

// PollDeviceLoginJSONRequestBody defines body for PollDeviceLogin for application/json ContentType.
type PollDeviceLoginJSONRequestBody = DeviceTokenRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = TokenCreateRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = WorkspaceRequest

// RenameWorkspaceJSONRequestBody defines body for RenameWorkspace for application/json ContentType.
type RenameWorkspaceJSONRequestBody = WorkspaceRequest

// PlanDeploymentJSONRequestBody defines body for PlanDeployment for application/json ContentType.
type PlanDeploymentJSONRequestBody = DeploymentPlanRequest

// DeployAppJSONRequestBody defines body for DeployApp for application/json ContentType.
type DeployAppJSONRequestBody = DeploymentRequest

// PrepareFunctionReleaseJSONRequestBody defines body for PrepareFunctionRelease for application/json ContentType.
type PrepareFunctionReleaseJSONRequestBody = FunctionSpec

// SubmitTasksJSONRequestBody defines body for SubmitTasks for application/json ContentType.
type SubmitTasksJSONRequestBody = SubmitTasksRequest

// StartDeploymentJSONRequestBody defines body for StartDeployment for application/json ContentType.
type StartDeploymentJSONRequestBody = StartDeploymentRequest

// BuildImageJSONRequestBody defines body for BuildImage for application/json ContentType.
type BuildImageJSONRequestBody = ImageDefinition

// ResolveImageJSONRequestBody defines body for ResolveImage for application/json ContentType.
type ResolveImageJSONRequestBody = ImageDefinition

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = InvitationRequest

// SetMemberRoleJSONRequestBody defines body for SetMemberRole for application/json ContentType.
type SetMemberRoleJSONRequestBody = MemberRoleRequest

// CreateSourceUploadJSONRequestBody defines body for CreateSourceUpload for application/json ContentType.
type CreateSourceUploadJSONRequestBody = SourceUploadRequest

// StopTasksJSONRequestBody defines body for StopTasks for application/json ContentType.
type StopTasksJSONRequestBody = StopTasksRequest
