{{/*
Create ConfigMap to store compose_yaml metadata
*/}}
{{- if .Values.compose_yaml }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-compose-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lazycloud-compose.labels" . | nindent 4 }}
    app.kubernetes.io/component: compose-metadata
  annotations:
    lazycloud.io/compose-yaml: {{ .Values.compose_yaml | b64enc }}
{{- end }}
