//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/AmbientWare/lazycloud/internal/apitypes"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMe The authenticated user and the workspaces the token reaches
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// DeployApp Make the app's deployed workloads match the given definitions
	// (POST /v1/workspaces/{workspace}/apps/{app}/deployments)
	DeployApp(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath)

	// (GET /v1/workspaces/{workspace}/apps/{app}/functions/{function})
	GetFunction(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath)
	// SubmitTasks Admit one task per input against the function's active release
	// (POST /v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks)
	SubmitTasks(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath)
	// CreateSourceUpload Register a source archive by digest and get an upload URL when it is missing
	// (POST /v1/workspaces/{workspace}/sources)
	CreateSourceUpload(w http.ResponseWriter, r *http.Request, workspace WorkspacePath)
	// GetTask Read a task, optionally waiting until it finishes
	// (GET /v1/workspaces/{workspace}/tasks/{task})
	GetTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params GetTaskParams)
	// CancelTask Cancel a queued or running task
	// (POST /v1/workspaces/{workspace}/tasks/{task}/cancel)
	CancelTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath)
	// StreamTaskLogs Log lines after a cursor, one JSON LogEntry per line
	// (GET /v1/workspaces/{workspace}/tasks/{task}/logs)
	StreamTaskLogs(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params StreamTaskLogsParams)
	// GetTaskResult The value a succeeded task returned
	// (GET /v1/workspaces/{workspace}/tasks/{task}/result)
	GetTaskResult(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r, workspace, app)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFunction operation middleware
func (siw *ServerInterfaceWrapper) GetFunction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	// ------------- Path parameter "function" -------------
	var function FunctionPath

	err = runtime.BindStyledParameterWithOptions("simple", "function", r.PathValue("function"), &function, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "function", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFunction(w, r, workspace, app, function)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitTasks operation middleware
func (siw *ServerInterfaceWrapper) SubmitTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	// ------------- Path parameter "function" -------------
	var function FunctionPath

	err = runtime.BindStyledParameterWithOptions("simple", "function", r.PathValue("function"), &function, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "function", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTasks(w, r, workspace, app, function)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSourceUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateSourceUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSourceUpload(w, r, workspace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTaskParams

	// ------------- Optional query parameter "wait_seconds" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "wait_seconds", r.URL.Query(), &params.WaitSeconds, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "wait_seconds"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wait_seconds", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, workspace, task, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelTask operation middleware
func (siw *ServerInterfaceWrapper) CancelTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelTask(w, r, workspace, task)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTaskLogs operation middleware
func (siw *ServerInterfaceWrapper) StreamTaskLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTaskLogsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTaskLogs(w, r, workspace, task, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskResult operation middleware
func (siw *ServerInterfaceWrapper) GetTaskResult(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskResult(w, r, workspace, task)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/sources", wrapper.CreateSourceUpload)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/deployments", wrapper.DeployApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/functions/{function}", wrapper.GetFunction)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks", wrapper.SubmitTasks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}", wrapper.GetTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/result", wrapper.GetTaskResult)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/logs", wrapper.StreamTaskLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/cancel", wrapper.CancelTask)

	return m
}

type ErrorJSONResponse Error

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetMedefaultJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeployAppRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Body      *DeployAppJSONRequestBody
}

type DeployAppResponseObject interface {
	VisitDeployAppResponse(w http.ResponseWriter) error
}

type DeployApp200JSONResponse Deployment

func (response DeployApp200JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeployAppdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeployAppdefaultJSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunctionRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Function  FunctionPath  `json:"function"`
}

type GetFunctionResponseObject interface {
	VisitGetFunctionResponse(w http.ResponseWriter) error
}

type GetFunction200JSONResponse Function

func (response GetFunction200JSONResponse) VisitGetFunctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunctiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetFunctiondefaultJSONResponse) VisitGetFunctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitTasksRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Function  FunctionPath  `json:"function"`
	Body      *SubmitTasksJSONRequestBody
}

type SubmitTasksResponseObject interface {
	VisitSubmitTasksResponse(w http.ResponseWriter) error
}

type SubmitTasks201JSONResponse SubmitTasksResponse

func (response SubmitTasks201JSONResponse) VisitSubmitTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitTasksdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SubmitTasksdefaultJSONResponse) VisitSubmitTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSourceUploadRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Body      *CreateSourceUploadJSONRequestBody
}

type CreateSourceUploadResponseObject interface {
	VisitCreateSourceUploadResponse(w http.ResponseWriter) error
}

type CreateSourceUpload200JSONResponse SourceUpload

func (response CreateSourceUpload200JSONResponse) VisitCreateSourceUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSourceUploaddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateSourceUploaddefaultJSONResponse) VisitCreateSourceUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
	Params    GetTaskParams
}

type GetTaskResponseObject interface {
	VisitGetTaskResponse(w http.ResponseWriter) error
}

type GetTask200JSONResponse Task

func (response GetTask200JSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetTaskdefaultJSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTaskRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
}

type CancelTaskResponseObject interface {
	VisitCancelTaskResponse(w http.ResponseWriter) error
}

type CancelTask200JSONResponse Task

func (response CancelTask200JSONResponse) VisitCancelTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTaskdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CancelTaskdefaultJSONResponse) VisitCancelTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamTaskLogsRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
	Params    StreamTaskLogsParams
}

type StreamTaskLogsResponseObject interface {
	VisitStreamTaskLogsResponse(w http.ResponseWriter) error
}

type StreamTaskLogs200ApplicationxNdjsonResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamTaskLogs200ApplicationxNdjsonResponse) VisitStreamTaskLogsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-ndjson")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type StreamTaskLogsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StreamTaskLogsdefaultJSONResponse) VisitStreamTaskLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskResultRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
}

type GetTaskResultResponseObject interface {
	VisitGetTaskResultResponse(w http.ResponseWriter) error
}

type GetTaskResult200JSONResponse Payload

func (response GetTaskResult200JSONResponse) VisitGetTaskResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskResultdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetTaskResultdefaultJSONResponse) VisitGetTaskResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMe The authenticated user and the workspaces the token reaches
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// DeployApp Make the app's deployed workloads match the given definitions
	// (POST /v1/workspaces/{workspace}/apps/{app}/deployments)
	DeployApp(ctx context.Context, request DeployAppRequestObject) (DeployAppResponseObject, error)

	// (GET /v1/workspaces/{workspace}/apps/{app}/functions/{function})
	GetFunction(ctx context.Context, request GetFunctionRequestObject) (GetFunctionResponseObject, error)
	// SubmitTasks Admit one task per input against the function's active release
	// (POST /v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks)
	SubmitTasks(ctx context.Context, request SubmitTasksRequestObject) (SubmitTasksResponseObject, error)
	// CreateSourceUpload Register a source archive by digest and get an upload URL when it is missing
	// (POST /v1/workspaces/{workspace}/sources)
	CreateSourceUpload(ctx context.Context, request CreateSourceUploadRequestObject) (CreateSourceUploadResponseObject, error)
	// GetTask Read a task, optionally waiting until it finishes
	// (GET /v1/workspaces/{workspace}/tasks/{task})
	GetTask(ctx context.Context, request GetTaskRequestObject) (GetTaskResponseObject, error)
	// CancelTask Cancel a queued or running task
	// (POST /v1/workspaces/{workspace}/tasks/{task}/cancel)
	CancelTask(ctx context.Context, request CancelTaskRequestObject) (CancelTaskResponseObject, error)
	// StreamTaskLogs Log lines after a cursor, one JSON LogEntry per line
	// (GET /v1/workspaces/{workspace}/tasks/{task}/logs)
	StreamTaskLogs(ctx context.Context, request StreamTaskLogsRequestObject) (StreamTaskLogsResponseObject, error)
	// GetTaskResult The value a succeeded task returned
	// (GET /v1/workspaces/{workspace}/tasks/{task}/result)
	GetTaskResult(ctx context.Context, request GetTaskResultRequestObject) (GetTaskResultResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeployApp operation middleware
func (sh *strictHandler) DeployApp(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath) {
	var request DeployAppRequestObject

	request.Workspace = workspace
	request.App = app

	var body DeployAppJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployApp(ctx, request.(DeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployAppResponseObject); ok {
		if err := validResponse.VisitDeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFunction operation middleware
func (sh *strictHandler) GetFunction(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath) {
	var request GetFunctionRequestObject

	request.Workspace = workspace
	request.App = app
	request.Function = function

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFunction(ctx, request.(GetFunctionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFunction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFunctionResponseObject); ok {
		if err := validResponse.VisitGetFunctionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitTasks operation middleware
func (sh *strictHandler) SubmitTasks(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath) {
	var request SubmitTasksRequestObject

	request.Workspace = workspace
	request.App = app
	request.Function = function

	var body SubmitTasksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitTasks(ctx, request.(SubmitTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitTasksResponseObject); ok {
		if err := validResponse.VisitSubmitTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSourceUpload operation middleware
func (sh *strictHandler) CreateSourceUpload(w http.ResponseWriter, r *http.Request, workspace WorkspacePath) {
	var request CreateSourceUploadRequestObject

	request.Workspace = workspace

	var body CreateSourceUploadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSourceUpload(ctx, request.(CreateSourceUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSourceUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSourceUploadResponseObject); ok {
		if err := validResponse.VisitCreateSourceUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTask operation middleware
func (sh *strictHandler) GetTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params GetTaskParams) {
	var request GetTaskRequestObject

	request.Workspace = workspace
	request.Task = task
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTask(ctx, request.(GetTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskResponseObject); ok {
		if err := validResponse.VisitGetTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelTask operation middleware
func (sh *strictHandler) CancelTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath) {
	var request CancelTaskRequestObject

	request.Workspace = workspace
	request.Task = task

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelTask(ctx, request.(CancelTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelTaskResponseObject); ok {
		if err := validResponse.VisitCancelTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamTaskLogs operation middleware
func (sh *strictHandler) StreamTaskLogs(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params StreamTaskLogsParams) {
	var request StreamTaskLogsRequestObject

	request.Workspace = workspace
	request.Task = task
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamTaskLogs(ctx, request.(StreamTaskLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamTaskLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamTaskLogsResponseObject); ok {
		if err := validResponse.VisitStreamTaskLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTaskResult operation middleware
func (sh *strictHandler) GetTaskResult(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath) {
	var request GetTaskResultRequestObject

	request.Workspace = workspace
	request.Task = task

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskResult(ctx, request.(GetTaskResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskResultResponseObject); ok {
		if err := validResponse.VisitGetTaskResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFprb9s41v4rBN8BBnih2E7aZlrvp2x3Zqc77WyRtFhgO1nnRDy2OZFIlqSSuIH/+4IXyZJFX5I03X7x",
	"ReLl3PicG+9oLkslBQpr6PiOKtBQokXt/50o9R7s3P3kgo6pcn8yKqBEOqagFM2oxs8V18jo2OoKM2ry",
	"OZbgpvygcUrH9P+Gqy2G4a0Znij1u1tluczoL5XILZdiy1bTOOTB+/1L6qtCAms2/QDmasuGFszV1s2m",
	"Updg6ZhWFWc0o3ah3DxjNRczv4Pb0ijIccs2N/WYBzMWGVq6+UZJYdBr7metpXY/ciksCut+glIFz8HJ",
	"cfinkcI922+TsJrfhaHJNVdeGWN6QhzfjGAcUFNdW4/7Uloq1JYHwnKNYJFNwHakyMDigeUl9kWZUc72",
	"kHgt0z3tLqPGgvXjUVQlHX+ikFt+7QhQUBlk9Dyl1ZWWPlFPht+1Xi1r87eaLy//xNy6Tev9/VGzFrWT",
	"4n8+wcGXc/cxOng1Ob8bZcdHyx9SLJ5UVpocCtR9yZZwO3HaBi7i8WU4haqwdHyYube8dHwejkajjJZc",
	"xL/NLlxYnKF225RcbFpqtHmpUWopd5DMRKFeLbiVtB20LRMy/RuqQi7KaOVdoYBSe5iEW0XpSqA3NG6x",
	"NPcDlIYq0BoW1NtJgRAP414LnoYJ/bXWjK5G3bh8Q/j5Vsmc4ucKTUJANbLuT2gN12cKc28scPsmzDuK",
	"2ot/D/tS8bR29D+FwuA6rJxZqQheo16Qmj4ip8TOkYBSxM7BEm6IkJYU3Fhkg9VhuZSyQBA9ua0YTUmq",
	"wcs1tJIM9wLH126gEwYaAzM/Zzt2+JVX4zfS9FqyDkhxcQ0FZxMdFZrRSkBl5yisw3Z0kDSV+pIzhoJm",
	"VEg7mcpKuOe5FNOC59ZD3MJZ78RKOSlAz9AvZCqlpA6LuDcliMVEoWBczCb+JNNwoid+WS64mfvB7nxq",
	"AUUCMzP6C/Ci0vgbF6zNSWVQT4LjyKgnpv7j/ICsrH/sWTQWtJ1MgRd+N7MwFsv0XlHLCSTw6D6JB+ce",
	"p3E/CKlxYB8ntI4dmz2RsVKpfVxR9EIBHGpftMZyysY6h7kvs4672SqB1cilN7S80hpFvlgH++5Bd1GY",
	"IVIgabwD0ZUwBCyRIsfMv1Na5mgMUaiJKaQd0JbTOHpxvMudobjmWoraQwBj3O0PxfsOtz1j6klrDoIV",
	"tQNr81FKVhU4/lxB4TRBbridc+EBy8hK50hA5/M6ulj5/ZODf8PBl8l5/OHc/+D8/8cbnidDAl5GvNmm",
	"njduUA3YV4hqcgO6nBjMpWBrscJoXUlvWIHEnUlyiVOpkUBLW3Apr9EzGnVAnM2ajopeHj/fHSi48KUL",
	"NV2q1gOPPcKYh5xFjUFhe/jreqCfZfViomTB88XuiVYv3oeh7vD7VXZNOvOjTnHqpkR8TKrv2fFotEX0",
	"6ZAqgSS1qTcE1pbWFlEKUVam1oMTtbBzKSbXqE2E6Brwng0ORzRzX4fh6yh8PQtfz3cD4NraKcreYZ8k",
	"54R2yf6jCebUJGvmXlGin7IzrPOEdPZIsbAjdzjYlju8Dy6/D14nxJ03AnpWOYgkUhONttKCXENR4YBc",
	"uGzxguSgNUdDLvzji7+Qi7yQFVM8vypw9foSDB4/JxcMLFwMyElc1hAULughF3d/UNAz8wcdk0+DweA8",
	"I3/Qq5v60d1gMFguLwY0W1OVW6+TB14ubDJd9Pu43y0DcxzQjLYIToYPnjM6vlvXTrNkSimnq5Di8bnu",
	"tBXA3Ae39syRTTyY9wnwW+d1B3b4PVu1mnpmJy2ORKQl2QLfNVmqalLyouB1rhvx7NXRmiM4epH0LlhK",
	"vZiU/LI7/cVPRy+Pn3fmv9wJkS1aOiunWVqhfY+pS8iv5HTaAXA65bc+yq1Nt/l/GxTFN4TZDAtYJH1C",
	"2yFE/9B3xaIqL1eeGKzFUlmTQIv4hnCRF5U7FN77T7k23cDscI86A9xOemTvETbUtK7ppUN4Shlnczh6",
	"cdzn6a28QZ2DQTLHW3L268nB0YtjwvgsZFhttB0dvIKD6fnd8fM0yq4cdU/bptl9q6cPo9Z5i5OTXPkt",
	"P6oa3decrkYTA9+12HveRKUumTZWamQEBCM5CHKJhPnqQTq5zu7JTUarhr6tvtaP+uAyUrtJBlnD0y5p",
	"bKx63Jd4w7/gxPkb00FZLuzx87bNv3h2/PKn0avDo3uFXA1frW2SrFWXJbc+Z9rIGReqsvsHKHVQ0Knj",
	"NHW9TYWcddgPe+4kOdSn+zQ34f5eJLvFdoZTYckURX76A+uEtbPdAx19yQIZMZJMQQ9o3wiyh8UHoZiy",
	"j5Bi3cXPiqWa7ykUiWWJyZ7Do0DvxYGxYKu9DOosjEwGNKGo0mlBNZQ3e7SMYmcToK2cniXibY6qFnsf",
	"sVsRLCPN2IzczDHUG3QlXF6ey6pgxKDmUPAvSLh3zjtj56tYpNsaH7bqeVtLnhm1GnJ0Uc6W+kqKy4Yx",
	"31/yfMWElGjgpuOTNiSEnpPtBdaW4lupwucKKx9wOUm6lTNqqjxHZP5pU4XMQeRYFMnqXEY7jqzH4xkK",
	"RmzLAXvQ92UjYufckFjezdwgQTTOuLGo/ZQQlhCYARf9LAlvFddo7nVM5ggs9nkeXhsr0c5lp8D7/uOH",
	"pGgqXeyuj7tBzaIrErM2gymdfjSp3hiWwIskH3uhTwoVwpIpEjp4uJasJwp7W5P2VQGh7+m/Xle06Yqn",
	"u5t9Jh22Yl5pbhdnbo2YziDoIH2/sA8Yw6Nmgbm1KjSSuZhKrxFuC/fmLXxZvHbgRk7ev2nljmN66NiQ",
	"CgUoTsf02WA0eBai8rnfdnh9OAw8xrPmpOTb3G8YHdO/o30Xy1ar/vjRaPTVuuPvMNUafw2FgyvOXMpm",
	"FyFDiwlZer2GwKbf7pCnLEEv6nC93eghlUHt43WHCqvCkf9r5ZXHDcjnGNyak9Jq0PCu+b0cglJmeAdK",
	"LYes6Rj2roN8SlO9GjLs3nhYZjsn1PdLlucZVdIklBc6mCfNTRM09q+SLb6a7vod0uVyuX4XY/mExrMi",
	"IGVEp2iqwrocu2n4PtaO3sEV1p3UH02T5JGbiFqGlGDzuR8y49coCEMXPobe6f6W1PRbh3f1z+W2M/pL",
	"O756ImE3eyRE7c5X02x2p4pbQ0IHrRb+g2S/zL7ZKdo9tHPVann+KGUOm7Ttu+VvE6q0stInwpVEqr4X",
	"sBw+DQVhj+QNLlZy67yJ12ZGuCA+nSdSM9QPsvg22vjlfRPXre87uGF5H74aG2qHUWs/9g/cdgttV4sf",
	"Y4MbDeW1T+Q6BbYnspdE1eobe6IOlwlLCe9JuFzwWLs4rTMaWGuQk8tFk+EIRmbovkkoHpKPp29Dosv9",
	"/Z+SG1PH51usxFv28M59bfVAH8KdzzVL6grhV1mEeCsaAamE5YV/4g08FlqMa6L5RM5doSGxuk0UGN8Z",
	"9zdBP1eoF62roMBXHd327c9kGf94Rz/dmfSTWUqowKVdqPXvHm0dwAj4tTIiVUhIiwVxMnLBUBA6t424",
	"6dN72ebC8C632Ta3YSgSfAMn2SJvI5h5Wj7UN5v/R8ZBYOrOfaye+B0ebS+BMwIk1G58BzsUb6I93kNj",
	"hZyZjShxZjVC6Vh864btAIvT0EVHYTWvqzsgCGdk5v2KgwgQHic2oYIX1kY46DcitkFCtk7fb4gq3FHy",
	"bBGXY28CtE0ETmVRyJs0hfFuZ+9i5v2w6fZAsL4JriqZXIAnaL1m07PA3/Gm4AIPGBa85C7meStnPwur",
	"FyTUNR6fXL2VM+L2MNHKgeSVNlKHe2z/OPvn76s9XSzkxn632KXRREFs85ghRX1KRGl6VGlQiWR+jfqK",
	"v/7hQpK63hvOQLgNg+wba6pVZPN71eW1T+fuBBnU1zUVvqJKh27SfwcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
