//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/AmbientWare/lazycloud/internal/apitypes"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMe The authenticated user and the workspaces the token reaches
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// DeployApp Make the app's deployed workloads match the given definitions
	// (POST /v1/workspaces/{workspace}/apps/{app}/deployments)
	DeployApp(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath)

	// (GET /v1/workspaces/{workspace}/apps/{app}/functions/{function})
	GetFunction(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath)
	// SubmitTasks Admit one task per input against the function's active release
	// (POST /v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks)
	SubmitTasks(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath)
	// ListSchedules Scheduled functions with their next and last runs
	// (GET /v1/workspaces/{workspace}/schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, params ListSchedulesParams)
	// ListSecrets Secret names and update times, without values
	// (GET /v1/workspaces/{workspace}/secrets)
	ListSecrets(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, params ListSecretsParams)
	// CreateSecret Create a secret; an existing name is a conflict
	// (POST /v1/workspaces/{workspace}/secrets)
	CreateSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath)

	// (DELETE /v1/workspaces/{workspace}/secrets/{secret})
	DeleteSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath)
	// GetSecret A secret without its value
	// (GET /v1/workspaces/{workspace}/secrets/{secret})
	GetSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath)
	// UpdateSecret Replace an existing secret's value
	// (PATCH /v1/workspaces/{workspace}/secrets/{secret})
	UpdateSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath)
	// SetSecret Create the secret or replace its value
	// (PUT /v1/workspaces/{workspace}/secrets/{secret})
	SetSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath)
	// GetSecretValue Reveal a secret's value
	// (GET /v1/workspaces/{workspace}/secrets/{secret}/value)
	GetSecretValue(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath)
	// CreateSourceUpload Register a source archive by digest and get an upload URL when it is missing
	// (POST /v1/workspaces/{workspace}/sources)
	CreateSourceUpload(w http.ResponseWriter, r *http.Request, workspace WorkspacePath)
	// GetTask Read a task, optionally waiting until it finishes
	// (GET /v1/workspaces/{workspace}/tasks/{task})
	GetTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params GetTaskParams)
	// CancelTask Cancel a queued or running task
	// (POST /v1/workspaces/{workspace}/tasks/{task}/cancel)
	CancelTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath)
	// StreamTaskLogs Log lines after a cursor, one JSON LogEntry per line
	// (GET /v1/workspaces/{workspace}/tasks/{task}/logs)
	StreamTaskLogs(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params StreamTaskLogsParams)
	// GetTaskResult The value a succeeded task returned
	// (GET /v1/workspaces/{workspace}/tasks/{task}/result)
	GetTaskResult(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApp operation middleware
func (siw *ServerInterfaceWrapper) DeployApp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApp(w, r, workspace, app)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFunction operation middleware
func (siw *ServerInterfaceWrapper) GetFunction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	// ------------- Path parameter "function" -------------
	var function FunctionPath

	err = runtime.BindStyledParameterWithOptions("simple", "function", r.PathValue("function"), &function, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "function", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFunction(w, r, workspace, app, function)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitTasks operation middleware
func (siw *ServerInterfaceWrapper) SubmitTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "app" -------------
	var app AppPath

	err = runtime.BindStyledParameterWithOptions("simple", "app", r.PathValue("app"), &app, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "app", Err: err})
		return
	}

	// ------------- Path parameter "function" -------------
	var function FunctionPath

	err = runtime.BindStyledParameterWithOptions("simple", "function", r.PathValue("function"), &function, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "function", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTasks(w, r, workspace, app, function)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, workspace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSecrets operation middleware
func (siw *ServerInterfaceWrapper) ListSecrets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSecretsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSecrets(w, r, workspace, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSecret operation middleware
func (siw *ServerInterfaceWrapper) CreateSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSecret(w, r, workspace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSecret operation middleware
func (siw *ServerInterfaceWrapper) DeleteSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "secret" -------------
	var secret SecretPath

	err = runtime.BindStyledParameterWithOptions("simple", "secret", r.PathValue("secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSecret(w, r, workspace, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSecret operation middleware
func (siw *ServerInterfaceWrapper) GetSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "secret" -------------
	var secret SecretPath

	err = runtime.BindStyledParameterWithOptions("simple", "secret", r.PathValue("secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSecret(w, r, workspace, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSecret operation middleware
func (siw *ServerInterfaceWrapper) UpdateSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "secret" -------------
	var secret SecretPath

	err = runtime.BindStyledParameterWithOptions("simple", "secret", r.PathValue("secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSecret(w, r, workspace, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSecret operation middleware
func (siw *ServerInterfaceWrapper) SetSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "secret" -------------
	var secret SecretPath

	err = runtime.BindStyledParameterWithOptions("simple", "secret", r.PathValue("secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSecret(w, r, workspace, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSecretValue operation middleware
func (siw *ServerInterfaceWrapper) GetSecretValue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "secret" -------------
	var secret SecretPath

	err = runtime.BindStyledParameterWithOptions("simple", "secret", r.PathValue("secret"), &secret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSecretValue(w, r, workspace, secret)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSourceUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateSourceUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSourceUpload(w, r, workspace)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTaskParams

	// ------------- Optional query parameter "wait_seconds" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "wait_seconds", r.URL.Query(), &params.WaitSeconds, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "wait_seconds"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wait_seconds", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, workspace, task, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelTask operation middleware
func (siw *ServerInterfaceWrapper) CancelTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelTask(w, r, workspace, task)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTaskLogs operation middleware
func (siw *ServerInterfaceWrapper) StreamTaskLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTaskLogsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "follow" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "follow", r.URL.Query(), &params.Follow, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "follow"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "follow", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTaskLogs(w, r, workspace, task, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskResult operation middleware
func (siw *ServerInterfaceWrapper) GetTaskResult(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "workspace" -------------
	var workspace WorkspacePath

	err = runtime.BindStyledParameterWithOptions("simple", "workspace", r.PathValue("workspace"), &workspace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace", Err: err})
		return
	}

	// ------------- Path parameter "task" -------------
	var task TaskPath

	err = runtime.BindStyledParameterWithOptions("simple", "task", r.PathValue("task"), &task, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskResult(w, r, workspace, task)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/sources", wrapper.CreateSourceUpload)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/deployments", wrapper.DeployApp)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/functions/{function}", wrapper.GetFunction)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks", wrapper.SubmitTasks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}", wrapper.GetTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/result", wrapper.GetTaskResult)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/logs", wrapper.StreamTaskLogs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/tasks/{task}/cancel", wrapper.CancelTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets", wrapper.ListSecrets)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets", wrapper.CreateSecret)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets/{secret}", wrapper.DeleteSecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets/{secret}", wrapper.GetSecret)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets/{secret}", wrapper.UpdateSecret)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets/{secret}", wrapper.SetSecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/secrets/{secret}/value", wrapper.GetSecretValue)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/workspaces/{workspace}/schedules", wrapper.ListSchedules)

	return m
}

type ErrorJSONResponse Error

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetMedefaultJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeployAppRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Body      *DeployAppJSONRequestBody
}

type DeployAppResponseObject interface {
	VisitDeployAppResponse(w http.ResponseWriter) error
}

type DeployApp200JSONResponse Deployment

func (response DeployApp200JSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeployAppdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeployAppdefaultJSONResponse) VisitDeployAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunctionRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Function  FunctionPath  `json:"function"`
}

type GetFunctionResponseObject interface {
	VisitGetFunctionResponse(w http.ResponseWriter) error
}

type GetFunction200JSONResponse Function

func (response GetFunction200JSONResponse) VisitGetFunctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunctiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetFunctiondefaultJSONResponse) VisitGetFunctionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitTasksRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	App       AppPath       `json:"app"`
	Function  FunctionPath  `json:"function"`
	Body      *SubmitTasksJSONRequestBody
}

type SubmitTasksResponseObject interface {
	VisitSubmitTasksResponse(w http.ResponseWriter) error
}

type SubmitTasks201JSONResponse SubmitTasksResponse

func (response SubmitTasks201JSONResponse) VisitSubmitTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitTasksdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SubmitTasksdefaultJSONResponse) VisitSubmitTasksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Params    ListSchedulesParams
}

type ListSchedulesResponseObject interface {
	VisitListSchedulesResponse(w http.ResponseWriter) error
}

type ListSchedules200JSONResponse SchedulePage

func (response ListSchedules200JSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchedulesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListSchedulesdefaultJSONResponse) VisitListSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListSecretsRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Params    ListSecretsParams
}

type ListSecretsResponseObject interface {
	VisitListSecretsResponse(w http.ResponseWriter) error
}

type ListSecrets200JSONResponse SecretPage

func (response ListSecrets200JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSecretsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListSecretsdefaultJSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSecretRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Body      *CreateSecretJSONRequestBody
}

type CreateSecretResponseObject interface {
	VisitCreateSecretResponse(w http.ResponseWriter) error
}

type CreateSecret201JSONResponse Secret

func (response CreateSecret201JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateSecretdefaultJSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecretRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Secret    SecretPath    `json:"secret"`
}

type DeleteSecretResponseObject interface {
	VisitDeleteSecretResponse(w http.ResponseWriter) error
}

type DeleteSecret204Response struct {
}

func (response DeleteSecret204Response) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteSecretdefaultJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecretRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Secret    SecretPath    `json:"secret"`
}

type GetSecretResponseObject interface {
	VisitGetSecretResponse(w http.ResponseWriter) error
}

type GetSecret200JSONResponse Secret

func (response GetSecret200JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSecretdefaultJSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSecretRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Secret    SecretPath    `json:"secret"`
	Body      *UpdateSecretJSONRequestBody
}

type UpdateSecretResponseObject interface {
	VisitUpdateSecretResponse(w http.ResponseWriter) error
}

type UpdateSecret200JSONResponse Secret

func (response UpdateSecret200JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateSecretdefaultJSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SetSecretRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Secret    SecretPath    `json:"secret"`
	Body      *SetSecretJSONRequestBody
}

type SetSecretResponseObject interface {
	VisitSetSecretResponse(w http.ResponseWriter) error
}

type SetSecret200JSONResponse Secret

func (response SetSecret200JSONResponse) VisitSetSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetSecretdefaultJSONResponse) VisitSetSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecretValueRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Secret    SecretPath    `json:"secret"`
}

type GetSecretValueResponseObject interface {
	VisitGetSecretValueResponse(w http.ResponseWriter) error
}

type GetSecretValue200JSONResponse SecretValue

func (response GetSecretValue200JSONResponse) VisitGetSecretValueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecretValuedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSecretValuedefaultJSONResponse) VisitGetSecretValueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSourceUploadRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Body      *CreateSourceUploadJSONRequestBody
}

type CreateSourceUploadResponseObject interface {
	VisitCreateSourceUploadResponse(w http.ResponseWriter) error
}

type CreateSourceUpload200JSONResponse SourceUpload

func (response CreateSourceUpload200JSONResponse) VisitCreateSourceUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSourceUploaddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateSourceUploaddefaultJSONResponse) VisitCreateSourceUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
	Params    GetTaskParams
}

type GetTaskResponseObject interface {
	VisitGetTaskResponse(w http.ResponseWriter) error
}

type GetTask200JSONResponse Task

func (response GetTask200JSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetTaskdefaultJSONResponse) VisitGetTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTaskRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
}

type CancelTaskResponseObject interface {
	VisitCancelTaskResponse(w http.ResponseWriter) error
}

type CancelTask200JSONResponse Task

func (response CancelTask200JSONResponse) VisitCancelTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelTaskdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CancelTaskdefaultJSONResponse) VisitCancelTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamTaskLogsRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
	Params    StreamTaskLogsParams
}

type StreamTaskLogsResponseObject interface {
	VisitStreamTaskLogsResponse(w http.ResponseWriter) error
}

type StreamTaskLogs200ApplicationxNdjsonResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamTaskLogs200ApplicationxNdjsonResponse) VisitStreamTaskLogsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/x-ndjson")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type StreamTaskLogsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StreamTaskLogsdefaultJSONResponse) VisitStreamTaskLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskResultRequestObject struct {
	Workspace WorkspacePath `json:"workspace"`
	Task      TaskPath      `json:"task"`
}

type GetTaskResultResponseObject interface {
	VisitGetTaskResultResponse(w http.ResponseWriter) error
}

type GetTaskResult200JSONResponse Payload

func (response GetTaskResult200JSONResponse) VisitGetTaskResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTaskResultdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetTaskResultdefaultJSONResponse) VisitGetTaskResultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMe The authenticated user and the workspaces the token reaches
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// DeployApp Make the app's deployed workloads match the given definitions
	// (POST /v1/workspaces/{workspace}/apps/{app}/deployments)
	DeployApp(ctx context.Context, request DeployAppRequestObject) (DeployAppResponseObject, error)

	// (GET /v1/workspaces/{workspace}/apps/{app}/functions/{function})
	GetFunction(ctx context.Context, request GetFunctionRequestObject) (GetFunctionResponseObject, error)
	// SubmitTasks Admit one task per input against the function's active release
	// (POST /v1/workspaces/{workspace}/apps/{app}/functions/{function}/tasks)
	SubmitTasks(ctx context.Context, request SubmitTasksRequestObject) (SubmitTasksResponseObject, error)
	// ListSchedules Scheduled functions with their next and last runs
	// (GET /v1/workspaces/{workspace}/schedules)
	ListSchedules(ctx context.Context, request ListSchedulesRequestObject) (ListSchedulesResponseObject, error)
	// ListSecrets Secret names and update times, without values
	// (GET /v1/workspaces/{workspace}/secrets)
	ListSecrets(ctx context.Context, request ListSecretsRequestObject) (ListSecretsResponseObject, error)
	// CreateSecret Create a secret; an existing name is a conflict
	// (POST /v1/workspaces/{workspace}/secrets)
	CreateSecret(ctx context.Context, request CreateSecretRequestObject) (CreateSecretResponseObject, error)

	// (DELETE /v1/workspaces/{workspace}/secrets/{secret})
	DeleteSecret(ctx context.Context, request DeleteSecretRequestObject) (DeleteSecretResponseObject, error)
	// GetSecret A secret without its value
	// (GET /v1/workspaces/{workspace}/secrets/{secret})
	GetSecret(ctx context.Context, request GetSecretRequestObject) (GetSecretResponseObject, error)
	// UpdateSecret Replace an existing secret's value
	// (PATCH /v1/workspaces/{workspace}/secrets/{secret})
	UpdateSecret(ctx context.Context, request UpdateSecretRequestObject) (UpdateSecretResponseObject, error)
	// SetSecret Create the secret or replace its value
	// (PUT /v1/workspaces/{workspace}/secrets/{secret})
	SetSecret(ctx context.Context, request SetSecretRequestObject) (SetSecretResponseObject, error)
	// GetSecretValue Reveal a secret's value
	// (GET /v1/workspaces/{workspace}/secrets/{secret}/value)
	GetSecretValue(ctx context.Context, request GetSecretValueRequestObject) (GetSecretValueResponseObject, error)
	// CreateSourceUpload Register a source archive by digest and get an upload URL when it is missing
	// (POST /v1/workspaces/{workspace}/sources)
	CreateSourceUpload(ctx context.Context, request CreateSourceUploadRequestObject) (CreateSourceUploadResponseObject, error)
	// GetTask Read a task, optionally waiting until it finishes
	// (GET /v1/workspaces/{workspace}/tasks/{task})
	GetTask(ctx context.Context, request GetTaskRequestObject) (GetTaskResponseObject, error)
	// CancelTask Cancel a queued or running task
	// (POST /v1/workspaces/{workspace}/tasks/{task}/cancel)
	CancelTask(ctx context.Context, request CancelTaskRequestObject) (CancelTaskResponseObject, error)
	// StreamTaskLogs Log lines after a cursor, one JSON LogEntry per line
	// (GET /v1/workspaces/{workspace}/tasks/{task}/logs)
	StreamTaskLogs(ctx context.Context, request StreamTaskLogsRequestObject) (StreamTaskLogsResponseObject, error)
	// GetTaskResult The value a succeeded task returned
	// (GET /v1/workspaces/{workspace}/tasks/{task}/result)
	GetTaskResult(ctx context.Context, request GetTaskResultRequestObject) (GetTaskResultResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeployApp operation middleware
func (sh *strictHandler) DeployApp(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath) {
	var request DeployAppRequestObject

	request.Workspace = workspace
	request.App = app

	var body DeployAppJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeployApp(ctx, request.(DeployAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeployApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeployAppResponseObject); ok {
		if err := validResponse.VisitDeployAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFunction operation middleware
func (sh *strictHandler) GetFunction(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath) {
	var request GetFunctionRequestObject

	request.Workspace = workspace
	request.App = app
	request.Function = function

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFunction(ctx, request.(GetFunctionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFunction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFunctionResponseObject); ok {
		if err := validResponse.VisitGetFunctionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitTasks operation middleware
func (sh *strictHandler) SubmitTasks(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, app AppPath, function FunctionPath) {
	var request SubmitTasksRequestObject

	request.Workspace = workspace
	request.App = app
	request.Function = function

	var body SubmitTasksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitTasks(ctx, request.(SubmitTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitTasksResponseObject); ok {
		if err := validResponse.VisitSubmitTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchedules operation middleware
func (sh *strictHandler) ListSchedules(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, params ListSchedulesParams) {
	var request ListSchedulesRequestObject

	request.Workspace = workspace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchedules(ctx, request.(ListSchedulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchedules")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchedulesResponseObject); ok {
		if err := validResponse.VisitListSchedulesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSecrets operation middleware
func (sh *strictHandler) ListSecrets(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, params ListSecretsParams) {
	var request ListSecretsRequestObject

	request.Workspace = workspace
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSecrets(ctx, request.(ListSecretsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSecrets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSecretsResponseObject); ok {
		if err := validResponse.VisitListSecretsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSecret operation middleware
func (sh *strictHandler) CreateSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath) {
	var request CreateSecretRequestObject

	request.Workspace = workspace

	var body CreateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSecret(ctx, request.(CreateSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSecretResponseObject); ok {
		if err := validResponse.VisitCreateSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSecret operation middleware
func (sh *strictHandler) DeleteSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath) {
	var request DeleteSecretRequestObject

	request.Workspace = workspace
	request.Secret = secret

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSecret(ctx, request.(DeleteSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSecretResponseObject); ok {
		if err := validResponse.VisitDeleteSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSecret operation middleware
func (sh *strictHandler) GetSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath) {
	var request GetSecretRequestObject

	request.Workspace = workspace
	request.Secret = secret

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSecret(ctx, request.(GetSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSecretResponseObject); ok {
		if err := validResponse.VisitGetSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSecret operation middleware
func (sh *strictHandler) UpdateSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath) {
	var request UpdateSecretRequestObject

	request.Workspace = workspace
	request.Secret = secret

	var body UpdateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSecret(ctx, request.(UpdateSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSecretResponseObject); ok {
		if err := validResponse.VisitUpdateSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetSecret operation middleware
func (sh *strictHandler) SetSecret(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath) {
	var request SetSecretRequestObject

	request.Workspace = workspace
	request.Secret = secret

	var body SetSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetSecret(ctx, request.(SetSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetSecretResponseObject); ok {
		if err := validResponse.VisitSetSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSecretValue operation middleware
func (sh *strictHandler) GetSecretValue(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, secret SecretPath) {
	var request GetSecretValueRequestObject

	request.Workspace = workspace
	request.Secret = secret

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSecretValue(ctx, request.(GetSecretValueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSecretValue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSecretValueResponseObject); ok {
		if err := validResponse.VisitGetSecretValueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSourceUpload operation middleware
func (sh *strictHandler) CreateSourceUpload(w http.ResponseWriter, r *http.Request, workspace WorkspacePath) {
	var request CreateSourceUploadRequestObject

	request.Workspace = workspace

	var body CreateSourceUploadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSourceUpload(ctx, request.(CreateSourceUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSourceUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSourceUploadResponseObject); ok {
		if err := validResponse.VisitCreateSourceUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTask operation middleware
func (sh *strictHandler) GetTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params GetTaskParams) {
	var request GetTaskRequestObject

	request.Workspace = workspace
	request.Task = task
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTask(ctx, request.(GetTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskResponseObject); ok {
		if err := validResponse.VisitGetTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelTask operation middleware
func (sh *strictHandler) CancelTask(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath) {
	var request CancelTaskRequestObject

	request.Workspace = workspace
	request.Task = task

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelTask(ctx, request.(CancelTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelTaskResponseObject); ok {
		if err := validResponse.VisitCancelTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamTaskLogs operation middleware
func (sh *strictHandler) StreamTaskLogs(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath, params StreamTaskLogsParams) {
	var request StreamTaskLogsRequestObject

	request.Workspace = workspace
	request.Task = task
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamTaskLogs(ctx, request.(StreamTaskLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamTaskLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamTaskLogsResponseObject); ok {
		if err := validResponse.VisitStreamTaskLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTaskResult operation middleware
func (sh *strictHandler) GetTaskResult(w http.ResponseWriter, r *http.Request, workspace WorkspacePath, task TaskPath) {
	var request GetTaskResultRequestObject

	request.Workspace = workspace
	request.Task = task

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskResult(ctx, request.(GetTaskResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskResultResponseObject); ok {
		if err := validResponse.VisitGetTaskResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dxrc+O4kX8FxUtVqq5o+TFjZ9b7yfFms3vx7Lr8SOoy65NhsiUhpgAOANrWuPzfr7oBviFK8us2Vfdl",
	"PCLx6Hc3uht8jBI1z5UEaU10+BjlXPM5WND06yjPT7md4X+FjA6jHH/EkeRziA4jnudRHGn4WggNaXRo",
	"dQFxZJIZzDlO+YOGSXQY/cd2vcW2e2u2j/L8F1zl6SmOjgttlMYZKZhEi9wKhbtdzIBJeLDjhAYwNWF2",
	"BizXcCdUYVjOpzCKYgfa1wL0oobNTYma4Mz5wwnIKaKzv7sXR3aR40hjtZBTAuTHQia49wDOEz/k2Yj/",
	"Q+nbTPG0wv5EzIWtduugkdHL5topTHiR2ehwd2cnRpzEvJjTL/wppP9ZoSekhSlo2uocEg12ADtDA56N",
	"m1u/wuyCm9uBzSw3t4NbTZSecxsdRkUh0ijEMCSmyXkCA9vcl2OejZZH6Annm1xJA6Qcf9HaSW2ipAVJ",
	"POR5nomEo4Rs/8ugFD+uuYlbjXZpa8ERQ7xTBn5ACXWpoPgn1yoHbYUDLNHALaRjbltUTLmFLSvm0Cdl",
	"HIl0DYqXNF1TtePIWG5pPEiUyi8RT6y4QwByXhhIo6sQV2sufYkIDNq1XC1u4lfPVzf/gsTipuX+ZM2s",
	"BY1U/J8vfOvbFf6zs/Xd+OpxJz7Ye/pDCMWjwiqT8Ax0n7Jz/jBGbnMhvYWs1XEjZaS3y5Ya0Oud0FKo",
	"SGacg64XHARttaHo0fQHyDO1mHspbxOF5/kaIoGr5LqQQIImLMzNZqaygoprzRcRyUkG3CvjWgueuQn9",
	"tTpCVzo2v3wF+NUgZc7gawEmQKDSZ6wPaOmIznNISFj4w89u3p7nnv+526cKwdri/4RnBrpm5dyqnMEd",
	"6AUr4SsdLM9zZmfcMmGYVJZlwlhIR7Wy3CiVAZc9utWIhihV2cuOtVIprGUcj3EgEgOM4VOaM2w7aOV6",
	"/FKYjlXaMlJC3vFMpGPtGRpHheSFnYG0aNsBTdJE6RuRpiCjOJLKjieqkPg8UXKSicSSiVug9I6tUuOM",
	"6ynQQqbIc6XdIvhmzuVinINMhZyOSZMjp9FjWlZIYWY0GPVTS54FbGYc/chFVmj4m5BpE5PCgB47xxFH",
	"BEz5A/2AKiw9JhSN5dqOJ1xktJtZGAvz8F6eywFLQNZ97BVnA21cz4SUdmAdJ9S1Hfg8LbKV887LcYPe",
	"y1iV5+u4L++5nEEp/VeHTCG5bBmAPp1bLmqQavXIpzhKeJbd8OR2XOisH26fQQLiDgzjzIiphJSd/np+",
	"we5nIBlnKJJoEDRYLSBlSjMvnAYtQyO43tv5+CkgNomSSaE1yGTR9U6dsB+VgCkJrHJnTBfSMG6ZkgnE",
	"9C7XKgFjWA6amUxZD4Tzanv7B6v8b6KdBHdoUEgygbVJxN/CsMuLY1bKUAff3QNnkqvfAeRB3gmtZOlA",
	"eZoKXJ5npy3G9ub1BGPGZZpB4LA0Vwja4deCZyh07F7YmXDIGFXoBBjXyawMvuqw6Gjrn3zr2/jK/wej",
	"o9HVfx4ueR6MmMTcm+MhSfwZB5X+TMix599qR1WypCE/xHDDuGF2poGnBj0XCoUuJEqLXzvkseLoFiAf",
	"33M9HxtIlExNn5Y/pxkw/5bdwERpYLwhjfxG3QEB5WWMoUEwLRH8dPCxFWhtBaUwExNIFkkG45lStyvj",
	"gpNy+E802kUGHe8xfEZcIzJ9jnnV4IRsjRCsHEizrF6Mc5WJZLF6otWLUzcUbTMdNQO8c2dQU4pMaT8q",
	"22ZYQxfZHdeC32RgytjHoO4gBSixsE6s1jz0NiM1on0rOEP3L74W4AdYXQBiQvRYuQuNOoNJ9FQ577YA",
	"e5Z/ONjZGRDDcLwfcFmloakALPW8yeyQ60LRPIMJoKZ2YvNXtjsNWh/04+Da4PT8Z76wMyXHd6CNj2NK",
	"D/9htLsTxfhn1/3Zc38+uD8fV3v8ztohCnW0uCfCxzzLnFDaWWXThLxTt2DIrntjBA+WuVVjBjzBx9cd",
	"N3DNdMkKJqRVDX8wYkqOKepz3hVdK3nTthFlfGJB0zwvEgwV38SMy5QJa9jExZ4YHHB651IVI4b5O2Vn",
	"oA2uyYTsKCXXGDR70K2FeW5jHKV0Cvp7HCx0ubphXAPL1HQKKe2cKjqbJDMup84Wq8Imyilum91K+rB3",
	"hY51JPcpxpl+/+fNpQDpWVPJND5vZiElCuZz5pI4PG9mkZTufJO5oRDnM/Q1tjCrY91L4/xXlfAzG2Ua",
	"aMrK1AAB0tojpOEr8k9bQ/mnU3ds7JuFIxeDcz0tyHcpdGu20JLd8ayAEbvGjOM1S7jWAgy7psfX37Pr",
	"JFNFmovkNoP69Q03cPCRXafc8usRO/LLon/EgzO7fvwt4npqfosO2ZfRaHQVs9+i2/vy0eNoNHp6uu5r",
	"G67XyiXeLGww5Uj7eEkt7S9iEMVRA+DgEZQww3kPW1O15V/j3NEZv//sz/td1lX7hTh2Vp9ZX55MnTRO",
	"yJtEUWsmYY13aptkkBq+boX/pz0bZY5yZivv6oEIU7IRCnZPmAb0HWXHuwEaz+75wjAMzs2IHZ9eNoJs",
	"XU9DJ2NmXEPKipxZxa6TvBhTlWQ8F1kmzHXMbhbMh0O96XlWGLZ7wBKlwYzYZ5grvVi+Fc8ydV/vNafh",
	"1XY37b0mqtAMRcJ0l4rx6IryZdku+6v4MzkwbtlcGcs+uScEgrDfd+giDLsVWQYpu4GFIo/bV7kuDXyq",
	"2kd83+11gv69/eCBOC9eMr1Lm/Yi+3/a+3TwsbXKp4FVnjm/m/+rMWqtHJba+njRswGYM1GTSSvOjibi",
	"gTJlpemqfj84XRRLUnUpZHwRDN2bcbsP4/t5f1nMbzyt+MPYh00BXTvyb5iQSVag3XOJDaFNO1eyu0at",
	"gj+Me2AvPWL0Ye3wpQV4iBnnjWRd1xqHsjZUKEarmYlvkDJ4yDUYNFqjkPnMuLF1QNhe6R+zBZEJxzCV",
	"+IQDMJ7OhbWQMqnICy9fWBfS+4ruyiDrpV0onTa3uOeGpQWFr+t5GdqOMsUiDdMEXw6i09psac0PHppo",
	"rQccPv+mZCt9enlxvPr8RBxuzG/vPyQtp3wakJhGA0GfSKcaDIZSlOOcKw1Vjs+wiULjH2R0NWjtALOE",
	"Ma2S56sCzXqPIZzTgWT8Rjn154Ysm+fVg7W2RrxRrRjE2zUovEqUtk6eq53cKfJ0w13CuZVWINVYdDnG",
	"xzQjIN0b41CFzqunXMCDXYaCW2Y5wOUJqOOUZDD7Rgk3F/mcHP3zv49Pfr38YcxyDRPx4GoOGEo5c7Ui",
	"h4Qnq70P34WPVmX/y2vYCZ9mHLISdYpyg0TiasPgl11Oe+Jbu+HpYH//w8FSivy9lIl/D6VqCPFa6uZG",
	"P0ftiDCXNLJPnpdq0oAKzfje/kFfDE/UPeiEG2AzeGDnPx1t7e0fsFRMXZW6qRo7W9/xrcnV48HHJapQ",
	"5ZN7eJlq90HE3KiedLrHQaxoy8u8zG60d82dioUDGV+6otOfVdqnABMu2Q2wlDowwg0K8YbYoFyU8A3m",
	"mmjUBddTsMtoEFc4raLG0s6RTYE34huMMd9iWrokpD342Iz59z8cfPrTzne7e42wfXVloMKrsU0QteJm",
	"LiyVcZdiJmRebGAby6RYt8Iy3AzTgd/vuRJk1+PXh7mqr60FMi620pi7JUMQ0fQXBnVrnA4p4wspM4pN",
	"uB5FfSGIn5cCWy9tjlj63hWa5dtdfk/ZtpxrkCsOWj7nXh64uGUm5/fYQkHNA0rCWict3xEyXhMyrdQq",
	"uJSyZWUTmz/YVPN85iItglVYA9nExTVSYcfAtALdZZpWQlHG6+l4sqyJG890zeMnUag6UpfArH/y9UK7",
	"kZQYy22xltKeu5HBvGjvtNJgWbVHQ/E6QUeLY8u0/sdaddrKDw8J5KWkB6hcJ81TVo2NHXMblcREFVnK",
	"DGhB+ZIun5el6299b9lg1rnRhjbYqRdHVvMEMLE20PcSwrJCjNqiW3VJzYVphQFLwkLCZLgvsCEHjQTG",
	"1wIKyvF5fUeWY90LUnpaNc8lXCaASdtgArAVOwT6F6RTiTLmIT/ryr5kTHxXYoyDJNMwFaYs0LpIkPEp",
	"F7KfJYaHXGgwG2nNDHjq25Of37M0BztTrb7E08uLIGmCfWlHN0ZlhQV2eXbiTJcnQVXKkordANdIBXUL",
	"crUE4D4VXDWWcZNGIbG4NKGucJhzkQVJsZYhD9kZt2QIhJYXW91TMVhqrMue/fjs9e4DVPdBwn39fSTd",
	"2bnQwi4wbTT3SXjicHWhgsJ896haYGZt7q5QCDlRxBFhM3xzwr8tjtE+sqPTnxtFrcNoF9FQOUiei+gw",
	"+jDaGX1wZ6kZbbt9t7vtcPTqilSiqs7PaXQY/RXsZ98TU98M2dvZebV7IZ8hdCkEW0RAM5GCtMIuXF3B",
	"lxHC61UAVjdN0HjN51wvykNWs8WZFQY0nbJQ4epyN/0kLWMaeDLzRXykUj1o+7H6/9M2z3Oz/cjz/Gk7",
	"rXrle3fNvoShrodst+/6PMUrJ5SX156u4ihXJsA817t/VF1jA2P/rNLFq/Gufzfgqa0HvgXszYSnBiAk",
	"RGdgisxiyFdddXipHH3mt1DeIfijqY7m7N5bLcPm3CYzGjIVdyCxeiqkcLcG1pek6qbB9mP536chHf2x",
	"GbG9EbGrPQKkvmj2FJeNU64PvCT+s2jvzifvokWrh7auTz5dvYiZ29Vh+3eL3zKr0sglvJFdCSRY1jIs",
	"u28DgdsjeHexOuPhSGruoySMa/F7sbWh5anxmw6zOWi/PEXAxrZa+f/YV7hhCW1V+YKG5UQYe16N2lQV",
	"/bXnNQTPXRFGiXsz49UqogY4+asEum+N2YS6RkpsxN6UBV0aQ8M2aRQ4X8TcqsRZLVmdgkBouhhOG1Jt",
	"WxfS3Zuamk7x9KUWcoUZaxR5louIH/PvLSB17WyVePjSmJBU13slXXf704qG+O4KOK7hKibJUIV1rZAt",
	"USjLZS8WhGX23tVmz5tX51/d4DeLwO9t6n1ZMhzU+PSWZ/qLuexQZNyv9z3jksGDMBSlkjRRl3njlmWf",
	"z2sp7Paj+8+TyzdkYKHP2R/oeYOzLRJ/7Kcq3IT0mWQIieyygHYZUDvvxPdX4veRX6jSX4yLy3rtq6vw",
	"akPa+EIGKTweVvr0dxXhd9D4Zv35nY+O78L+M8gznkBLy93Sf1whBkUo8Ab7/zx5LRNsqxXdRQPHqGH1",
	"3MzyblcNFMFEOKKkZLZgFZNd3cjdeUAv4K89XGA2yjDqPMajhmIaODW8JlzSHSGsfLkqxxI7+neP0htz",
	"zm0zyL4qOeCI83IFuwOeMb6mVr2jcV0hK/UVgjcN2potKW9kNAJ9Hu9tNppYBqTPvWfu8wQvlzhfkOKd",
	"e+d0VcIXqGTKpiTrzLXbYGnH1SkFfXVkLowpayMDUkJZhe1H/DOY/btwX5rqSFKbCD+pLG0VlwppRVZX",
	"ysuPHaA1pDocfrijuiSec3fdPPQNr3su6qu6wU95NRv/D1Z87udND3muZyVsnyy9e7F08NR/TCJmKnf1",
	"xGzBkEZosR3Rha3IHb29Wao+U7bKKDXFbdvVeN8hQdkAb6kxI1guyu+p/R8Jh78p7Ivf/FWSQA4zxpkr",
	"vVMo0ui12cRAbGdqapZGG0e+kxePslYDn7N7LSx9DOUm4/KWZUKCx3B3v9L78tgC0moBJsY+qiQTiBm1",
	"JyK1F4xTRML8tf0RO/YjzK3IG8ubfoRyTrAg5U8Q+hU27MxdB/XA+KvikomUTcndoeXi7oMmy4wVYbjU",
	"SvU7CocsVdyF728AuQssHYlVDnKZnV0GoGNTGEL//ZDeV6o2M5kPWzLta0bdHyMkJ4C6ZfyeYvwC98jW",
	"rRTK2PRETf8irV74a/svr7edqKkTHS+anLkWdveNnP86//WXes8cNI393ZpUDcYTYsiRu6rlWxq6qtk0",
	"bOs8mK9RcqdgHCOlsovI6YA74rg80jtyqtF3QXuVHRdfrlCD6AqGh4L6dKJtnPS/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
