{{- if .Values.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  parentRefs:
    - name: lazycloud-gateway
      namespace: envoy-gateway-system
  hostnames:
    - {{ .Values.ingress.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
{{- end }}
