replicaCount: 1

backgroundWorkers:
  replicaCount: 1
  image:
    name: backend-background-workers
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi

crons:
  replicaCount: 1
  image:
    name: backend-crons
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

image:
  name: backend-api
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  hostname: api.lazycloud.dev
  healthCheckPath: /health
  annotations: {}

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

storage:
  storageClassName: efs-sc
  size: 10Gi

# Environment variables pulled from External Secrets
secrets:
  name: "app-secrets"
  env:
    - "ENV"
    - "DATABASE_URL"
    - "REDIS_URL"
    - "PREFECT_API_URL"
    - "WORKOS_API_KEY"
    - "WORKOS_CLIENT_ID"
    - "WORKOS_COOKIE_PASSWORD"
    - "AWS_ACCESS_KEY_ID"
    - "AWS_SECRET_ACCESS_KEY"
    - "AWS_REGION"
    - "DEPOT_TOKEN"
    - "DEPOT_PROJECT_ID"
    - "SENTRY_DSN"
