apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-secrets-external
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lazycloud-prod-secrets
    kind: ClusterSecretStore
  target:
    name: prefect-secrets
    creationPolicy: Owner
  data:
    # Basic auth credentials in format "username:password"
    - secretKey: auth-string
      remoteRef:
        key: lazycloud/prod-secrets
        property: PREFECT_API_AUTH_STRING
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-db-secret-external
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lazycloud-prod-secrets
    kind: ClusterSecretStore
  target:
    name: prefect-db-secret
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: lazycloud/prod-secrets
        property: PREFECT_DATABASE_URL
