apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prefect-secrets-external
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lazycloud-prod-secrets
    kind: ClusterSecretStore
  target:
    name: prefect-secrets
    creationPolicy: Owner
  data:
    # Basic auth credentials (used by Prefect server)
    - secretKey: username
      remoteRef:
        key: lazycloud-prod
        property: PREFECT_AUTH_USERNAME
    - secretKey: password
      remoteRef:
        key: lazycloud-prod
        property: PREFECT_AUTH_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prefect-db-secret-external
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lazycloud-prod-secrets
    kind: ClusterSecretStore
  target:
    name: prefect-db-secret
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: lazycloud-prod
        property: PREFECT_DATABASE_URL
