// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package edge

import (
	"context"

	"github.com/google/uuid"
)

const containerRelease = `-- name: ContainerRelease :one
select release_id::uuid from containers where id = $1 and state <> 'stopped' and release_id is not null
`

func (q *Queries) ContainerRelease(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, containerRelease, id)
	var release_id uuid.UUID
	err := row.Scan(&release_id)
	return release_id, err
}

const releaseOfVersion = `-- name: ReleaseOfVersion :one
select id from releases where workload_id = $1 and version = $2
`

type ReleaseOfVersionParams struct {
	WorkloadID uuid.UUID
	Version    *int32
}

func (q *Queries) ReleaseOfVersion(ctx context.Context, arg ReleaseOfVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, releaseOfVersion, arg.WorkloadID, arg.Version)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const releaseRoute = `-- name: ReleaseRoute :one
select rel.id as release_id, rel.version, rel.spec,
       w.id as workload_id, w.kind, w.name, w.desired_state, (w.active_release_id is not distinct from rel.id)::bool as active,
       a.id as app_id, a.name as app_name, a.state as app_state, a.workspace_id, ws.name as workspace_name,
       coalesce(p.stopped_at is null and p.lease_expires_at > now() and (p.deadline_at is null or p.deadline_at > now()), false)::bool as preview_live,
       -- Whether the workload's active release requires a token; every host
       -- of every release follows it, so going private closes old URLs.
       coalesce((ar.spec ->> 'authorized')::bool, ar.id is not null)::bool as active_authorized
from releases rel
join workloads w on w.id = rel.workload_id
join apps a on a.id = w.app_id
join workspaces ws on ws.id = a.workspace_id
left join previews p on p.release_id = rel.id
left join releases ar on ar.id = w.active_release_id
where rel.id = $1
`

type ReleaseRouteRow struct {
	ReleaseID        uuid.UUID
	Version          *int32
	Spec             []byte
	WorkloadID       uuid.UUID
	Kind             string
	Name             string
	DesiredState     string
	Active           bool
	AppID            uuid.UUID
	AppName          string
	AppState         string
	WorkspaceID      uuid.UUID
	WorkspaceName    string
	PreviewLive      bool
	ActiveAuthorized bool
}

// One release with its workload's routing context, for release, version,
// preview and container hosts.
func (q *Queries) ReleaseRoute(ctx context.Context, id uuid.UUID) (ReleaseRouteRow, error) {
	row := q.db.QueryRow(ctx, releaseRoute, id)
	var i ReleaseRouteRow
	err := row.Scan(
		&i.ReleaseID,
		&i.Version,
		&i.Spec,
		&i.WorkloadID,
		&i.Kind,
		&i.Name,
		&i.DesiredState,
		&i.Active,
		&i.AppID,
		&i.AppName,
		&i.AppState,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.PreviewLive,
		&i.ActiveAuthorized,
	)
	return i, err
}

const routes = `-- name: Routes :many
select r.workload_id, r.subdomain, r.hostname,
       coalesce(d.phase = 'ready', false)::bool as hostname_ready,
       w.kind, w.name, w.desired_state,
       a.id as app_id, a.name as app_name, a.state as app_state, a.workspace_id, ws.name as workspace_name,
       rel.id as release_id, rel.version, rel.spec
from http_routes r
join workloads w on w.id = r.workload_id
join apps a on a.id = w.app_id
join workspaces ws on ws.id = a.workspace_id
left join releases rel on rel.id = w.active_release_id
left join custom_domains d on d.hostname = r.hostname and exists (
    select 1 from workspace_members m
    where m.workspace_id = a.workspace_id and m.user_id = d.user_id and m.role = 'owner'
)
where w.desired_state <> 'deleted' and a.state <> 'deleted'
order by r.workload_id
`

type RoutesRow struct {
	WorkloadID    uuid.UUID
	Subdomain     string
	Hostname      *string
	HostnameReady bool
	Kind          string
	Name          string
	DesiredState  string
	AppID         uuid.UUID
	AppName       string
	AppState      string
	WorkspaceID   uuid.UUID
	WorkspaceName string
	ReleaseID     *uuid.UUID
	Version       *int32
	Spec          []byte
}

// Every claimed route with its workload, app, workspace and active release.
// The edge holds them in memory and reloads them on lc_route.
func (q *Queries) Routes(ctx context.Context) ([]RoutesRow, error) {
	rows, err := q.db.Query(ctx, routes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutesRow
	for rows.Next() {
		var i RoutesRow
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Subdomain,
			&i.Hostname,
			&i.HostnameReady,
			&i.Kind,
			&i.Name,
			&i.DesiredState,
			&i.AppID,
			&i.AppName,
			&i.AppState,
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.ReleaseID,
			&i.Version,
			&i.Spec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workloadRoute = `-- name: WorkloadRoute :one
select w.kind, r.subdomain, r.hostname, coalesce(d.phase = 'ready', false)::bool as hostname_ready
from http_routes r
join workloads w on w.id = r.workload_id
join apps a on a.id = w.app_id
left join custom_domains d on d.hostname = r.hostname and exists (
    select 1 from workspace_members m
    where m.workspace_id = a.workspace_id and m.user_id = d.user_id and m.role = 'owner'
)
where r.workload_id = $1
`

type WorkloadRouteRow struct {
	Kind          string
	Subdomain     string
	Hostname      *string
	HostnameReady bool
}

// Where a deployed HTTP workload answers: its kind, which the API path names,
// its subdomain and, once ready, its custom hostname.
func (q *Queries) WorkloadRoute(ctx context.Context, workloadID uuid.UUID) (WorkloadRouteRow, error) {
	row := q.db.QueryRow(ctx, workloadRoute, workloadID)
	var i WorkloadRouteRow
	err := row.Scan(
		&i.Kind,
		&i.Subdomain,
		&i.Hostname,
		&i.HostnameReady,
	)
	return i, err
}
