// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: callbacks.sql

package notifications

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const callbackDeliveries = `-- name: CallbackDeliveries :many
select c.id, c.task_id, c.workspace_id, c.url, c.event, c.attempt, c.max_attempts, c.failure,
       coalesce(t.root_task_id, t.id)::uuid as root_task_id, t.failure as task_failure, t.finished_at
from task_callbacks c
join tasks t on t.id = c.task_id
where c.id = any($1::bigint[])
order by c.id
`

type CallbackDeliveriesRow struct {
	ID          int64
	TaskID      uuid.UUID
	WorkspaceID uuid.UUID
	Url         string
	Event       string
	Attempt     int32
	MaxAttempts int32
	Failure     []byte
	RootTaskID  uuid.UUID
	TaskFailure []byte
	FinishedAt  *time.Time
}

func (q *Queries) CallbackDeliveries(ctx context.Context, ids []int64) ([]CallbackDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, callbackDeliveries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallbackDeliveriesRow
	for rows.Next() {
		var i CallbackDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.WorkspaceID,
			&i.Url,
			&i.Event,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Failure,
			&i.RootTaskID,
			&i.TaskFailure,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const callbackResult = `-- name: CallbackResult :one
select encoding,
       (case when octet_length(data) <= $1::int then data end)::bytea as data
from task_results
where task_id = $2
`

type CallbackResultParams struct {
	MaxBytes int32
	TaskID   uuid.UUID
}

type CallbackResultRow struct {
	Encoding string
	Data     []byte
}

// The task's result for one delivery: its data only when it is at most
// max_bytes, so no batch holds large results.
func (q *Queries) CallbackResult(ctx context.Context, arg CallbackResultParams) (CallbackResultRow, error) {
	row := q.db.QueryRow(ctx, callbackResult, arg.MaxBytes, arg.TaskID)
	var i CallbackResultRow
	err := row.Scan(&i.Encoding, &i.Data)
	return i, err
}

const claimDueCallbacks = `-- name: ClaimDueCallbacks :many
update task_callbacks c
set next_attempt_at = now() + make_interval(secs => $1::float8),
    deliveries = c.deliveries + 1
where c.id in (
    select d.id from task_callbacks d
    where d.state = 'pending' and d.next_attempt_at <= now()
    order by d.next_attempt_at, d.id
    limit $2
    for update skip locked
)
returning c.id, c.deliveries
`

type ClaimDueCallbacksParams struct {
	LeaseSeconds float64
	BatchSize    int32
}

type ClaimDueCallbacksRow struct {
	ID         int64
	Deliveries int32
}

// Leases due callbacks to this deliverer: next_attempt_at moves past the
// delivery timeout and deliveries counts the attempt, which fences a late
// outcome from an earlier lease.
func (q *Queries) ClaimDueCallbacks(ctx context.Context, arg ClaimDueCallbacksParams) ([]ClaimDueCallbacksRow, error) {
	rows, err := q.db.Query(ctx, claimDueCallbacks, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueCallbacksRow
	for rows.Next() {
		var i ClaimDueCallbacksRow
		if err := rows.Scan(&i.ID, &i.Deliveries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishCallback = `-- name: FinishCallback :exec
update task_callbacks
set state = $1, last_error = $2, finished_at = now()
where id = $3 and deliveries = $4 and state = 'pending'
`

type FinishCallbackParams struct {
	State      string
	LastError  *string
	ID         int64
	Deliveries int32
}

func (q *Queries) FinishCallback(ctx context.Context, arg FinishCallbackParams) error {
	_, err := q.db.Exec(ctx, finishCallback,
		arg.State,
		arg.LastError,
		arg.ID,
		arg.Deliveries,
	)
	return err
}

const purgeFinishedCallbacks = `-- name: PurgeFinishedCallbacks :execrows
delete from task_callbacks
where id in (
    select f.id from task_callbacks f
    where f.state <> 'pending' and f.finished_at < now() - make_interval(secs => $1::float8)
    limit $2
)
`

type PurgeFinishedCallbacksParams struct {
	RetainSeconds float64
	BatchSize     int32
}

func (q *Queries) PurgeFinishedCallbacks(ctx context.Context, arg PurgeFinishedCallbacksParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeFinishedCallbacks, arg.RetainSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryCallback = `-- name: RetryCallback :exec
update task_callbacks
set next_attempt_at = now() + make_interval(secs => $1::float8), last_error = $2
where id = $3 and deliveries = $4 and state = 'pending'
`

type RetryCallbackParams struct {
	DelaySeconds float64
	LastError    *string
	ID           int64
	Deliveries   int32
}

func (q *Queries) RetryCallback(ctx context.Context, arg RetryCallbackParams) error {
	_, err := q.db.Exec(ctx, retryCallback,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.Deliveries,
	)
	return err
}
