{{- if .Values.tcpIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lazycloud.fullname" . }}-tcp-ingress
  labels:
    {{- include "lazycloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: tcp-ingress
    {{- with .Values.tcpIngress.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.tcpIngress.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.tcpIngress.service.type }}
  selector:
    {{- include "lazycloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: tcp-ingress
      port: {{ .Values.tcpIngress.port }}
      targetPort: tcp-ingress
      protocol: TCP
{{- end }}
