# JuiceFS Storage Classes for Hetzner

storageClasses:
  juicefsStandard:
    enabled: true
    name: juicefs-standard
    isDefault: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

  juicefsShared:
    enabled: true
    name: juicefs-shared
    isDefault: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
