apiVersion: v2
name: prefect
description: Self-hosted Prefect Server using official Helm chart
type: application
version: 0.1.0
appVersion: "3.0"

dependencies:
  - name: prefect-server
    version: "2025.11.24182903"
    repository: "https://prefecthq.github.io/prefect-helm"
