// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: containers.sql

package execution

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStartFailure = `-- name: CountStartFailure :one
update releases set start_failures = start_failures + 1 where id = $1 returning start_failures
`

func (q *Queries) CountStartFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countStartFailure, id)
	var start_failures int32
	err := row.Scan(&start_failures)
	return start_failures, err
}

const failQueuedTasksOfRelease = `-- name: FailQueuedTasksOfRelease :many
update tasks
set status = 'failed', failure = $1, finished_at = now()
where id = any($2::uuid[]) and status = 'queued'
returning id
`

type FailQueuedTasksOfReleaseParams struct {
	Failure []byte
	Ids     []uuid.UUID
}

// The caller holds the rows from LockQueuedWithDependents.
func (q *Queries) FailQueuedTasksOfRelease(ctx context.Context, arg FailQueuedTasksOfReleaseParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, failQueuedTasksOfRelease, arg.Failure, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContainer = `-- name: LockContainer :one
select id, release_id, image_build_id, state, host_id from containers where id = $1 for update
`

type LockContainerRow struct {
	ID           uuid.UUID
	ReleaseID    *uuid.UUID
	ImageBuildID *uuid.UUID
	State        string
	HostID       *uuid.UUID
}

func (q *Queries) LockContainer(ctx context.Context, id uuid.UUID) (LockContainerRow, error) {
	row := q.db.QueryRow(ctx, lockContainer, id)
	var i LockContainerRow
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ImageBuildID,
		&i.State,
		&i.HostID,
	)
	return i, err
}

const lockStoppedReleases = `-- name: LockStoppedReleases :many
select r.id, r.start_failures, r.load_error, last_stop.stopped_at, coalesce(last_stop.reason, '')::text as reason
from releases r
left join lateral (
    select lc.stopped_at, coalesce(nullif(lc.exit_message, ''), lc.stop_reason)::text as reason
    from containers lc
    where lc.release_id = r.id and lc.purpose = 'serve'
    order by lc.id desc limit 1
) last_stop on true
where r.id = any($1::uuid[]) and (r.load_error is not null or r.start_failures >= $2::int)
order by r.id
for update of r
`

type LockStoppedReleasesParams struct {
	Ids               []uuid.UUID
	StartFailureLimit int32
}

type LockStoppedReleasesRow struct {
	ID            uuid.UUID
	StartFailures int32
	LoadError     *string
	StoppedAt     *time.Time
	Reason        string
}

// The releases among the ids that stopped starting, on a load error or
// the start failure limit, locked, with when and why their newest serve
// container stopped.
func (q *Queries) LockStoppedReleases(ctx context.Context, arg LockStoppedReleasesParams) ([]LockStoppedReleasesRow, error) {
	rows, err := q.db.Query(ctx, lockStoppedReleases, arg.Ids, arg.StartFailureLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockStoppedReleasesRow
	for rows.Next() {
		var i LockStoppedReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.StartFailures,
			&i.LoadError,
			&i.StoppedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoadError = `-- name: RecordLoadError :exec
update releases set load_error = $1 where id = $2
`

type RecordLoadErrorParams struct {
	LoadError *string
	ID        uuid.UUID
}

func (q *Queries) RecordLoadError(ctx context.Context, arg RecordLoadErrorParams) error {
	_, err := q.db.Exec(ctx, recordLoadError, arg.LoadError, arg.ID)
	return err
}

const retryReleaseStarts = `-- name: RetryReleaseStarts :exec
update releases set start_failures = $1, load_error = null where id = any($2::uuid[])
`

type RetryReleaseStartsParams struct {
	StartFailures int32
	Ids           []uuid.UUID
}

func (q *Queries) RetryReleaseStarts(ctx context.Context, arg RetryReleaseStartsParams) error {
	_, err := q.db.Exec(ctx, retryReleaseStarts, arg.StartFailures, arg.Ids)
	return err
}

const runningAttemptsOnContainer = `-- name: RunningAttemptsOnContainer :many
select id from attempts where container_id = $1 and state = 'running' order by id
`

func (q *Queries) RunningAttemptsOnContainer(ctx context.Context, containerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, runningAttemptsOnContainer, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopContainer = `-- name: StopContainer :exec
update containers
set state = 'stopped', stop_reason = $1, exit_message = $2, exit_code = $3,
    stopped_at = now()
where id = $4
`

type StopContainerParams struct {
	StopReason  *string
	ExitMessage *string
	ExitCode    *int32
	ID          uuid.UUID
}

func (q *Queries) StopContainer(ctx context.Context, arg StopContainerParams) error {
	_, err := q.db.Exec(ctx, stopContainer,
		arg.StopReason,
		arg.ExitMessage,
		arg.ExitCode,
		arg.ID,
	)
	return err
}
