{{- if .Values.limitRange.enabled }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
spec:
  limits:
  - type: Container
    {{- with .Values.limitRange.limits }}
    {{- if .default }}
    default:
      {{- toYaml .default | nindent 6 }}
    {{- end }}
    {{- if .defaultRequest }}
    defaultRequest:
      {{- toYaml .defaultRequest | nindent 6 }}
    {{- end }}
    {{- if .max }}
    max:
      {{- toYaml .max | nindent 6 }}
    {{- end }}
    {{- if .min }}
    min:
      {{- toYaml .min | nindent 6 }}
    {{- end }}
    {{- end }}
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
    min:
      storage: 1Gi
{{- end }}