{{- if .Values.storageClasses.juicefsShared.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.juicefsShared.name }}
  {{- if .Values.storageClasses.juicefsShared.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
reclaimPolicy: {{ .Values.storageClasses.juicefsShared.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClasses.juicefsShared.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClasses.juicefsShared.allowVolumeExpansion }}
{{- end }}
