# Reloader values
# Automatically restarts pods when ConfigMaps or Secrets change

reloader:
  reloader:
    watchGlobally: true
    nodeSelector:
      instance-class: platform
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
