// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet.sql

package compute

import (
	"context"
	"time"

	"github.com/AmbientWare/lazycloud/internal/cpu"
	"github.com/google/uuid"
)

const cancelConnectionLaunches = `-- name: CancelConnectionLaunches :exec
update hosts h
set phase = 'deleted', phase_message = 'Removed', phase_at = now(), state = 'retired', updated_at = now()
from cloud_connections cc
where cc.id = h.connection_id and cc.phase = 'disconnect_draining' and h.phase = 'requested'
  and (h.launch_lease_until is null or h.launch_lease_until < now())
`

// A disconnecting account buys nothing more.
func (q *Queries) CancelConnectionLaunches(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cancelConnectionLaunches)
	return err
}

const claimLaunches = `-- name: ClaimLaunches :many
update hosts h
set launch_lease_until = now() + make_interval(secs => $1::float8),
    launch_attempts = launch_attempts + 1, updated_at = now()
where h.id in (
    select r.id from hosts r
    where r.provider = 'aws' and r.phase = 'requested'
      and (r.launch_lease_until is null or r.launch_lease_until < now())
    order by r.created_at
    limit $2
    for update skip locked
)
returning h.id, h.kind, h.connection_id, h.region, h.availability_zone, h.instance_type, h.market, h.gpu_type,
          h.gpu_count, h.cpu_millis, h.memory_bytes, h.launch_attempts, h.launch_pools, h.reserve_mode
`

type ClaimLaunchesParams struct {
	LeaseSeconds float64
	BatchSize    int32
}

type ClaimLaunchesRow struct {
	ID               uuid.UUID
	Kind             string
	ConnectionID     *uuid.UUID
	Region           string
	AvailabilityZone string
	InstanceType     string
	Market           *string
	GpuType          string
	GpuCount         int32
	CpuMillis        cpu.Millis
	MemoryBytes      int64
	LaunchAttempts   int32
	LaunchPools      int16
	ReserveMode      *string
}

// Requested hosts whose launch is not held by another launcher. The lease
// outlasts one RunInstances call; a launcher that dies leaves it to expire.
func (q *Queries) ClaimLaunches(ctx context.Context, arg ClaimLaunchesParams) ([]ClaimLaunchesRow, error) {
	rows, err := q.db.Query(ctx, claimLaunches, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimLaunchesRow
	for rows.Next() {
		var i ClaimLaunchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ConnectionID,
			&i.Region,
			&i.AvailabilityZone,
			&i.InstanceType,
			&i.Market,
			&i.GpuType,
			&i.GpuCount,
			&i.CpuMillis,
			&i.MemoryBytes,
			&i.LaunchAttempts,
			&i.LaunchPools,
			&i.ReserveMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimTerminations = `-- name: ClaimTerminations :many
update hosts h
set phase = 'terminating', phase_message = 'Shutting down', phase_at = now(), state = 'retired',
    token_hash = null, updated_at = now()
where h.provider = 'aws' and h.phase = 'draining' and h.instance_id is not null
  and not exists (select 1 from containers c where c.host_id = h.id and c.state <> 'stopped')
returning h.id, h.connection_id, h.region, h.instance_id
`

type ClaimTerminationsRow struct {
	ID           uuid.UUID
	ConnectionID *uuid.UUID
	Region       string
	InstanceID   *string
}

// Draining cloud hosts that run nothing move to terminating.
func (q *Queries) ClaimTerminations(ctx context.Context) ([]ClaimTerminationsRow, error) {
	rows, err := q.db.Query(ctx, claimTerminations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimTerminationsRow
	for rows.Next() {
		var i ClaimTerminationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Region,
			&i.InstanceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionScope = `-- name: ConnectionScope :one
select a.id as authorization_id, a.role_arn, a.external_id, a.networks, a.node_instance_profile,
       a.node_role_arn, cc.phase
from cloud_connections cc
join cloud_authorizations a on a.connection_id = cc.id and a.slot = 'active'
where cc.id = $1
`

type ConnectionScopeRow struct {
	AuthorizationID     uuid.UUID
	RoleArn             string
	ExternalID          string
	Networks            []byte
	NodeInstanceProfile *string
	NodeRoleArn         *string
	Phase               string
}

func (q *Queries) ConnectionScope(ctx context.Context, id uuid.UUID) (ConnectionScopeRow, error) {
	row := q.db.QueryRow(ctx, connectionScope, id)
	var i ConnectionScopeRow
	err := row.Scan(
		&i.AuthorizationID,
		&i.RoleArn,
		&i.ExternalID,
		&i.Networks,
		&i.NodeInstanceProfile,
		&i.NodeRoleArn,
		&i.Phase,
	)
	return i, err
}

const drainConnectionHosts = `-- name: DrainConnectionHosts :many
update hosts h
set phase = 'draining', capacity_state = 'draining', capacity_reason = 'disconnecting',
    phase_message = 'Draining; no new work is placed here', phase_at = now(), updated_at = now()
from cloud_connections cc
where cc.id = h.connection_id and cc.phase = 'disconnect_draining' and h.phase in ('ready', 'joining')
returning h.id
`

// A disconnecting account's hosts stop taking work.
func (q *Queries) DrainConnectionHosts(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, drainConnectionHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failHost = `-- name: FailHost :execrows
update hosts
set phase = 'failed', failure = $1, phase_message = $2, phase_at = now(), state = 'retired',
    token_hash = null, launch_lease_until = null, updated_at = now()
where id = $3 and phase = $4
`

type FailHostParams struct {
	Failure   *string
	Message   string
	ID        uuid.UUID
	FromPhase string
}

// Fails a host still in the phase its caller read.
func (q *Queries) FailHost(ctx context.Context, arg FailHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, failHost,
		arg.Failure,
		arg.Message,
		arg.ID,
		arg.FromPhase,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fleetHostsInRegion = `-- name: FleetHostsInRegion :many
select id, phase, state, instance_id, launched_at, last_seen_at, phase_at, updating_until, stop_requested_at
from hosts
where provider = 'aws' and region = $1
  and connection_id is not distinct from $2::uuid
  and phase not in ('deleted', 'failed', 'requested')
order by id
`

type FleetHostsInRegionParams struct {
	Region       string
	ConnectionID *uuid.UUID
}

type FleetHostsInRegionRow struct {
	ID              uuid.UUID
	Phase           string
	State           string
	InstanceID      *string
	LaunchedAt      *time.Time
	LastSeenAt      *time.Time
	PhaseAt         time.Time
	UpdatingUntil   *time.Time
	StopRequestedAt *time.Time
}

// Cloud hosts of one owner and region the provider should know about.
func (q *Queries) FleetHostsInRegion(ctx context.Context, arg FleetHostsInRegionParams) ([]FleetHostsInRegionRow, error) {
	rows, err := q.db.Query(ctx, fleetHostsInRegion, arg.Region, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetHostsInRegionRow
	for rows.Next() {
		var i FleetHostsInRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.State,
			&i.InstanceID,
			&i.LaunchedAt,
			&i.LastSeenAt,
			&i.PhaseAt,
			&i.UpdatingUntil,
			&i.StopRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fleetRegions = `-- name: FleetRegions :many
select distinct connection_id, region from hosts
where provider = 'aws' and phase not in ('deleted', 'failed', 'requested') and region <> ''
`

type FleetRegionsRow struct {
	ConnectionID *uuid.UUID
	Region       string
}

// Owner and region pairs with cloud hosts to reconcile.
func (q *Queries) FleetRegions(ctx context.Context) ([]FleetRegionsRow, error) {
	rows, err := q.db.Query(ctx, fleetRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetRegionsRow
	for rows.Next() {
		var i FleetRegionsRow
		if err := rows.Scan(&i.ConnectionID, &i.Region); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hostWaiters = `-- name: HostWaiters :many
select coalesce(r.spec -> 'placement' ->> 'region', '')::text as region,
       coalesce(r.spec -> 'placement' ->> 'availability_zone', '')::text as zone,
       coalesce((r.spec -> 'placement' ->> 'preemptible')::boolean, true)::bool as preemptible
from containers c
left join releases r on r.id = c.release_id
where c.state = 'pending' and c.capacity_host_id = $1
`

type HostWaitersRow struct {
	Region      string
	Zone        string
	Preemptible bool
}

// The placement each pending container waiting for a host asks for. A
// build has no release and takes any region on Spot.
func (q *Queries) HostWaiters(ctx context.Context, hostID *uuid.UUID) ([]HostWaitersRow, error) {
	rows, err := q.db.Query(ctx, hostWaiters, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostWaitersRow
	for rows.Next() {
		var i HostWaitersRow
		if err := rows.Scan(&i.Region, &i.Zone, &i.Preemptible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCooldown = `-- name: InsertCooldown :exec
insert into capacity_cooldowns (connection_key, region, instance_type, market, until, reason, refused_at)
values ($1, $2, $3, $4, now() + make_interval(secs => $5::float8), $6, now())
on conflict (connection_key, region, instance_type, market)
do update set until = excluded.until, reason = excluded.reason, refused_at = excluded.refused_at
`

type InsertCooldownParams struct {
	ConnectionKey string
	Region        string
	InstanceType  string
	Market        string
	Seconds       float64
	Reason        string
}

func (q *Queries) InsertCooldown(ctx context.Context, arg InsertCooldownParams) error {
	_, err := q.db.Exec(ctx, insertCooldown,
		arg.ConnectionKey,
		arg.Region,
		arg.InstanceType,
		arg.Market,
		arg.Seconds,
		arg.Reason,
	)
	return err
}

const knownHostIDs = `-- name: KnownHostIDs :many
select id from hosts where id = any($1::uuid[]) and phase not in ('deleted', 'failed')
`

// Which of these hosts still exist and are not failed or deleted.
func (q *Queries) KnownHostIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, knownHostIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const launchCooldowns = `-- name: LaunchCooldowns :many
select region, instance_type, market, until, refused_at
from capacity_cooldowns
where connection_key = $1
  and (until > now() or refused_at > now() - make_interval(secs => $2::float8))
`

type LaunchCooldownsParams struct {
	ConnectionKey string
	WindowSeconds float64
}

type LaunchCooldownsRow struct {
	Region       string
	InstanceType string
	Market       string
	Until        time.Time
	RefusedAt    *time.Time
}

// One owner's offers cooling now, and refusals recent enough to cool their
// region.
func (q *Queries) LaunchCooldowns(ctx context.Context, arg LaunchCooldownsParams) ([]LaunchCooldownsRow, error) {
	rows, err := q.db.Query(ctx, launchCooldowns, arg.ConnectionKey, arg.WindowSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LaunchCooldownsRow
	for rows.Next() {
		var i LaunchCooldownsRow
		if err := rows.Scan(
			&i.Region,
			&i.InstanceType,
			&i.Market,
			&i.Until,
			&i.RefusedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managedConnectionNetworks = `-- name: ManagedConnectionNetworks :many
select cc.id, a.networks
from cloud_connections cc
join cloud_authorizations a on a.connection_id = cc.id and a.slot = 'active' and a.phase = 'ready'
where cc.phase not in ('awaiting_authorization', 'validating')
`

type ManagedConnectionNetworksRow struct {
	ID       uuid.UUID
	Networks []byte
}

// Connections whose account may still hold fleet instances, with the
// networks of their active authorization.
func (q *Queries) ManagedConnectionNetworks(ctx context.Context) ([]ManagedConnectionNetworksRow, error) {
	rows, err := q.db.Query(ctx, managedConnectionNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagedConnectionNetworksRow
	for rows.Next() {
		var i ManagedConnectionNetworksRow
		if err := rows.Scan(&i.ID, &i.Networks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostDeleted = `-- name: MarkHostDeleted :execrows
update hosts
set phase = 'deleted', phase_message = 'Removed', phase_at = now(), state = 'retired', token_hash = null, updated_at = now()
where id = $1 and phase = $2
`

type MarkHostDeletedParams struct {
	ID        uuid.UUID
	FromPhase string
}

// Deletes a host still in the phase its caller read.
func (q *Queries) MarkHostDeleted(ctx context.Context, arg MarkHostDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markHostDeleted, arg.ID, arg.FromPhase)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveLaunchPool = `-- name: MoveLaunchPool :execrows
update hosts
set instance_type = $1, region = $2, availability_zone = $3,
    availability_zone_id = $4, cpu_millis = $5, memory_bytes = $6,
    gpu_count = $7, hourly_micros = $8, launch_pools = launch_pools + 1, updated_at = now()
where id = $9 and phase = 'requested'
`

type MoveLaunchPoolParams struct {
	InstanceType       string
	Region             string
	AvailabilityZone   string
	AvailabilityZoneID string
	CpuMillis          cpu.Millis
	MemoryBytes        int64
	GpuCount           int32
	HourlyMicros       *int64
	ID                 uuid.UUID
}

// Moves a requested host whose pool EC2 refused to the next pool, with
// that pool's capacity and cost.
func (q *Queries) MoveLaunchPool(ctx context.Context, arg MoveLaunchPoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveLaunchPool,
		arg.InstanceType,
		arg.Region,
		arg.AvailabilityZone,
		arg.AvailabilityZoneID,
		arg.CpuMillis,
		arg.MemoryBytes,
		arg.GpuCount,
		arg.HourlyMicros,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordLaunch = `-- name: RecordLaunch :execrows
update hosts
set instance_id = $1, availability_zone = $2, availability_zone_id = $3,
    phase = 'provisioning', phase_message = 'Instance is starting; waiting for the node to report', phase_at = now(),
    launched_at = now(), launch_lease_until = null, updated_at = now(),
    authorization_id = $4, node_role_arn = $5,
    spot_request_id = $6, node_image = $7,
    hibernation_configured = $8
where id = $9 and phase = 'requested'
`

type RecordLaunchParams struct {
	InstanceID            *string
	AvailabilityZone      string
	AvailabilityZoneID    string
	AuthorizationID       *uuid.UUID
	NodeRoleArn           *string
	SpotRequestID         *string
	NodeImage             *string
	HibernationConfigured bool
	ID                    uuid.UUID
}

func (q *Queries) RecordLaunch(ctx context.Context, arg RecordLaunchParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordLaunch,
		arg.InstanceID,
		arg.AvailabilityZone,
		arg.AvailabilityZoneID,
		arg.AuthorizationID,
		arg.NodeRoleArn,
		arg.SpotRequestID,
		arg.NodeImage,
		arg.HibernationConfigured,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reportedMemory = `-- name: ReportedMemory :many
select instance_type, min(memory_bytes)::bigint as memory_bytes
from hosts
where provider = 'aws' and phase not in ('deleted', 'failed') and session_epoch > 0 and instance_type <> ''
group by instance_type
`

type ReportedMemoryRow struct {
	InstanceType string
	MemoryBytes  int64
}

// The least memory live hosts of each type reported.
func (q *Queries) ReportedMemory(ctx context.Context) ([]ReportedMemoryRow, error) {
	rows, err := q.db.Query(ctx, reportedMemory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportedMemoryRow
	for rows.Next() {
		var i ReportedMemoryRow
		if err := rows.Scan(&i.InstanceType, &i.MemoryBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostPhase = `-- name: SetHostPhase :execrows
update hosts
set phase = $1, phase_message = $2, phase_at = now(), updated_at = now()
where id = $3 and phase = $4
`

type SetHostPhaseParams struct {
	Phase     string
	Message   string
	ID        uuid.UUID
	FromPhase string
}

func (q *Queries) SetHostPhase(ctx context.Context, arg SetHostPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setHostPhase,
		arg.Phase,
		arg.Message,
		arg.ID,
		arg.FromPhase,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
