// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interruptions.sql

package compute

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const duePreemptions = `-- name: DuePreemptions :many
select id from hosts
where interruption_at is not null
  and interruption_at <= now() + make_interval(secs => $1::float8)
  and capacity_state = 'preempting' and phase = 'draining'
order by interruption_at, id
limit $2
`

type DuePreemptionsParams struct {
	LeadSeconds float64
	BatchSize   int32
}

// Interrupted hosts whose reclaim time is near and that have not been
// preempted yet.
func (q *Queries) DuePreemptions(ctx context.Context, arg DuePreemptionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, duePreemptions, arg.LeadSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHost = `-- name: LockHost :one
select id, phase, state, interruption_at from hosts where id = $1 for update
`

type LockHostRow struct {
	ID             uuid.UUID
	Phase          string
	State          string
	InterruptionAt *time.Time
}

func (q *Queries) LockHost(ctx context.Context, id uuid.UUID) (LockHostRow, error) {
	row := q.db.QueryRow(ctx, lockHost, id)
	var i LockHostRow
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.State,
		&i.InterruptionAt,
	)
	return i, err
}

const markInterrupted = `-- name: MarkInterrupted :exec
update hosts
set phase = case when phase in ('ready', 'joining') then 'draining' else phase end,
    phase_message = $1, phase_at = now(),
    capacity_state = 'preempting', capacity_reason = $2,
    interruption_at = $3, updated_at = now()
where id = $4
`

type MarkInterruptedParams struct {
	Message   string
	Reason    string
	ReclaimAt *time.Time
	ID        uuid.UUID
}

// The host takes no new work from now on and is preempted before reclaim_at.
func (q *Queries) MarkInterrupted(ctx context.Context, arg MarkInterruptedParams) error {
	_, err := q.db.Exec(ctx, markInterrupted,
		arg.Message,
		arg.Reason,
		arg.ReclaimAt,
		arg.ID,
	)
	return err
}

const markPreempted = `-- name: MarkPreempted :execrows
update hosts
set phase = 'terminating', phase_message = 'Reclaimed by the provider', phase_at = now(), updated_at = now()
where id = $1 and phase = 'draining' and capacity_state = 'preempting'
`

func (q *Queries) MarkPreempted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPreempted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
