{{/*
Create Secrets for each secret defined
*/}}
{{- range $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lazycloud-compose.sanitizeName" $secret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "lazycloud-compose.labels" $ | nindent 4 }}
    app.kubernetes.io/component: secret
    lazycloud.dev/secret: {{ $secret.name }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "lazycloud-compose.annotations" $ | nindent 4 }}
    {{- if $secret.annotations }}
    {{- toYaml $secret.annotations | nindent 4 }}
    {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- if $secret.data }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}