apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
