nameOverride: argocd
fullnameOverride: argocd

server:
  # Run in insecure mode - Cloudflare handles TLS termination
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.lazycloud.dev
    annotations: {}
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  metrics:
    enabled: true

controller:
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  metrics:
    enabled: true

dex:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

redis:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

repoServer:
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  metrics:
    enabled: true

applicationSet:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

notifications:
  enabled: false

configs:
  cm:
    users.anonymous.enabled: "false"
    helm.enableOCI: "true"
