# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from enum import Enum
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Base64Bytes, BaseModel, Field, RootModel
from uuid import UUID


class ErrorCode(str, Enum):
    invalid_request = "invalid_request"
    unauthenticated = "unauthenticated"
    forbidden = "forbidden"
    not_found = "not_found"
    conflict = "conflict"
    payload_too_large = "payload_too_large"
    unsupported = "unsupported"
    too_many_pending_tasks = "too_many_pending_tasks"
    task_not_finished = "task_not_finished"
    internal = "internal"


class WorkloadName(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]


class User(BaseModel):
    id: UUID
    email: str


class Workspace(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{0,62}$")]


class SourceUploadRequest(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]
    size_bytes: Annotated[int, Field(ge=1, le=536870912)]


class UploadTarget(BaseModel):
    url: Annotated[str, Field(description="Absolute URL; the request carries no bearer token.")]
    method: Literal["PUT"]
    headers: dict[str, str]
    expires_at: AwareDatetime


class SourceRef(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]


class PythonVersion(str, Enum):
    field_3_10 = "3.10"
    field_3_11 = "3.11"
    field_3_12 = "3.12"
    field_3_13 = "3.13"
    field_3_14 = "3.14"


class ImageSpec(BaseModel):
    python_version: PythonVersion


class Resources(BaseModel):
    cpu_millis: Annotated[int, Field(ge=125, le=192000)]
    cpu_limit_millis: Annotated[int | None, Field(ge=125, le=192000)] = None
    memory_mib: Annotated[int, Field(ge=128, le=1572864)]
    memory_limit_mib: Annotated[int | None, Field(ge=128, le=1572864)] = None


class Backoff(str, Enum):
    fixed = "fixed"
    exponential = "exponential"


class RetryPolicy(BaseModel):
    max_attempts: Annotated[int, Field(description="Attempts including the first.", ge=1, le=100)]
    delay_seconds: Annotated[float, Field(ge=0.0, le=3600.0)] = 0
    backoff: Backoff = Backoff.fixed
    max_delay_seconds: Annotated[float | None, Field(ge=0.0, le=86400.0)] = None


class Autoscaler(BaseModel):
    min_containers: Annotated[int, Field(ge=0, le=1000)] = 0
    max_containers: Annotated[int, Field(ge=1, le=1000)] = 1
    tasks_per_container: Annotated[int, Field(ge=1, le=10000)] = 1


class State(str, Enum):
    active = "active"
    stopped = "stopped"


class Encoding(str, Enum):
    json = "json"
    cloudpickle = "cloudpickle"


class Payload(BaseModel):
    encoding: Encoding
    value: Any | None = None
    data: Base64Bytes | None = None


class TaskInput(Payload):
    depends_on: Annotated[list[UUID] | None, Field(max_length=100)] = None


class TaskStatus(str, Enum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class TaskPendingReason(str, Enum):
    Queued = "queued"
    Dependencies = "dependencies"
    Retry = "retry"
    CapacityBusy = "capacity_busy"
    CapacityUnavailable = "capacity_unavailable"
    CapacityLimit = "capacity_limit"
    ProvisioningCompute = "provisioning_compute"
    StartingContainer = "starting_container"


class FailureKind(str, Enum):
    user_error = "user_error"
    load_error = "load_error"
    timeout = "timeout"
    lost = "lost"
    start_failed = "start_failed"
    system = "system"
    dependency_failed = "dependency_failed"


class TaskFailure(BaseModel):
    kind: FailureKind
    type: Annotated[str | None, Field(description="The exception type the handler raised.")] = None
    message: str
    traceback: str | None = None
    exception: Annotated[
        Base64Bytes | None,
        Field(description="The cloudpickled exception, when the runner could serialize it."),
    ] = None


class Stream(str, Enum):
    stdout = "stdout"
    stderr = "stderr"
    system = "system"


class LogEntry(BaseModel):
    id: int
    task_id: UUID
    attempt: int
    stream: Stream
    data: Annotated[str, Field(description="One line of output without its trailing newline.")]
    time: AwareDatetime


class AppRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="An app name or id.",
            pattern="^([a-z][a-z0-9_]{0,62}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
        ),
    ]


class AppState(str, Enum):
    active = "active"
    paused = "paused"
    deleted = "deleted"


class LiveAppState(str, Enum):
    active = "active"
    paused = "paused"


class WorkloadState(str, Enum):
    active = "active"
    stopped = "stopped"
    deleted = "deleted"


class DeploymentPlanAction(str, Enum):
    add = "add"
    redeploy = "redeploy"
    retain = "retain"
    remove = "remove"


class WorkloadIdentity(BaseModel):
    kind: Literal["function"]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]


class DeploymentPlanItem(BaseModel):
    kind: Literal["function"]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    action: DeploymentPlanAction
    versions: Annotated[int, Field(description="Versions the workload has now.")]


class DeployedWorkload(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    kind: Literal["function"]
    state: WorkloadState
    app_state: AppState | None = None
    version: Annotated[int | None, Field(description="The active version.")] = None
    release_id: Annotated[UUID | None, Field(description="The active release.")] = None
    created_at: AwareDatetime
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="When the active version was deployed.")
    ] = None


class DeploymentPage(BaseModel):
    deployments: list[DeployedWorkload]
    next_cursor: str | None = None


class StartDeploymentRequest(BaseModel):
    version: Annotated[
        int | None, Field(description="Make this deployed version active before starting.", ge=1)
    ] = None


class Version(BaseModel):
    release_id: UUID
    version: int
    active: bool
    created_at: AwareDatetime


class VersionPage(BaseModel):
    versions: list[Version]
    next_cursor: str | None = None


class StopTasksRequest(BaseModel):
    task_ids: Annotated[list[UUID], Field(max_length=1000, min_length=1)]


class StopTasksResponse(BaseModel):
    stopped: Annotated[list[UUID], Field(description="Tasks this request cancelled.")]
    skipped: Annotated[
        list[UUID],
        Field(description="Tasks that were already finished or are not in the workspace."),
    ]


class ContainerState(str, Enum):
    pending = "pending"
    starting = "starting"
    ready = "ready"
    draining = "draining"
    stopped = "stopped"


class StopReason(str, Enum):
    stopped = "stopped"
    load_error = "load_error"
    start_failed = "start_failed"
    crashed = "crashed"
    out_of_memory = "out_of_memory"
    host_lost = "host_lost"


class Container(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    release_id: UUID
    version: Annotated[
        int | None,
        Field(
            description="The deployed version of the release; absent for a working-tree release."
        ),
    ] = None
    state: ContainerState
    stop_reason: StopReason | None = None
    exit_message: str | None = None
    slots: int
    running_tasks: Annotated[int, Field(description="Attempts running now.")]
    cpu_millis: int
    memory_mib: int
    created_at: AwareDatetime
    ready_at: AwareDatetime | None = None
    stopped_at: AwareDatetime | None = None


class ContainerPage(BaseModel):
    containers: list[Container]
    next_cursor: str | None = None


class Error(BaseModel):
    code: ErrorCode
    message: str


class Me(BaseModel):
    user: User
    workspaces: list[Workspace]


class SourceUpload(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]
    present: Annotated[bool, Field(description="The archive is stored and can be deployed.")]
    upload: UploadTarget | None = None


class App(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    state: AppState
    workloads: Annotated[int, Field(description="Deployed workloads that are not deleted.")]
    created_at: AwareDatetime


class FunctionSpec(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    handler: Annotated[
        str,
        Field(
            description="module:qualname within the source archive",
            pattern="^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*$",
        ),
    ]
    source: SourceRef
    image: ImageSpec
    resources: Resources
    timeout_seconds: Annotated[int, Field(ge=1, le=86400)] = 3600
    retry_policy: RetryPolicy | None = None
    concurrency: Annotated[
        int,
        Field(description="Tasks one container runs at once, one process per slot.", ge=1, le=256),
    ] = 1
    keep_warm_seconds: Annotated[
        int,
        Field(description="Idle time before a container above the minimum stops.", ge=0, le=86400),
    ] = 10
    autoscaler: Autoscaler | None = None
    max_pending_tasks: Annotated[int, Field(ge=1, le=1000000)] = 100
    environment: dict[str, str] | None = None
    client_contract: Annotated[
        dict[str, Any] | None,
        Field(
            description="The handler's call signature as the SDK describes it, for typed clients that `lazycloud app export` generates. Opaque to the platform."
        ),
    ] = None


class Release(BaseModel):
    id: UUID
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    version: Annotated[
        int | None,
        Field(
            description="The deployed version; absent for a release only working-tree calls use."
        ),
    ] = None
    created_at: AwareDatetime
    spec: FunctionSpec


class Function(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    state: State
    active_release: Release


class SubmitTasksRequest(BaseModel):
    inputs: Annotated[list[TaskInput], Field(max_length=1000, min_length=1)]
    release_id: Annotated[
        UUID | None,
        Field(
            description="Run on this release of the function instead of the active one, such as one from prepareFunctionRelease."
        ),
    ] = None
    parent_task_id: Annotated[
        UUID | None, Field(description="The task that submits these, which becomes their parent.")
    ] = None


class TaskPendingProgress(BaseModel):
    reason: TaskPendingReason
    message: str
    since: Annotated[AwareDatetime, Field(description="When the current reason began.")]
    pending_since: Annotated[
        AwareDatetime, Field(description="When the task last became due or was submitted.")
    ]
    observed_at: AwareDatetime


class AppPage(BaseModel):
    apps: list[App]
    next_cursor: Annotated[str | None, Field(description="Present when another page follows.")] = (
        None
    )


class DeploymentPlanRequest(BaseModel):
    workloads: Annotated[list[WorkloadIdentity], Field(max_length=200)]
    prune: bool = False


class DeploymentPlan(BaseModel):
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    prune: bool
    items: Annotated[
        list[DeploymentPlanItem],
        Field(
            description="Listed workloads by kind and name, then deployed workloads the request omits."
        ),
    ]


class DeploymentRequest(BaseModel):
    functions: Annotated[list[FunctionSpec], Field(max_length=200, min_length=1)]
    prune: Annotated[
        bool, Field(description="Delete every function of the app that is not listed.")
    ] = False


class Deployment(BaseModel):
    app: App
    releases: list[Release]
    pruned: Annotated[list[WorkloadName], Field(description="Functions the prune deleted.")]
    removed_versions: Annotated[int, Field(description="Versions of the pruned functions.")]


class Task(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    release_id: UUID
    version: Annotated[
        int | None,
        Field(
            description="The deployed version of the release; absent for a working-tree release."
        ),
    ] = None
    status: TaskStatus
    attempts: Annotated[int, Field(description="Attempts started so far.")]
    max_attempts: int
    parent_task_id: UUID | None = None
    root_task_id: Annotated[
        UUID | None,
        Field(
            description="The first task of the call graph; the task itself when it has no parent."
        ),
    ] = None
    container_id: Annotated[
        UUID | None, Field(description="The container of the latest attempt.")
    ] = None
    next_attempt_at: Annotated[
        AwareDatetime | None,
        Field(description="When a queued task that already ran becomes due again."),
    ] = None
    pending: TaskPendingProgress | None = None
    created_at: AwareDatetime
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    failure: TaskFailure | None = None


class TaskPage(BaseModel):
    tasks: list[Task]
    next_cursor: str | None = None


class SubmitTasksResponse(BaseModel):
    tasks: list[Task]
