# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from enum import Enum
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, Base64Bytes, BaseModel, Field, RootModel
from uuid import UUID
from typing_extensions import TypeAliasType


class ErrorCode(str, Enum):
    invalid_request = "invalid_request"
    unauthenticated = "unauthenticated"
    forbidden = "forbidden"
    not_found = "not_found"
    conflict = "conflict"
    payload_too_large = "payload_too_large"
    unsupported = "unsupported"
    too_many_pending_tasks = "too_many_pending_tasks"
    task_not_finished = "task_not_finished"
    unavailable = "unavailable"
    internal = "internal"
    payment_required = "payment_required"
    limit_reached = "limit_reached"


class WorkloadName(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]


class User(BaseModel):
    id: UUID
    email: Annotated[
        str, Field(description="Empty when GitHub reported no verified primary address.")
    ]
    display_name: str
    avatar_url: str
    github_login: Annotated[
        str, Field(description="Empty for accounts that have not signed in with GitHub.")
    ]
    is_admin: Annotated[bool, Field(description="Platform administrators reach every workspace.")]
    created_at: AwareDatetime


class WorkspaceState(str, Enum):
    active = "active"
    deleting = "deleting"


class WorkspaceRole(str, Enum):
    owner = "owner"
    administrator = "administrator"
    member = "member"


class WorkspaceRequest(BaseModel):
    name: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{0,62}$")]


class TokenStatus(str, Enum):
    active = "active"
    expired = "expired"


class Token(BaseModel):
    id: UUID
    name: str
    device: Annotated[bool, Field(description="Minted by `lazycloud login`.")]
    workspace_id: Annotated[
        UUID | None, Field(description="Set when the token reaches only this workspace.")
    ] = None
    status: TokenStatus
    created_at: AwareDatetime
    expires_at: Annotated[
        AwareDatetime | None, Field(description="Absent when the token never expires.")
    ] = None
    last_used_at: Annotated[
        AwareDatetime | None,
        Field(description="Recorded within 30 seconds of use; absent if never used."),
    ] = None


class TokenList(BaseModel):
    tokens: list[Token]
    next_cursor: Annotated[
        UUID | None, Field(description="Pass as `cursor` for the next page; absent after the last.")
    ] = None


class TokenCreateRequest(BaseModel):
    name: Annotated[str, Field(max_length=100, min_length=1)]
    expires_in_seconds: Annotated[
        int | None,
        Field(
            description="One to 90 days; omit for a token that never expires.", ge=86400, le=7776000
        ),
    ] = None


class CreatedToken(BaseModel):
    token: Annotated[str, Field(description="The secret; it is not shown again.")]
    record: Token


class DeviceLoginRequest(BaseModel):
    client_name: Annotated[
        str, Field(description="Names the device token, such as cli@laptop.", max_length=200)
    ] = "cli"


class DeviceLogin(BaseModel):
    device_code: Annotated[str, Field(description="The CLI's secret for polling.")]
    user_code: Annotated[
        str, Field(description="What the person confirms at the verification page.")
    ]
    verification_uri: str
    verification_uri_complete: Annotated[
        str, Field(description="The verification page with the code filled in.")
    ]
    expires_in_seconds: int
    poll_interval_seconds: int


class DeviceTokenRequest(BaseModel):
    device_code: Annotated[str, Field(max_length=200, min_length=1)]


class DeviceTokenStatus(str, Enum):
    pending = "pending"
    slow_down = "slow_down"
    approved = "approved"
    denied = "denied"
    expired = "expired"


class DeviceTokenResponse(BaseModel):
    status: DeviceTokenStatus
    token: Annotated[
        str | None,
        Field(description="The device token, on the poll that finds the login approved."),
    ] = None
    poll_interval_seconds: Annotated[
        int, Field(description="Wait at least this long before the next poll.")
    ]


class DeviceCodeStatus(str, Enum):
    pending = "pending"
    approved = "approved"
    denied = "denied"
    expired = "expired"


class DeviceCode(BaseModel):
    user_code: str
    client_name: str
    status: DeviceCodeStatus
    created_at: AwareDatetime
    expires_at: AwareDatetime


class Member(BaseModel):
    user_id: UUID
    display_name: str
    email: str
    role: WorkspaceRole
    created_at: Annotated[AwareDatetime, Field(description="When the user joined.")]


class MemberList(BaseModel):
    members: list[Member]


class InvitationRole(str, Enum):
    administrator = "administrator"
    member = "member"


class DeliveryState(str, Enum):
    queued = "queued"
    sent = "sent"
    delivered = "delivered"
    bounced = "bounced"
    complained = "complained"
    failed = "failed"
    discarded = "discarded"


class InvitationRequest(BaseModel):
    email: Annotated[str, Field(max_length=320, min_length=3)]
    role: InvitationRole = InvitationRole.member


class Invitation(BaseModel):
    id: UUID
    workspace_id: UUID
    email: str
    role: InvitationRole
    invited_by_user_id: UUID | None = None
    invited_by_name: str
    expired: Annotated[bool, Field(description="Decided by the server's clock.")]
    delivery: DeliveryState
    expires_at: AwareDatetime
    created_at: AwareDatetime
    updated_at: AwareDatetime


class InvitationList(BaseModel):
    invitations: list[Invitation]


class InvitationPreview(BaseModel):
    workspace_id: UUID
    workspace_name: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{0,62}$")]
    email: str
    role: InvitationRole
    invited_by_name: str
    expired: bool
    expires_at: AwareDatetime


class SourceUploadRequest(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]
    size_bytes: Annotated[int, Field(ge=1, le=536870912)]


class UploadTarget(BaseModel):
    url: Annotated[str, Field(description="Absolute URL; the request carries no bearer token.")]
    method: Literal["PUT"]
    headers: dict[str, str]
    expires_at: AwareDatetime


class SourceRef(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]


class PythonVersion(str, Enum):
    field_3_10 = "3.10"
    field_3_11 = "3.11"
    field_3_12 = "3.12"
    field_3_13 = "3.13"
    field_3_14 = "3.14"


class Resources(BaseModel):
    cpu_millis: Annotated[int, Field(ge=125, le=192000)]
    cpu_limit_millis: Annotated[int | None, Field(ge=125, le=192000)] = None
    memory_mib: Annotated[int, Field(ge=128, le=1572864)]
    memory_limit_mib: Annotated[int | None, Field(ge=128, le=1572864)] = None
    disk_mib: Annotated[
        int | None,
        Field(
            description="Writable layer limit; enforced where Docker has project quotas.",
            ge=1024,
            le=16777216,
        ),
    ] = None


class Backoff(str, Enum):
    fixed = "fixed"
    exponential = "exponential"


class RetryPolicy(BaseModel):
    max_attempts: Annotated[int, Field(description="Attempts including the first.", ge=1, le=100)]
    delay_seconds: Annotated[float, Field(ge=0.0, le=3600.0)] = 0
    backoff: Backoff = Backoff.fixed
    max_delay_seconds: Annotated[float | None, Field(ge=0.0, le=86400.0)] = None


class Autoscaler(BaseModel):
    min_containers: Annotated[int, Field(ge=0, le=1000)] = 0
    max_containers: Annotated[int, Field(ge=1, le=1000)] = 1
    tasks_per_container: Annotated[int, Field(ge=1, le=10000)] = 1


class State(str, Enum):
    active = "active"
    stopped = "stopped"


class Encoding(str, Enum):
    json = "json"
    cloudpickle = "cloudpickle"


class Payload(BaseModel):
    encoding: Encoding
    value: Any | None = None
    data: Base64Bytes | None = None


class TaskInput(Payload):
    depends_on: Annotated[list[UUID] | None, Field(max_length=100)] = None


class TaskStatus(str, Enum):
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class TaskPendingReason(str, Enum):
    Queued = "queued"
    Dependencies = "dependencies"
    Retry = "retry"
    CapacityBusy = "capacity_busy"
    CapacityUnavailable = "capacity_unavailable"
    CapacityLimit = "capacity_limit"
    ProvisioningCompute = "provisioning_compute"
    StartingContainer = "starting_container"


class FailureKind(str, Enum):
    user_error = "user_error"
    load_error = "load_error"
    timeout = "timeout"
    lost = "lost"
    start_failed = "start_failed"
    system = "system"
    dependency_failed = "dependency_failed"


class TaskFailure(BaseModel):
    kind: FailureKind
    type: Annotated[str | None, Field(description="The exception type the handler raised.")] = None
    message: str
    traceback: str | None = None
    exception: Annotated[
        Base64Bytes | None,
        Field(description="The cloudpickled exception, when the runner could serialize it."),
    ] = None


class Stream(str, Enum):
    stdout = "stdout"
    stderr = "stderr"
    system = "system"


class LogEntry(BaseModel):
    id: int
    task_id: UUID
    attempt: int
    stream: Stream
    data: Annotated[str, Field(description="One line of output without its trailing newline.")]
    time: AwareDatetime


class HookReference(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*$")]


class SecretName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="An environment variable name; the LAZYCLOUD_ prefix is reserved.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ]


class SecretCreate(BaseModel):
    name: Annotated[
        str,
        Field(
            description="An environment variable name; the LAZYCLOUD_ prefix is reserved.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ]
    value: Annotated[str, Field(max_length=65536)]


class SecretValueUpdate(BaseModel):
    value: Annotated[str, Field(max_length=65536)]


class Secret(BaseModel):
    name: Annotated[
        str,
        Field(
            description="An environment variable name; the LAZYCLOUD_ prefix is reserved.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SecretValue(BaseModel):
    name: Annotated[
        str,
        Field(
            description="An environment variable name; the LAZYCLOUD_ prefix is reserved.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ]
    value: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SecretPage(BaseModel):
    secrets: list[Secret]
    next_cursor: Annotated[str | None, Field(description="Present when more secrets follow.")] = (
        None
    )


class Schedule(BaseModel):
    cron: Annotated[str, Field(description="The normalized expression.")]
    timezone: Literal["UTC"]
    next_run_at: AwareDatetime
    last_run_at: Annotated[
        AwareDatetime | None, Field(description="When the last handled occurrence was due.")
    ] = None
    last_task_id: Annotated[
        UUID | None, Field(description="The task the last occurrence admitted.")
    ] = None
    last_error: Annotated[
        str | None, Field(description="Why the last occurrence admitted no task.")
    ] = None


class ScheduledFunction(BaseModel):
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    schedule: Schedule


class SchedulePage(BaseModel):
    schedules: list[ScheduledFunction]
    next_cursor: Annotated[str | None, Field(description="Present when more schedules follow.")] = (
        None
    )


class MapKey(RootModel[str]):
    root: Annotated[str, Field(max_length=1024, min_length=1, pattern="^[^\\x00-\\x1f\\x7f]+$")]


class VolumeRelativePath(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A path below the volume root; `.` or empty is the root, `..` is refused.",
            max_length=1024,
        ),
    ]


class WorkloadRef(BaseModel):
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    kind: Literal["function"]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]


class CloudBucketSpec(BaseModel):
    bucket: Annotated[str, Field(max_length=63, min_length=3)]
    prefix: Annotated[
        str,
        Field(
            description="A key prefix ending in `/`, or empty for the whole bucket.",
            max_length=1024,
        ),
    ] = ""
    region: Annotated[str | None, Field(max_length=64)] = None
    endpoint: Annotated[
        str | None,
        Field(description="An S3-compatible endpoint URL; AWS S3 when absent.", max_length=1024),
    ] = None
    force_path_style: bool = False
    access_key_secret: Annotated[
        str | None,
        Field(
            description="The workspace secret holding the access key id.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ] = None
    secret_key_secret: Annotated[
        str | None,
        Field(
            description="The workspace secret holding the secret access key.",
            pattern="^[A-Za-z_][A-Za-z0-9_]{0,239}$",
        ),
    ] = None


class Volume(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$")]
    size_bytes: Annotated[int, Field(description="Bytes stored at the last measurement.")]
    size_measured_at: AwareDatetime | None = None
    created_at: AwareDatetime
    used_by: Annotated[
        list[WorkloadRef], Field(description="Workloads whose active release mounts the volume.")
    ]


class VolumePage(BaseModel):
    volumes: list[Volume]
    next_cursor: str | None = None


class CreateVolumeRequest(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$")]


class VolumeFile(BaseModel):
    path: Annotated[str, Field(description="The path relative to the volume root.")]
    is_dir: bool
    size_bytes: int
    modified_at: Annotated[AwareDatetime | None, Field(description="Absent for directories.")] = (
        None
    )


class VolumeFilePage(BaseModel):
    files: list[VolumeFile]
    next_cursor: str | None = None


class RemovedVolumeFiles(BaseModel):
    removed: Annotated[
        list[str], Field(description="Removed file paths relative to the volume root.")
    ]


class MoveVolumeFileRequest(BaseModel):
    from_: Annotated[
        str,
        Field(
            alias="from",
            description="A file or directory below the volume root.",
            max_length=1024,
            min_length=1,
        ),
    ]
    to: Annotated[
        str,
        Field(
            description="A file or directory below the volume root.", max_length=1024, min_length=1
        ),
    ]


class Method(str, Enum):
    get = "get"
    head = "head"
    put = "put"
    upload_part = "upload_part"


class PresignVolumeFileRequest(BaseModel):
    path: Annotated[
        str,
        Field(
            description="A file or directory below the volume root.", max_length=1024, min_length=1
        ),
    ]
    method: Method
    expires_seconds: Annotated[int, Field(ge=1, le=604800)] = 3600
    upload_id: Annotated[
        str | None, Field(description="Required for `upload_part`.", max_length=1024)
    ] = None
    part_number: Annotated[
        int | None, Field(description="Required for `upload_part`.", ge=1, le=10000)
    ] = None


class PresignedUrl(BaseModel):
    url: Annotated[str, Field(description="Absolute URL; the request carries no bearer token.")]
    expires_at: AwareDatetime


class UploadPart(BaseModel):
    number: int
    offset: int
    size_bytes: int
    url: Annotated[
        str,
        Field(description="A presigned PUT of these bytes; its ETag completes a multipart upload."),
    ]


class Upload(BaseModel):
    upload_id: str | None = None
    part_size_bytes: int | None = None
    parts: list[UploadPart]
    expires_at: AwareDatetime


class CompletedPart(BaseModel):
    number: Annotated[int, Field(ge=1, le=10000)]
    etag: Annotated[str, Field(max_length=1024)]


class CreateVolumeUploadRequest(BaseModel):
    path: Annotated[
        str,
        Field(
            description="A file or directory below the volume root.", max_length=1024, min_length=1
        ),
    ]
    size_bytes: Annotated[int, Field(ge=0, le=5497558138880)]
    part_size_bytes: Annotated[int, Field(ge=5242880, le=5368709120)] = 5242880


class MultipartUpload(BaseModel):
    upload_id: str
    path: str
    part_size_bytes: int
    parts: list[UploadPart]
    expires_at: AwareDatetime


class CompleteVolumeUploadRequest(BaseModel):
    path: Annotated[
        str,
        Field(
            description="A file or directory below the volume root.", max_length=1024, min_length=1
        ),
    ]
    upload_id: Annotated[str, Field(max_length=1024)]
    parts: Annotated[list[CompletedPart], Field(max_length=10000, min_length=1)]


class AbortVolumeUploadRequest(BaseModel):
    path: Annotated[
        str,
        Field(
            description="A file or directory below the volume root.", max_length=1024, min_length=1
        ),
    ]
    upload_id: Annotated[str, Field(max_length=1024)]


class DiskStatus(str, Enum):
    detached = "detached"
    attached = "attached"
    saving = "saving"


class Disk(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")]
    size_bytes: int
    stored_bytes: Annotated[
        int, Field(description="Bytes the disk's published generations occupy in the object store.")
    ]
    generation: Annotated[
        int, Field(description="The newest published generation; 0 before the first.")
    ]
    status: DiskStatus
    holder_container_id: Annotated[
        UUID | None, Field(description="The container holding the disk while attached or saving.")
    ] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DiskPage(BaseModel):
    disks: list[Disk]
    next_cursor: str | None = None


class State1(str, Enum):
    uploading = "uploading"
    stored = "stored"


class Artifact(BaseModel):
    id: UUID
    task_id: UUID | None = None
    app: Annotated[str | None, Field(pattern="^[a-z][a-z0-9_]{0,62}$")] = None
    filename: str
    content_type: str
    size_bytes: int
    state: State1
    created_at: AwareDatetime
    stored_at: AwareDatetime | None = None
    expires_at: AwareDatetime | None = None


class ArtifactPage(BaseModel):
    artifacts: list[Artifact]
    next_cursor: str | None = None


class CreateArtifactRequest(BaseModel):
    task_id: UUID
    filename: Annotated[
        str, Field(description="A base name without `/`.", pattern="^[^/\\x00-\\x1f\\x7f]{1,255}$")
    ]
    content_type: Annotated[str, Field(max_length=255, min_length=1)] = "application/octet-stream"
    size_bytes: Annotated[int, Field(ge=0, le=5497558138880)]


class ArtifactUpload(BaseModel):
    artifact: Artifact
    upload: Upload


class CompleteArtifactRequest(BaseModel):
    parts: Annotated[
        list[CompletedPart] | None,
        Field(description="The ETag of every part of a multipart upload.", max_length=10000),
    ] = None


class PresignArtifactRequest(BaseModel):
    expires_seconds: Annotated[
        int, Field(description="Capped at the artifact's remaining retention.", ge=1, le=604800)
    ] = 3600
    download: Annotated[
        bool, Field(description="Ask browsers to save the file rather than show it.")
    ] = False


class ArtifactSummary(BaseModel):
    count: int
    size_bytes: int
    retention_seconds: Annotated[
        int, Field(description="How long new artifacts are kept under the workspace's plan.")
    ]


class DeleteArtifactsRequest(BaseModel):
    ids: Annotated[list[UUID], Field(max_length=100, min_length=1)]


class DeletedArtifacts(BaseModel):
    deleted: list[UUID]


class QueueInfo(BaseModel):
    name: Annotated[
        str,
        Field(
            description="A queue or map name; any characters except control characters.",
            pattern="^[^\\x00-\\x1f\\x7f]{1,255}$",
        ),
    ]
    size: int
    oldest_message_at: AwareDatetime | None = None


class QueuePage(BaseModel):
    queues: list[QueueInfo]
    next_cursor: str | None = None


class PutQueueMessagesRequest(BaseModel):
    messages: Annotated[
        list[Base64Bytes],
        Field(
            description="Message bodies, base64; each at most 1 MiB.", max_length=1000, min_length=1
        ),
    ]


class QueueMessageResult(BaseModel):
    message: Base64Bytes | None = None


class MapInfo(BaseModel):
    name: Annotated[
        str,
        Field(
            description="A queue or map name; any characters except control characters.",
            pattern="^[^\\x00-\\x1f\\x7f]{1,255}$",
        ),
    ]
    count: int
    size_bytes: int
    expiring_count: int
    next_expiry_at: AwareDatetime | None = None


class MapPage(BaseModel):
    maps: list[MapInfo]
    next_cursor: str | None = None


class MapKeyPage(BaseModel):
    keys: list[str]
    next_cursor: str | None = None


class MapEntry(BaseModel):
    key: str
    value: Annotated[
        Base64Bytes,
        Field(description="Base64 bytes; SDK values are JSON, or cloudpickle (first byte 0x80)."),
    ]
    revision: Annotated[
        str,
        Field(description="Changes on every write; pass it as `if_revision` to compare and set."),
    ]
    expires_at: AwareDatetime | None = None
    updated_at: AwareDatetime


class SetMapEntryRequest(BaseModel):
    value: Annotated[Base64Bytes, Field(description="At most 1 MiB, base64.")]
    ttl_seconds: Annotated[
        int | None,
        Field(
            description="Seconds to expiry, 0 for never; absent keeps an existing expiry.",
            ge=0,
            le=604800,
        ),
    ] = None
    if_revision: Annotated[str | None, Field(pattern="^[0-9]{1,20}$")] = None
    if_absent: bool = False


class MapEntryWrite(BaseModel):
    revision: str
    expires_at: AwareDatetime | None = None


class AppRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="An app name or id.",
            pattern="^([a-z][a-z0-9_]{0,62}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
        ),
    ]


class AppState(str, Enum):
    active = "active"
    paused = "paused"
    deleted = "deleted"


class LiveAppState(str, Enum):
    active = "active"
    paused = "paused"


class WorkloadState(str, Enum):
    active = "active"
    stopped = "stopped"
    deleted = "deleted"


class DeploymentPlanAction(str, Enum):
    add = "add"
    redeploy = "redeploy"
    retain = "retain"
    remove = "remove"


class WorkloadIdentity(BaseModel):
    kind: Literal["function"]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]


class DeploymentPlanItem(BaseModel):
    kind: Literal["function"]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    action: DeploymentPlanAction
    versions: Annotated[int, Field(description="Versions the workload has now.")]


class DeployedWorkload(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    kind: Literal["function"]
    state: WorkloadState
    app_state: AppState | None = None
    version: Annotated[int | None, Field(description="The active version.")] = None
    release_id: Annotated[UUID | None, Field(description="The active release.")] = None
    created_at: AwareDatetime
    deployed_at: Annotated[
        AwareDatetime | None, Field(description="When the active version was deployed.")
    ] = None


class DeploymentPage(BaseModel):
    deployments: list[DeployedWorkload]
    next_cursor: str | None = None


class StartDeploymentRequest(BaseModel):
    version: Annotated[
        int | None, Field(description="Make this deployed version active before starting.", ge=1)
    ] = None


class Version(BaseModel):
    release_id: UUID
    version: int
    active: bool
    created_at: AwareDatetime


class VersionPage(BaseModel):
    versions: list[Version]
    next_cursor: str | None = None


class StopTasksRequest(BaseModel):
    task_ids: Annotated[list[UUID], Field(max_length=1000, min_length=1)]


class StopTasksResponse(BaseModel):
    stopped: Annotated[list[UUID], Field(description="Tasks this request cancelled.")]
    skipped: Annotated[
        list[UUID],
        Field(description="Tasks that were already finished or are not in the workspace."),
    ]


class ContainerState(str, Enum):
    pending = "pending"
    starting = "starting"
    ready = "ready"
    draining = "draining"
    stopped = "stopped"


class StopReason(str, Enum):
    stopped = "stopped"
    load_error = "load_error"
    start_failed = "start_failed"
    crashed = "crashed"
    out_of_memory = "out_of_memory"
    host_lost = "host_lost"


class Container(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    release_id: UUID
    version: Annotated[
        int | None,
        Field(
            description="The deployed version of the release; absent for a working-tree release."
        ),
    ] = None
    state: ContainerState
    stop_reason: StopReason | None = None
    exit_message: str | None = None
    slots: int
    running_tasks: Annotated[int, Field(description="Attempts running now.")]
    cpu_millis: int
    memory_mib: int
    created_at: AwareDatetime
    ready_at: AwareDatetime | None = None
    stopped_at: AwareDatetime | None = None


class ContainerPage(BaseModel):
    containers: list[Container]
    next_cursor: str | None = None


class ImageArchitecture(str, Enum):
    amd64 = "amd64"
    arm64 = "arm64"


BaseImageCredentialsAdditionalProperty = TypeAliasType(
    "BaseImageCredentialsAdditionalProperty", Annotated[str, Field(max_length=65536)]
)


class Architecture(str, Enum):
    amd64 = "amd64"
    arm64 = "arm64"


class PythonPackage(RootModel[str]):
    root: Annotated[str, Field(max_length=1024, min_length=1)]


class Command(RootModel[str]):
    root: Annotated[str, Field(max_length=65536, min_length=1)]


EnvAdditionalProperty = TypeAliasType(
    "EnvAdditionalProperty", Annotated[str, Field(max_length=65536)]
)


class Secret1(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_]{0,127}$")]


class ImageStepKind(str, Enum):
    shell = "shell"
    pip = "pip"
    micromamba = "micromamba"
    uv_project = "uv_project"
    poetry_project = "poetry_project"
    pyproject = "pyproject"
    micromamba_environment = "micromamba_environment"


class Arg(RootModel[str]):
    root: Annotated[str, Field(max_length=1024)]


class Group(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$")]


class ImageStep(BaseModel):
    kind: ImageStepKind
    command: Annotated[str | None, Field(max_length=65536)] = None
    args: Annotated[list[Arg] | None, Field(max_length=1000)] = None
    groups: Annotated[list[Group] | None, Field(max_length=64)] = None


class Image(BaseModel):
    id: Annotated[str, Field(pattern="^img_[0-9a-f]{24}$")]
    python_version: str
    architecture: ImageArchitecture
    ready: Annotated[bool, Field(description="The image is published and can be deployed.")]
    created_at: AwareDatetime
    ready_at: AwareDatetime | None = None


class ImageBuildStatus(str, Enum):
    building = "building"
    succeeded = "succeeded"
    failed = "failed"


class ImageBuildPhase(str, Enum):
    queued = "queued"
    starting = "starting"
    building = "building"
    finished = "finished"


class ImageBuild(BaseModel):
    id: UUID
    image_id: Annotated[str, Field(pattern="^img_[0-9a-f]{24}$")]
    status: ImageBuildStatus
    phase: ImageBuildPhase
    attempt: Annotated[int, Field(description="Build containers started so far, at most 2.")]
    failure: str | None = None
    created_at: AwareDatetime
    finished_at: AwareDatetime | None = None


class ImageBuildLogEntry(BaseModel):
    id: int
    attempt: int
    data: Annotated[
        str, Field(description="One line of build output without its trailing newline.")
    ]
    time: AwareDatetime


class PlanId(str, Enum):
    free = "free"
    team = "team"
    business = "business"


class TermsVersion(str, Enum):
    free_v2 = "free-v2"
    team_v3 = "team-v3"
    business_v2 = "business-v2"


class BillingOwner(str, Enum):
    platform_fleet = "platform_fleet"
    connected_cloud = "connected_cloud"
    self_hosted = "self_hosted"


class RateClass(str, Enum):
    auto = "auto"
    pinned = "pinned"
    non_preemptible = "non_preemptible"
    pinned_non_preemptible = "pinned_non_preemptible"


class PlanEntitlements(BaseModel):
    max_concurrent_cpu_containers: int
    max_concurrent_gpus: int
    gpu_types: Annotated[list[str], Field(description="The GPU models the account may ask for.")]
    max_workspaces: Annotated[int | None, Field(description="Absent when unlimited.")] = None
    max_members: Annotated[
        int | None,
        Field(
            description="People in the account's workspaces, owner included; absent if unlimited."
        ),
    ] = None
    connected_cloud: bool
    custom_domains: bool
    self_hosted: bool
    retention_days: Annotated[int, Field(description="Log and artifact retention.")]
    region_selection: bool
    max_workspace_disk_gib: Annotated[
        int, Field(description="Declared disk size one workspace may hold; 0 is no disks.")
    ]


class PublishedPlan(BaseModel):
    id: PlanId
    terms_version: TermsVersion
    name: str
    summary: str
    monthly_nanos: int
    included_nanos: Annotated[int, Field(description="Usage credit each month.")]
    entitlements: PlanEntitlements
    terms: list[str]


class ShapeRate(BaseModel):
    billing_owner: BillingOwner
    nanos_per_container_hour: int
    nanos_per_cpu_core_hour: int
    nanos_per_memory_gib_hour: int


class CardRates(BaseModel):
    platform_fleet: int
    connected_cloud: int
    self_hosted: int


class ComputeRate(BaseModel):
    billing_owner: BillingOwner
    gpu_type: Annotated[str | None, Field(description="Absent for containers without a GPU.")] = (
        None
    )
    nanos_per_container_hour: int
    nanos_per_cpu_core_hour: int
    nanos_per_memory_gib_hour: int
    nanos_per_gpu_card_hour: int


class PlacementRate(BaseModel):
    rate_class: RateClass
    effective_at: AwareDatetime
    pinned: bool
    preemptible: bool
    name: str
    cpu_memory_multiplier: float
    gpu_multiplier: float
    compute_rates: list[ComputeRate]


class TrialTerms(BaseModel):
    amount_nanos: int
    duration_days: int
    one_time: bool


class NoPaymentMethodTerms(BaseModel):
    max_concurrent_cpu_containers: int
    max_concurrent_gpus: int
    gpu_types: list[str]


class PlatformRate(BaseModel):
    nanos_per_egress_gib: int
    nanos_per_volume_gib_month: int
    storage_month_seconds: int


class DiskRate(BaseModel):
    nanos_per_stored_gib_month: int
    nanos_per_attached_gib_month: int


class CreditPurchaseTerms(BaseModel):
    minimum_cents: int
    maximum_cents: int


class BillingStatus(str, Enum):
    active = "active"
    past_due = "past_due"


class BillingPlan(BaseModel):
    id: PlanId
    name: str
    terms_version: TermsVersion
    monthly_nanos: int
    included_nanos: int
    scheduled_terms_version: TermsVersion | None = None
    scheduled_change_at: AwareDatetime | None = None
    period_started_at: Annotated[
        AwareDatetime | None,
        Field(description="The subscription's billing period; absent on Free."),
    ] = None
    period_ended_at: AwareDatetime | None = None


class EntitlementUsage(BaseModel):
    concurrent_cpu_containers: int
    concurrent_gpus: int
    workspaces: int
    members: int
    connected_clouds: int
    custom_domains: int


class UsageBudget(BaseModel):
    month_started_at: AwareDatetime
    month_ended_at: AwareDatetime
    limit_nanos: Annotated[
        int | None, Field(description="Absent without a monthly usage limit.")
    ] = None
    spent_nanos: int
    available_nanos: int | None = None


class BillingPreferences(BaseModel):
    monthly_usage_limit_nanos: Annotated[
        int | None,
        Field(
            description="Stops new work once reached; resets monthly, UTC. Absent for none.",
            ge=0,
            le=9007199254740991,
        ),
    ] = None
    reload_enabled: bool
    reload_threshold_cents: Annotated[int, Field(ge=0, le=100000)]
    reload_amount_cents: Annotated[int, Field(ge=500, le=100000)]


class ReloadPauseReason(str, Enum):
    declined = "declined"
    action_required = "action_required"


class AutomaticReload(BaseModel):
    paused_purchase_id: UUID | None = None
    pause_reason: ReloadPauseReason | None = None
    pending_purchase_id: UUID | None = None
    month_started_at: AwareDatetime
    month_ended_at: AwareDatetime
    monthly_payment_committed_cents: int


class BillingAccount(BaseModel):
    status: BillingStatus
    currency: str
    plan: BillingPlan
    portal_available: Annotated[
        bool,
        Field(description="Stripe holds a customer for the account, so invoices can be shown."),
    ]
    payment_method_on_file: bool
    complimentary_since: Annotated[
        AwareDatetime | None,
        Field(description="When an administrator waived the account's usage charges."),
    ] = None
    entitlements: PlanEntitlements
    usage: EntitlementUsage
    balance_nanos: Annotated[
        int,
        Field(description="Prepaid credit left; negative is usage the next credit covers first."),
    ]
    usage_budget: UsageBudget
    preferences: BillingPreferences
    automatic_reload: AutomaticReload
    plan_change_pending: Annotated[
        bool, Field(description="A plan change is waiting on Stripe's answer.")
    ]


class PlanChangeRequest(BaseModel):
    plan: PlanId
    terms_version: TermsVersion


class HostedSessionRequest(BaseModel):
    return_url: Annotated[
        str,
        Field(
            description="A dashboard page; other origins are refused.",
            max_length=2048,
            min_length=1,
        ),
    ]
    cancel_url: Annotated[
        str | None,
        Field(
            description="Where to return on abandoning the page; defaults to return_url.",
            max_length=2048,
        ),
    ] = None


class HostedSession(BaseModel):
    url: str


class CreditPurchaseRequest(BaseModel):
    request_key: UUID
    amount_cents: Annotated[int, Field(ge=500, le=100000)]
    return_url: Annotated[str, Field(max_length=2048, min_length=1)]
    cancel_url: Annotated[str | None, Field(max_length=2048)] = None


class CreditPaymentStatus(str, Enum):
    pending = "pending"
    action_required = "action_required"
    succeeded = "succeeded"
    declined = "declined"
    cancelled = "cancelled"


class Kind(str, Enum):
    manual = "manual"
    automatic = "automatic"


class CreditPurchase(BaseModel):
    id: UUID
    kind: Kind
    amount_nanos: int
    status: CreditPaymentStatus
    checkout_url: Annotated[
        str | None, Field(description="Stripe Checkout, while the purchase is pending.")
    ] = None
    funded_at: AwareDatetime | None = None
    reversed_nanos: Annotated[int, Field(description="Refunded or disputed credit taken back.")]
    created_at: AwareDatetime


class ComplimentaryRequest(BaseModel):
    complimentary: bool


class PlatformRole(str, Enum):
    admin = "admin"
    user = "user"


class UserStatus(str, Enum):
    active = "active"
    disabled = "disabled"


class BillingAccountAdmin(BaseModel):
    user: User
    user_status: UserStatus
    plan: PlanId | None = None
    status: BillingStatus | None = None
    payment_method_on_file: bool
    complimentary_since: AwareDatetime | None = None
    recent_cost_nanos: Annotated[
        int, Field(description="Usage cost since recent_cost_since, waived or not.")
    ]
    recent_cost_since: AwareDatetime


class BillingAccountAdminPage(BaseModel):
    accounts: list[BillingAccountAdmin]
    next_cursor: Annotated[str | None, Field(description="Present when more accounts follow.")] = (
        None
    )


class UsageCostGroup(str, Enum):
    app = "app"
    workload = "workload"
    task = "task"


class UsageCostCategory(str, Enum):
    image_build = "image-build"
    unattributed = "unattributed"


class UsageCostBucket(str, Enum):
    hour = "hour"
    day = "day"


class BilledDimension(str, Enum):
    compute_runtime = "compute_runtime"
    network_egress = "network_egress"
    volume_storage = "volume_storage"
    disk = "disk"


class UsageCostComponentKind(str, Enum):
    container_time = "container_time"
    cpu = "cpu"
    memory = "memory"
    gpu = "gpu"


class UsageCostComponent(BaseModel):
    dimension: BilledDimension
    component: UsageCostComponentKind
    quantity: float
    cost_nanos: int


class UsageCostRow(BaseModel):
    workspace_id: UUID
    workspace_name: str | None = None
    app_id: UUID | None = None
    app_name: str | None = None
    workload_id: UUID | None = None
    workload_name: str | None = None
    workload_kind: str | None = None
    task_id: UUID | None = None
    category: UsageCostCategory | None = None
    cost_nanos: int
    components: list[UsageCostComponent]


class UsageCostPage(BaseModel):
    start: AwareDatetime
    end: AwareDatetime
    currency: str
    group_by: UsageCostGroup
    cost_nanos: Annotated[int, Field(description="The whole window's cost, not the page's.")]
    rows: list[UsageCostRow]
    next_cursor: Annotated[str | None, Field(description="Present when more rows follow.")] = None


class UsageCostDimension(BaseModel):
    dimension: BilledDimension
    cost_nanos: int


class Error(BaseModel):
    code: ErrorCode
    message: str


class Workspace(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[a-z][a-z0-9-]{0,62}$")]
    state: WorkspaceState
    role: Annotated[
        WorkspaceRole | None,
        Field(description="The caller's role; absent for an administrator who is not a member."),
    ] = None
    created_at: AwareDatetime


class WorkspaceList(BaseModel):
    workspaces: list[Workspace]
    next_cursor: Annotated[
        str | None,
        Field(
            description="Pass as `cursor` for the next page; absent after the last.",
            pattern="^[a-z][a-z0-9-]{0,62}$",
        ),
    ] = None


class MemberRoleRequest(BaseModel):
    role: InvitationRole


class AcceptedInvitation(BaseModel):
    workspace: Workspace
    member: Member


class SourceUpload(BaseModel):
    sha256: Annotated[
        str, Field(description="Lowercase hex SHA-256 digest", pattern="^[0-9a-f]{64}$")
    ]
    present: Annotated[bool, Field(description="The archive is stored and can be deployed.")]
    upload: UploadTarget | None = None


class App(BaseModel):
    id: UUID
    name: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    state: AppState
    workloads: Annotated[int, Field(description="Deployed workloads that are not deleted.")]
    created_at: AwareDatetime


class ImageSpec(BaseModel):
    python_version: Annotated[
        PythonVersion, Field(description="The Python minor version the runtime is mounted for.")
    ]
    image_id: Annotated[str | None, Field(pattern="^img_[0-9a-f]{24}$")] = None
    reference: Annotated[
        str | None, Field(description="The image by digest the release runs, set by the server.")
    ] = None


class SubmitTasksRequest(BaseModel):
    inputs: Annotated[list[TaskInput], Field(max_length=1000, min_length=1)]
    release_id: Annotated[
        UUID | None,
        Field(
            description="Run on this release, such as a prepared one, instead of the active one."
        ),
    ] = None
    parent_task_id: Annotated[
        UUID | None, Field(description="The task that submits these, which becomes their parent.")
    ] = None


class TaskPendingProgress(BaseModel):
    reason: TaskPendingReason
    message: str
    since: Annotated[AwareDatetime, Field(description="When the current reason began.")]
    pending_since: Annotated[
        AwareDatetime, Field(description="When the task last became due or was submitted.")
    ]
    observed_at: AwareDatetime


class LifecycleHooks(BaseModel):
    on_start: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_running: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_success: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_error: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_retry: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_failure: Annotated[list[HookReference] | None, Field(max_length=16)] = None
    on_finish: Annotated[list[HookReference] | None, Field(max_length=16)] = None


class VolumeMountSpec(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$")]
    mount_path: Annotated[
        str | None,
        Field(
            description="Absolute, or relative to /volumes; the default is /volumes/<name>.",
            max_length=1024,
        ),
    ] = None
    read_only: bool = False
    cloud_bucket: CloudBucketSpec | None = None


class AppPage(BaseModel):
    apps: list[App]
    next_cursor: Annotated[str | None, Field(description="Present when another page follows.")] = (
        None
    )


class DeploymentPlanRequest(BaseModel):
    workloads: Annotated[list[WorkloadIdentity], Field(max_length=200)]
    prune: bool = False


class DeploymentPlan(BaseModel):
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    prune: bool
    items: Annotated[
        list[DeploymentPlanItem],
        Field(description="Listed workloads by kind and name, then omitted deployed ones."),
    ]


class ImageDefinition(BaseModel):
    python_version: Annotated[
        str,
        Field(
            description="A supported minor release or an exact patch release.",
            pattern="^3\\.(10|11|12|13|14)(\\.[0-9]{1,3})?$",
        ),
    ]
    micromamba: Annotated[
        bool, Field(description="Micromamba provides Python and the base environment.")
    ] = False
    base_image: Annotated[
        str | None,
        Field(description="A registry image to start from.", max_length=512, min_length=1),
    ] = None
    base_image_credentials: Annotated[
        dict[str, BaseImageCredentialsAdditionalProperty] | None,
        Field(description="Registry credentials by environment variable name.", max_length=32),
    ] = None
    architecture: Architecture = Architecture.amd64
    python_packages: Annotated[list[PythonPackage] | None, Field(max_length=1000)] = None
    steps: Annotated[list[ImageStep] | None, Field(max_length=1000)] = None
    commands: Annotated[list[Command] | None, Field(max_length=1000)] = None
    env: Annotated[dict[str, EnvAdditionalProperty] | None, Field(max_length=256)] = None
    dockerfile: Annotated[
        str | None,
        Field(
            description="A Dockerfile that replaces the base image and Python setup.",
            max_length=1048576,
        ),
    ] = None
    context: SourceRef | None = None
    secrets: Annotated[
        list[Secret1] | None,
        Field(description="Workspace secrets the build reads as build arguments.", max_length=64),
    ] = None
    gpu: Annotated[
        str | None, Field(description="The GPU model the build runs on.", max_length=64)
    ] = None


class ImageResolution(BaseModel):
    image: Image
    build: ImageBuild | None = None


class GpuRate(BaseModel):
    gpu_type: str
    nanos_per_card_hour: CardRates


class PricingCatalog(BaseModel):
    trial: TrialTerms
    pricing_version: str
    metered_rates_effective_at: AwareDatetime
    currency: str
    connected_cloud_management_fee_percent: int
    no_payment_method: NoPaymentMethodTerms
    plans: list[PublishedPlan]
    shape_rates: Annotated[
        list[ShapeRate],
        Field(description="Automatic placement rates for containers without a GPU."),
    ]
    gpu_rates: list[GpuRate]
    platform_rate: PlatformRate
    disk_rate: DiskRate | None = None
    placement_rates: list[PlacementRate]
    credit_purchase: CreditPurchaseTerms


class UsageCostInterval(BaseModel):
    started_at: AwareDatetime
    ended_at: AwareDatetime
    cost_nanos: int
    dimensions: Annotated[
        list[UsageCostDimension],
        Field(description="Only the invoice lines metered in the interval."),
    ]


class UsageCostSeries(BaseModel):
    start: AwareDatetime
    end: AwareDatetime
    currency: str
    bucket: UsageCostBucket
    cost_nanos: int
    subscription_credit_nanos: Annotated[
        int, Field(description="Usage in the window that subscription credit covered.")
    ]
    intervals: list[UsageCostInterval]


class Me(BaseModel):
    user: User
    workspaces: list[Workspace]


class FunctionSpec(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    handler: Annotated[
        str,
        Field(
            description="module:qualname within the source archive",
            pattern="^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*$",
        ),
    ]
    source: SourceRef
    image: ImageSpec
    resources: Resources
    timeout_seconds: Annotated[int, Field(ge=1, le=86400)] = 3600
    retry_policy: RetryPolicy | None = None
    concurrency: Annotated[
        int,
        Field(description="Tasks one container runs at once, one process per slot.", ge=1, le=256),
    ] = 1
    keep_warm_seconds: Annotated[
        int | None,
        Field(
            description="Idle seconds before a container above the minimum stops.", ge=-1, le=86400
        ),
    ] = None
    autoscaler: Autoscaler | None = None
    max_pending_tasks: Annotated[int, Field(ge=1, le=1000000)] = 100
    environment: dict[str, str] | None = None
    cron: Annotated[
        str | None,
        Field(description="Run the function on this UTC schedule.", max_length=160, min_length=1),
    ] = None
    secrets: Annotated[
        list[SecretName] | None,
        Field(
            description="Secrets the container receives as environment variables of the same name.",
            max_length=100,
        ),
    ] = None
    callback_url: Annotated[
        str | None,
        Field(
            description="Receives a signed POST when a task is retried or finishes.",
            max_length=2048,
        ),
    ] = None
    in_process: Annotated[
        bool, Field(description="Run the concurrency slots as threads of one runner process.")
    ] = False
    lifecycle_hooks: LifecycleHooks | None = None
    volumes: Annotated[list[VolumeMountSpec] | None, Field(max_length=32)] = None
    client_contract: Annotated[
        dict[str, Any] | None,
        Field(description="The signature `lazycloud app export` types clients from."),
    ] = None


class Release(BaseModel):
    id: UUID
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    version: Annotated[
        int | None,
        Field(
            description="The deployed version; absent for a release only working-tree calls use."
        ),
    ] = None
    created_at: AwareDatetime
    spec: FunctionSpec


class Function(BaseModel):
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    state: State
    active_release: Release
    schedule: Schedule | None = None


class Task(BaseModel):
    id: UUID
    app: Annotated[str, Field(pattern="^[a-z][a-z0-9_]{0,62}$")]
    function: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_-]{0,62}$")]
    release_id: UUID
    version: Annotated[
        int | None,
        Field(
            description="The deployed version of the release; absent for a working-tree release."
        ),
    ] = None
    status: TaskStatus
    attempts: Annotated[int, Field(description="Attempts started so far.")]
    max_attempts: int
    parent_task_id: Annotated[
        UUID | None, Field(description="The running task that spawned this one.")
    ] = None
    root_task_id: Annotated[
        UUID,
        Field(description="The root of the call graph; the task itself when nothing spawned it."),
    ]
    scheduled_for: Annotated[
        AwareDatetime | None, Field(description="The cron occurrence that admitted the task.")
    ] = None
    container_id: Annotated[
        UUID | None, Field(description="The container of the latest attempt.")
    ] = None
    next_attempt_at: Annotated[
        AwareDatetime | None,
        Field(description="When a queued task that already ran becomes due again."),
    ] = None
    pending: TaskPendingProgress | None = None
    created_at: AwareDatetime
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None
    failure: TaskFailure | None = None


class TaskPage(BaseModel):
    tasks: list[Task]
    next_cursor: str | None = None


class DeploymentRequest(BaseModel):
    functions: Annotated[
        list[FunctionSpec],
        Field(
            description="At least one, unless prune deletes every deployed function.",
            max_length=200,
        ),
    ]
    prune: Annotated[
        bool, Field(description="Delete every function of the app that is not listed.")
    ] = False


class Deployment(BaseModel):
    app: App
    releases: list[Release]
    pruned: Annotated[list[WorkloadName], Field(description="Functions the prune deleted.")]
    removed_versions: Annotated[int, Field(description="Versions of the pruned functions.")]


class SubmitTasksResponse(BaseModel):
    tasks: list[Task]
