// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package secrets

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSecret = `-- name: DeleteSecret :execrows
delete from secrets where workspace_id = $1 and name = $2
`

type DeleteSecretParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.WorkspaceID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSecret = `-- name: InsertSecret :one
insert into secrets (workspace_id, name, key_id, wrapped_key, nonce, ciphertext)
values ($1, $2, $3, $4, $5, $6)
on conflict (workspace_id, name) do nothing
returning name, created_at, updated_at
`

type InsertSecretParams struct {
	WorkspaceID uuid.UUID
	Name        string
	KeyID       string
	WrappedKey  []byte
	Nonce       []byte
	Ciphertext  []byte
}

type InsertSecretRow struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (InsertSecretRow, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyID,
		arg.WrappedKey,
		arg.Nonce,
		arg.Ciphertext,
	)
	var i InsertSecretRow
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
select name, created_at, updated_at
from secrets
where workspace_id = $1 and name > $2
order by name
limit $3
`

type ListSecretsParams struct {
	WorkspaceID uuid.UUID
	After       string
	MaxRows     int32
}

type ListSecretsRow struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, arg.WorkspaceID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsRow
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sealedSecrets = `-- name: SealedSecrets :many
select name, key_id, wrapped_key, nonce, ciphertext, created_at, updated_at
from secrets
where workspace_id = $1 and name = any($2::text[])
`

type SealedSecretsParams struct {
	WorkspaceID uuid.UUID
	Names       []string
}

type SealedSecretsRow struct {
	Name       string
	KeyID      string
	WrappedKey []byte
	Nonce      []byte
	Ciphertext []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) SealedSecrets(ctx context.Context, arg SealedSecretsParams) ([]SealedSecretsRow, error) {
	rows, err := q.db.Query(ctx, sealedSecrets, arg.WorkspaceID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SealedSecretsRow
	for rows.Next() {
		var i SealedSecretsRow
		if err := rows.Scan(
			&i.Name,
			&i.KeyID,
			&i.WrappedKey,
			&i.Nonce,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretMetadata = `-- name: SecretMetadata :one
select name, created_at, updated_at from secrets where workspace_id = $1 and name = $2
`

type SecretMetadataParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

type SecretMetadataRow struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SecretMetadata(ctx context.Context, arg SecretMetadataParams) (SecretMetadataRow, error) {
	row := q.db.QueryRow(ctx, secretMetadata, arg.WorkspaceID, arg.Name)
	var i SecretMetadataRow
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateSecret = `-- name: UpdateSecret :one
update secrets
set key_id = $1, wrapped_key = $2, nonce = $3, ciphertext = $4, updated_at = now()
where workspace_id = $5 and name = $6
returning name, created_at, updated_at
`

type UpdateSecretParams struct {
	KeyID       string
	WrappedKey  []byte
	Nonce       []byte
	Ciphertext  []byte
	WorkspaceID uuid.UUID
	Name        string
}

type UpdateSecretRow struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (UpdateSecretRow, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.KeyID,
		arg.WrappedKey,
		arg.Nonce,
		arg.Ciphertext,
		arg.WorkspaceID,
		arg.Name,
	)
	var i UpdateSecretRow
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const upsertSecret = `-- name: UpsertSecret :one
insert into secrets (workspace_id, name, key_id, wrapped_key, nonce, ciphertext)
values ($1, $2, $3, $4, $5, $6)
on conflict (workspace_id, name) do update
set key_id = excluded.key_id,
    wrapped_key = excluded.wrapped_key,
    nonce = excluded.nonce,
    ciphertext = excluded.ciphertext,
    updated_at = now()
returning name, created_at, updated_at
`

type UpsertSecretParams struct {
	WorkspaceID uuid.UUID
	Name        string
	KeyID       string
	WrappedKey  []byte
	Nonce       []byte
	Ciphertext  []byte
}

type UpsertSecretRow struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (UpsertSecretRow, error) {
	row := q.db.QueryRow(ctx, upsertSecret,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyID,
		arg.WrappedKey,
		arg.Nonce,
		arg.Ciphertext,
	)
	var i UpsertSecretRow
	err := row.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
