apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
      envoyHpa:
        minReplicas: {{ .Values.envoyProxy.minReplicas }}
        maxReplicas: {{ .Values.envoyProxy.maxReplicas }}
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 80
      envoyDeployment:
        replicas: {{ .Values.envoyProxy.minReplicas }}
        pod:
          {{- with .Values.envoyProxy.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- range . }}
            - maxSkew: {{ .maxSkew }}
              topologyKey: {{ .topologyKey }}
              whenUnsatisfiable: {{ .whenUnsatisfiable }}
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
                  app.kubernetes.io/component: proxy
                  gateway.envoyproxy.io/owning-gateway-name: {{ $.Values.gateway.name }}
            {{- end }}
          {{- end }}
        container:
          resources:
            {{- toYaml .Values.envoyProxy.resources | nindent 12 }}
  telemetry:
    metrics:
      prometheus:
        disable: false
