from __future__ import annotations

NAME = "lazycloud"
DISPLAY_NAME = NAME.replace("-", " ").title()
ENV_PREFIX = NAME.upper().replace("-", "_")
_LABEL_NAME = "".join(part.capitalize() for part in NAME.replace("_", "-").split("-"))
HOME_DIR = f".{NAME}"
STATE_DIR = f"/var/lib/{NAME}"
CACHE_DIR = f"{STATE_DIR}/cache"
CACHE_PAGES_DIR = f"{CACHE_DIR}/pages"
WORKER_BUNDLE_ROOT = f"/tmp/{NAME}-containers"
WORKER_CHECKPOINT_ROOT = f"/tmp/{NAME}-checkpoints"
CHECKPOINT_SIGNAL_ROOT = f"/tmp/{NAME}-checkpoint-signals"
MANAGED_PACKAGE_ROOT = f"/tmp/{NAME}-packages"
FUNCTION_IMAGE = f"{NAME}-function"
ENDPOINT_IMAGE = f"{NAME}-endpoint"
TASK_QUEUE_IMAGE = f"{NAME}-taskqueue"
POD_IMAGE = f"{NAME}-pod"
SHELL_IMAGE = f"{NAME}-shell"
SHELL_LOG_PATH = f"/tmp/{NAME}-shell.log"
AGENT_CONTAINER_TMP_PATH = f"/tmp/{NAME}"
AGENT_CONTAINER_LOG_PATH = f"/var/log/{NAME}"
AGENT_STATE_DIR = f"{STATE_DIR}/agent"
# The agent spawns its own tailscaled under its state directory; nothing else on
# the node opens a tailnet session, so these paths have one owner.
AGENT_TAILNET_DIR_NAME = "tailnet"
TAILSCALED_SOCKET_NAME = "tailscaled.sock"
TAILSCALED_STATE_NAME = "tailscaled.state"
AGENT_CONTAINER_DATA_PATH = f"{AGENT_STATE_DIR}/data"
AGENT_CONTAINER_OBJECT_PATH = f"{AGENT_CONTAINER_DATA_PATH}/objects"
AGENT_WORKER_CONFIG_PATH = f"/etc/{NAME}/worker/config.json"
CLI_NAME = NAME
ADMIN_CLI_NAME = f"{NAME}-admin"
REDIS_KEY_PREFIX = NAME
OBJECT_STORE_BUCKET = f"{NAME}-objects"
DATA_STORAGE_BUCKET = f"{NAME}-data"
OBJECT_STORE_ACCESS_KEY_ID = NAME
OBJECT_STORE_SECRET_ACCESS_KEY = f"{NAME}-secret"
WORKSPACE_OBJECT_BUCKET = "default"
IMAGE_BUILD_CONTEXT_BUCKET = "build-contexts"
CLUSTER_NAME_LABEL = f"{_LABEL_NAME}ClusterName"
POOL_NAME_LABEL = f"{_LABEL_NAME}PoolName"
MACHINE_ID_LABEL = f"{_LABEL_NAME}MachineId"
DEFAULT_RESOURCE_TYPE = NAME
EVENT_SOURCE = f"{NAME}-cluster"
INTERNAL_WEBHOOK_FORMAT = f"{NAME}-webhook"
METRICS_NAMESPACE = NAME.replace("-", "_")
AGENT_NAME = f"{NAME}-agent"
AGENT_SERVICE_DESCRIPTION = f"{DISPLAY_NAME} agent"
AGENT_LAUNCHD_LABEL_PREFIX = f"com.{NAME}.agent"
CONTROL_PLANE_SERVICE_NAME = f"{NAME}-api"
# The control plane's tailnet device name. Distinct from the process name
# above: this is what a node dials, so the deployment origin a remote
# machine is given has to match it exactly.
CONTROL_PLANE_TAILNET_HOSTNAME = f"{NAME}-control-plane"
CONTROL_PLANE_IMAGE = "api"
SCHEDULER_PROCESS_NAME = f"{NAME}-scheduler"
SCHEDULER_IMAGE = "scheduler"
CONTAINER_WORKER_PROCESS_NAME = f"{NAME}-container-worker"
CONTAINER_WORKER_IMAGE = "container-worker"
CONTAINER_HELPER_PATH = f"/usr/local/bin/{NAME}-sandbox-supervisor"
WORKER_BOOTSTRAP_PROCESS_NAME = f"{NAME}-worker-bootstrap"
WORKER_BOOTSTRAP_IMAGE = "worker-bootstrap"
CACHE_SERVER_PROCESS_NAME = f"{NAME}-cache-server"
CACHE_SERVER_IMAGE = "cache-server"
SANDBOX_COMPOSE_OVERRIDE_PATH = f"/tmp/{NAME}-docker-compose.override.yml"
METRICS_SOURCE = NAME
PRIVATE_RESOURCE_PREFIX = f"{NAME}-private"
SOURCE_CACHE_DIR = f"{NAME}-source-cache"
SOURCE_PACKAGE_BUCKET = f"{NAME}-source-packages"
WORKSPACE_UPLOAD_BUCKETS = frozenset(
    {WORKSPACE_OBJECT_BUCKET, SOURCE_PACKAGE_BUCKET, IMAGE_BUILD_CONTEXT_BUCKET}
)

__all__ = [
    "ADMIN_CLI_NAME",
    "AGENT_CONTAINER_DATA_PATH",
    "AGENT_CONTAINER_LOG_PATH",
    "AGENT_CONTAINER_OBJECT_PATH",
    "AGENT_CONTAINER_TMP_PATH",
    "AGENT_LAUNCHD_LABEL_PREFIX",
    "AGENT_NAME",
    "AGENT_SERVICE_DESCRIPTION",
    "AGENT_STATE_DIR",
    "AGENT_TAILNET_DIR_NAME",
    "AGENT_WORKER_CONFIG_PATH",
    "CACHE_DIR",
    "CACHE_PAGES_DIR",
    "CACHE_SERVER_IMAGE",
    "CACHE_SERVER_PROCESS_NAME",
    "CHECKPOINT_SIGNAL_ROOT",
    "CLI_NAME",
    "CLUSTER_NAME_LABEL",
    "CONTAINER_HELPER_PATH",
    "CONTAINER_WORKER_IMAGE",
    "CONTAINER_WORKER_PROCESS_NAME",
    "CONTROL_PLANE_IMAGE",
    "CONTROL_PLANE_SERVICE_NAME",
    "CONTROL_PLANE_TAILNET_HOSTNAME",
    "DATA_STORAGE_BUCKET",
    "DEFAULT_RESOURCE_TYPE",
    "DISPLAY_NAME",
    "ENDPOINT_IMAGE",
    "ENV_PREFIX",
    "EVENT_SOURCE",
    "FUNCTION_IMAGE",
    "HOME_DIR",
    "IMAGE_BUILD_CONTEXT_BUCKET",
    "INTERNAL_WEBHOOK_FORMAT",
    "MACHINE_ID_LABEL",
    "MANAGED_PACKAGE_ROOT",
    "METRICS_NAMESPACE",
    "METRICS_SOURCE",
    "NAME",
    "OBJECT_STORE_ACCESS_KEY_ID",
    "OBJECT_STORE_BUCKET",
    "OBJECT_STORE_SECRET_ACCESS_KEY",
    "POD_IMAGE",
    "POOL_NAME_LABEL",
    "PRIVATE_RESOURCE_PREFIX",
    "REDIS_KEY_PREFIX",
    "SANDBOX_COMPOSE_OVERRIDE_PATH",
    "SCHEDULER_IMAGE",
    "SCHEDULER_PROCESS_NAME",
    "SHELL_IMAGE",
    "SHELL_LOG_PATH",
    "SOURCE_CACHE_DIR",
    "SOURCE_PACKAGE_BUCKET",
    "STATE_DIR",
    "TAILSCALED_SOCKET_NAME",
    "TAILSCALED_STATE_NAME",
    "TASK_QUEUE_IMAGE",
    "WORKER_BOOTSTRAP_IMAGE",
    "WORKER_BOOTSTRAP_PROCESS_NAME",
    "WORKER_BUNDLE_ROOT",
    "WORKER_CHECKPOINT_ROOT",
    "WORKSPACE_OBJECT_BUCKET",
    "WORKSPACE_UPLOAD_BUCKETS",
]
