name: Backend Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/backend/**'
      - 'packages/**'
      - '.github/workflows/backend_tests.yml'

jobs:
  backend-tests:
    runs-on: depot-ubuntu-24.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: lc_dev
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6432:6432
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      DATABASE_URL: postgresql+asyncpg://lc_dev:password@localhost:6432/postgres
      REDIS_URL: redis://localhost:6379
      # these are not used in the tests, but are required by the app
      ADMIN_API_KEY: test-admin-key
      AWS_ACCOUNT_ID: "000000000000"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ECR_BASE_ROLE_ARN: arn:aws:iam::000000000000:role/LazyCloudECRBaseRole
      DB_SECRET_KEY: zkylH2X8q71YyllmlO4kL_8wmQc7JRooJgGppjWV5Hc=
      RESEND_API_KEY: test-resend-key
      PROMETHEUS_URL: http://localhost:9090
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --all-packages --dev

      - name: Run database migrations
        working-directory: apps/backend
        run: uv run alembic upgrade head

      - name: Run backend tests
        working-directory: apps/backend
        run: uv run pytest -v
